---
title: 'KAWN: Parameters vs Energetics'
author: "Michelle Catherine Kelly"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(lubridate)
library(tidyr)
library(grid)
library(gridExtra)
library(dplyr)
library(ggplot2)
library(ggpmisc)
library(imputeTS)

# Toggle this variable based on if you would like to compute new results
# or load old results
# recompile <- FALSE: load old results from output file, good if you're just
#                     interested in plotting and want to save time
# recompile <- TRUE: (re)compute results from raw data

recompile <- TRUE
```

```{r Load uptake data}
# UPDATE: Change this to load an RData file (so everyhtings preserved)
# update file name if needed
# make sure uptake variable name is same as following chunk
NitrateUptake <- read.csv(file = "./Outputs/NitrateUptakeResults_Eqn2.csv")
NitrateUptake$Date <- lubridate::ymd(NitrateUptake$Date)
```

```{r Compile uptake data, eval = recompile}
# Calculate autotrophic nitrate uptake (Ua-NO3) based on Heffernan and Cohen 
# 2010

## Load in raw data ##
# These CSV files can be downloaded from the StreamPULSE database
eric <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASREASTLAWRENCE_sensorData.csv",
           header = TRUE)
steve <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASRFALLLEAF_sensorData.csv", 
           header = TRUE)
desoto <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASR_sensorData.csv", 
           header = TRUE)

## Prep data for calculations ##
# Input: Sensor data frame
# Output: Sensor data frame with added columns for local time, data flagged 
# "Bad Data" removed

prepper <- function(sensor_data){
  # Format datetime column correctly
  sensor_data$DateTime_UTC <- 
    lubridate::ymd_hms(sensor_data$DateTime_UTC)
  # Add column for local time
  sensor_data$DateTime_CST <- 
    lubridate::with_tz(sensor_data$DateTime_UTC, 
                       tzone = "America/Chicago")
  #
  # Remove data that's been flagged as "Bad Data"
  sensor_data$value[sensor_data$flagtype %in% c("Bad Data")] <- NA
  # Remove flagtype and flagcomment columns
  sensor_data$flagtype <- NULL
  sensor_data$flagcomment <- NULL
  # Reshape dataframe from long to wide format
  sensor_data <- tidyr::spread(sensor_data, 
                               key = variable, value = value)
  # Create new dataframe with only data needed for uptake calculation
  sensor_uptake <- sensor_data[c("DateTime_UTC", "DateTime_CST",
                                 "Discharge_m3s", "Nitrate_mgL")]
  # Interpolate gaps in data
  sensor_uptake <- imputeTS::na.interpolation(sensor_uptake)
  # Return new dataframe
  return(sensor_uptake)
}

# Run function
eric_uptake <- prepper(eric)
steve_uptake <- prepper(steve)
desoto_uptake <- prepper(desoto)

##### Take out some of the variability due to changing Q #######################

variability.smoother <- function(uptake_data){
  # Section dates before 1 May 2018
  uptake_data <- uptake_data[uptake_data$DateTime_CST < 
                               ymd_hms("2018-05-01 00:00:00"),]
  # Visualize discharge through time
  plot(y = uptake_data$Discharge_m3s, 
     x = uptake_data$DateTime_CST, 
     main = "Discharge at Desoto",
     ylab = "Discharge, m3 / s", xlab = "DateTime")
  # Take the difference between each discharge measurement using diff()
  varib <- data.frame(DateTime_CST = uptake_data$DateTime_CST
                           [2:length(uptake_data$DateTime_CST)],
                           month = months(uptake_data$DateTime_CST)
                           [2:length(uptake_data$DateTime_CST)], 
                           diff.Discharge = diff(uptake_data$Discharge_m3s))
  # Extract outliers of all observations using base boxplot
  stats <- boxplot(varib$diff.Discharge)
  # Boxplot statistics output:
  # [1,1] extreme of lower whisker, [2,1] Q1, [3,1] median, 
  # [4,1] Q3, [5,1] extreme of upper whisker
  Q1 <- stats$stats[2,1]
  Q3 <- stats$stats[4,1]
  IQR <- Q3 - Q1
  
  # Boxplot to visualize variability
  #ggplot(varib) + 
    #stat_boxplot(aes(x = "All", y = diff.Discharge), geom = "errorbar", 
                 #width = 0.5) +
    #geom_boxplot(aes(x = "All", y = diff.Discharge), outlier.shape = 1) +
    #stat_boxplot(aes(x = month, y = diff.Discharge), geom = "errorbar",
                 #width = 0.5) +
    #geom_boxplot(aes(x = month, y = diff.Discharge), outlier.shape = 1) +
    #geom_hline(yintercept = Q3 + 5*IQR, linetype = 2) +
    #geom_hline(yintercept = Q1 - 5*IQR, linetype = 2) +
    #scale_x_discrete(limits = c("All", "January", "February", "March", 
                                #"April")) +
    #labs(x = NULL, y = "delta Discharge, m3 / s", 
         #title = "Change in discharge between \nmeasurements at Desoto") +
    #theme_classic()
  
  # Select extreme outliers
  # > Q3 + 3*IQR or < Q1 - 3*IQR
  varib$flag[varib$diff.Discharge > Q3 + 5*IQR] <- "outlier"
  varib$flag[varib$diff.Discharge < Q1 - 5*IQR] <- "outlier"
  # Transfer over outlier flags to original data
  uptake_data <- dplyr::full_join(uptake_data, varib[c(-2)], by = "DateTime_CST")
  
  # Visualize the points that have been selected as extreme outliers
  # Selected outliers in red
  #ggplot(uptake_data, aes(x = DateTime_CST)) +
    #geom_line(aes(y = diff.Discharge), shape = 1) +
    #geom_point(aes(y = diff.Discharge[flag == "outlier"]), color = "red", 
               #shape = 1) +
    #labs(x = NULL, y = "delta Discharge, m3 / s", 
         #title = "Change in discharge between \nmeasurements at Desoto") +
    #theme_classic()
  
  #ggplot(uptake_data) +
    #geom_point(data = subset(uptake_data, is.na(uptake_data$flag)),
                             #aes(x = DateTime_CST[is.na(flag)], 
                                 #y = Discharge_m3s[is.na(flag)]), shape = 1) +
    #geom_point(data = uptake_data, 
               #aes(x = DateTime_CST[flag == "outlier"],
                   #y = Discharge_m3s[flag == "outlier"]), color = "red", 
               #shape = 1) +
    #labs(x = NULL, y = "Discharge, m3 / s", 
         #title = "Discharge at Desoto") +
    #theme_classic()
  
  # Add column for corrected nitrate concentrations (where outlier data is now NA)
  uptake_data$Nitrate_mgL.corr <- uptake_data$Nitrate_mgL
  uptake_data$Nitrate_mgL.corr[uptake_data$flag == "outlier"] <- NA
  # Remove hours of data where there are 3 or more outliers present
  uptake_data <- uptake_data %>%
    group_by(date = lubridate::date(DateTime_CST), 
             hour = lubridate::hour(DateTime_CST)) %>%
    mutate(na.count = sum(is.na(Nitrate_mgL.corr))) %>%
    mutate(Nitrate_mgL.corr = ifelse(na.count >= 3, NA, Nitrate_mgL.corr))
  
  # visualize removed outliers (in red)
  #ggplot(uptake_data) +
    #geom_point(aes(x = DateTime_CST, y = Nitrate_mgL), shape = 1, col = "red") +
      #geom_point(aes(x = DateTime_CST, y = Nitrate_mgL.corr), shape = 1)
  
  # Amend Nitrate_mgL data with corrected data
  uptake_data$Nitrate_mgL <- uptake_data$Nitrate_mgL.corr
  # Return datatframe
  return(uptake_data)
}

eric_smooth <- variability.smoother(eric_uptake)
steve_smooth <- variability.smoother(steve_uptake)
desoto_smooth <- variability.smoother(desoto_uptake)



#### Specify equation used to calculate uptake #################################

# If UptakeEqn == 1, calculate uptake using the 
# extrapolated diel method (Heffernan and Cohen 
# 2010, Eqn. 1)
# If UptakeEqn == 2, calculate uptake using the 
# integrated diel method (Heffernan and Cohen 
# 2010, Eqn. 2)
UptakeEqn <- 2

#### Calculate uptake using Equation 1 ########################################
if (UptakeEqn == 1) {

  # Function to calculate uptake
  # Input: the dataframe spit out by prepper()
  # Output: Calculated NO3 Uptake
  
  HC_Eqn1 <- function(prepped_df){
    
    # Take hourly average nitrate concentration
    avg_df <- 
      prepped_df %>%
      dplyr::group_by(date = lubridate::date(DateTime_CST),
                      hour = lubridate::hour(DateTime_CST)) %>%
      dplyr::summarise(DateTime_CST = unique(floor_date(DateTime_CST, 
                                                        unit = "hours")),
                       Mean.Discharge_m3s = mean(Discharge_m3s),
                       Mean.Nitrate_mgL = mean(Nitrate_mgL))
    
    # Count number of days since start
    avg_df$day <- numeric(nrow(avg_df))
    
    for (i in 1:nrow(avg_df)){
      avg_df$day[i] <- 
        as.numeric(avg_df$date[i] - avg_df$date[1])
    }
    
    # Find maximum nitrate concentration each (local time) day
    avg_df <- 
      avg_df %>%
      dplyr::group_by(date) %>%
      dplyr::mutate(MaxNitrate = max(Mean.Nitrate_mgL))
    
    # Use a static value for river bed area (m^2)
    # Average discharge at desoto = 61.3 m3/s
    # USGS field measuremnents
    # 2018-03-01    Q = 1410 ft3/s      Channel area = 811 ft2
    #                 = 39.93 m3/s                   = 75.34 m2
    # 2018-04-24    Q = 2330 ft3/s      Channel area = 1400 ft2
    #                 = 65.97 m3/s                   = 130.06 m2
    # Approximate river bed area as 130 m2 (for now)
    A_m2 <- 130
    
    # Calculate water velocity [m/s]
    avg_df$v_ms <- avg_df$Mean.Discharge_m3s / A_m2
    
    # Calculate difference betweeen preceeding day's NitrateMax and Nitrate at 
    # time t
    avg_df$DiffNitrate <- numeric(nrow(avg_df))
    
    # Grab the row number of the start of day 1
    start <- which(avg_df$day == 1)[1]
    
    # Loop from day 1 to end
    for(i in start:nrow(avg_df)){
      # Get previous day: current day - 1
      prevday <- avg_df$day[i] - 1
      # Get MaxNitrate during prevday
      MaxNitrate.prev <- unique(avg_df$MaxNitrate[avg_df$day == prevday])
      # Get current Nitrate
      Nitrate <- avg_df$Mean.Nitrate_mgL[i]
      # Calculate absolute value of difference
      avg_df$DiffNitrate[i] <- MaxNitrate.prev - Nitrate
      # Iterate loop
      i <- i + 1
    }
    
    # Sum the differences from t = 0 to t = 24 for each day
    avg_df <- avg_df %>%
      group_by(day) %>%
      mutate(SumDiffNitrate_mgL = sum(DiffNitrate))
    
    # Multiply SumDiff and velocity, and correct for units
    # Q [m3/s] / A [m2] = v [m/s]
    # v [m/s] * [NO3] [mg-N/L] = U [m*mg-N / s*L]
    # U [m*mg-N / s*L] * [1000 L / 1 m3] * 86400 [s / day] = U [mg-N / m2*day]
    avg_df$UaNO3_mgNm2day <- 
      avg_df$SumDiffNitrate_mgL * avg_df$v_ms * 1000 * 86400
    
    # I don't know if this calculation is totally correct. The numbers seem
    # super high.
    #
    # Rename columns
    names(avg_df)[names(avg_df) == "MaxNitrate"] <- "DailyMaxNitrate_mgNL"
    names(avg_df)[names(avg_df) == "v_ms"] <- "Velocity_ms"
    names(avg_df)[names(avg_df) == "DiffNitrate"] <- "DiffNitrate_mgNL"
    avg_df$date <- NULL
    avg_df$hour <- NULL
    avg_df$day <- NULL
    # Return dataframe
    return(avg_df)
  }
  
  # Execute function
  eric_uptake_Eqn1 <- HC_Eqn1(eric_uptake)
  steve_uptake_Eqn1 <- HC_Eqn1(steve_uptake)
  desoto_uptake_Eqn1 <- HC_Eqn1(desoto_uptake)
  
  # Merge calculations into a single dataframe and save to CSV file
  Uptake_Eqn1 <- dplyr::full_join(eric_uptake_Eqn1, steve_uptake_Eqn1, 
                                  by = "DateTime_CST", 
                                  suffix = c(".eric", ".steve"))
  
  Uptake_Eqn1 <- dplyr::full_join(Uptake_Eqn1, desoto_uptake_Eqn1, 
                                  by = "DateTime_CST")
  
  # Cleanup
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "Mean.Discharge_m3s"] <- 
    "Mean.Discharge_m3s.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "Mean.Nitrate_mgL"] <- 
    "Mean.Nitrate_mgL.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "DailyMaxNitrate_mgNL"] <- 
    "DailyMaxNitrate_mgNL.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "Velocity_ms"] <- 
    "Velocity_ms.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "DiffNitrate_mgNL"] <- 
    "DiffNitrate_mgNL.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "SumDiffNitrate_mgL"] <- 
    "SumDiffNitrate_mgNL.desoto"
  names(Uptake_Eqn1)[names(Uptake_Eqn1) == "UaNO3_mgNm2day"] <- 
    "UaNO3_mgNm2day.desoto"
  
  # Add column to denote during waste release or after
  # During: dates prior to 1 April 2018
  # After: dates post 1 April 2018
  Uptake_Eqn1$ReleaseStatus <- "During"
  Uptake_Eqn1$ReleaseStatus[Uptake_Eqn1$DateTime_CST >= 
                              ymd_hms("2018-04-01 00:00:00", 
                                      tz = "America/Chicago")] <- "After"
  
  # Save dataframe
  write.csv(Uptake_Eqn1, file = "./Outputs/NitrateUptakeResults_Eqn1.csv", 
            row.names = FALSE)
  
}

#### Calculate uptake using Equation 2 #########################################

if (UptakeEqn == 2){
  # Calculate NO3 uptake using the integrated diel method 
  # (Heffernan and Cohen 2010, Eqn. 2)
  
  # Differences between Eqn. 1 and 2:
  #   - Eqn 2 takes an hourly average of obervations (less
  #     sensitive to variations in Nitrate)
  
  # Input: the dataframe spit out by prepper()
  # Output: Calculated NO3 Uptake
  
  HC_Eqn2 <- function(prepped_df){
    #
    # Take an hourly average Nitrate concentration
    prepped_df <- 
      prepped_df %>%
      dplyr::group_by(DateTime_CST = 
                        lubridate::floor_date(DateTime_CST, unit = "hour")) %>%
      dplyr::summarise(Mean.Discharge_m3s = mean(Discharge_m3s, na.rm = TRUE),
                       Mean.Nitrate_mgL = mean(Nitrate_mgL, na.rm = TRUE))
    #
    # Add date index vector
    # (Based on CST local time)
    # Extract date into new column
    prepped_df$date <- 
      lubridate::date(prepped_df$DateTime_CST)
    # Count number of days since start
    prepped_df$day <- numeric(length = nrow(prepped_df))
    for (i in 1:nrow(prepped_df)){
      prepped_df$day[i] <- 
        as.numeric(prepped_df$date[i] - prepped_df$date[1])
    }
    # Get hour of day, as fraction of 24
    prepped_df$hour <- lubridate::hour(prepped_df$DateTime_CST) / 24
    #
    # Find maximum nitrate concentration each 
    # (local time) day
    prepped_df <- prepped_df %>%
      dplyr::group_by(date) %>%
      dplyr::mutate(MaxNitrate = max(Mean.Nitrate_mgL, na.rm = TRUE))
    #
    # Use a static value for river bed area (m^2)
    # Average discharge at desoto = 61.3 m3/s
    # USGS field measuremnents
    # 2018-03-01    Q = 1410 ft3/s      Channel area = 811 ft2
    #                 = 39.93 m3/s                   = 75.34 m2
    # 2018-04-24    Q = 2330 ft3/s      Channel area = 1400 ft2
    #                 = 65.97 m3/s                   = 130.06 m2
    # Approximate river bed area as 130 m2 (for now)
    A_m2 <- 130
    #
    # Calculate water velocity [m/s]
    prepped_df$v_ms <- prepped_df$Mean.Discharge_m3s/A_m2
    # 
    # Run loop to calculate uptake
    prepped_df$DiffNitrate_mgL <- NA
    # Grab the row number of the start of day 1
    start <- which(prepped_df$day == 1)[1]
    for (i in start:nrow(prepped_df)){
      # Get previous day: current day - 1
      prevday <- prepped_df$day[i] - 1
      # Get MaxNitrate during prevday
      MaxNitrate.prev <- unique(prepped_df$MaxNitrate[prepped_df$day == 
                                                        prevday])
      # Get MaxNitrate during current day
      MaxNitrate <- unique(prepped_df$MaxNitrate[prepped_df$day == 
                                                   prepped_df$day[i]])
      # Get Nitrate at current hour
      Nitrate <- prepped_df$Mean.Nitrate_mgL[i]
      # Calculate DiffNitrate for each hour
      prepped_df$DiffNitrate_mgL[i] <- MaxNitrate.prev * 
                                             (1 - prepped_df$hour[i]) + 
                                             MaxNitrate * prepped_df$hour[i] - 
                                             Nitrate
    }
    #
    # Sum the differences from t = 0 to t = 24 for each day
    results <- prepped_df %>%
      dplyr::group_by(day) %>%
      dplyr::summarise(date = date[1],
                       Mean.Discharge_m3s = mean(Mean.Discharge_m3s, 
                                                 na.rm = TRUE),
                       Mean.Nitrate_mgL = mean(Mean.Nitrate_mgL, na.rm = TRUE),
                       Mean.v_ms = mean(v_ms, na.rm = TRUE), 
                       SumDiffNitrate = sum(DiffNitrate_mgL))
    # Multiply SumDiff by velocity
    # Unit check:
    # [mg / L] * [m / s] = [mg*m / L*s]
    # [mg*m / L*s] * 1000 [L / m3] * 86400 [s / day] * 1 [g] / 1000 [mg]
    results$UaNO3_gNm2day <- 
      results$SumDiffNitrate * results$Mean.v_ms * 86400
    #
    # Clean up dataframe
    names(results)[names(results) == "date"] <- "Date"
    names(results)[names(results) == "Mean.v_ms"] <- "Mean.velocity_ms"
    results$SumDiffNitrate <- NULL
    results$day <- NULL
    # Return dataframe
    return(results)
  }

  # Execute function
  eric_uptake_Eqn2_smooth <- HC_Eqn2(eric_smooth)
  eric_uptake_Eqn2 <- HC_Eqn2(eric_uptake)
  steve_uptake_Eqn2 <- HC_Eqn2(steve_uptake)
  desoto_uptake_Eqn2 <- HC_Eqn2(desoto_uptake)
  
  #plot(y = eric_uptake_Eqn2$UaNO3_gNm2day[eric_uptake_Eqn2$Date < ymd("2018-05-01")]/1000, 
       #x = eric_uptake_Eqn2$Date[eric_uptake_Eqn2$Date < ymd("2018-05-01")],
       #ylab = "Ua-NO3, kg-N / (m^2 day)", xlab = "DateTime",
       #main = "Uptake at Eric, using original data")
  #plot(y = eric_uptake_Eqn2_smooth$UaNO3_gNm2day/1000, 
       #x = eric_uptake_Eqn2_smooth$Date,
       #ylab = "Ua-NO3, kg-N / (m^2 day)", xlab = "DateTime",
       #main = "Uptake at Eric, with readings associated \nwith high Q variability removed")
  # plot(eric_uptake_Eqn2_smooth$UaNO3_gNm2day)
    
  # Merge calculations into a single dataframe and save to CSV file
  Uptake_Eqn2 <- dplyr::full_join(eric_uptake_Eqn2, steve_uptake_Eqn2, 
                                  by = "Date", 
                                  suffix = c(".eric", ".steve"))
    
  Uptake_Eqn2 <- dplyr::full_join(Uptake_Eqn2, desoto_uptake_Eqn2, 
                                  by = "Date")
  
  # Cleanup
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "Mean.Discharge_m3s"] <- 
    "Mean.Discharge_m3s.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "Mean.Nitrate_mgL"] <- 
    "Mean.Nitrate_mgL.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "DailyMaxNitrate_mgNL"] <- 
    "DailyMaxNitrate_mgNL.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "Mean.velocity_ms"] <- 
    "Mean.velocity_ms.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "DiffNitrate_mgNL"] <- 
    "DiffNitrate_mgNL.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "SumDiffNitrate_mgL"] <- 
    "SumDiffNitrate_mgNL.desoto"
  names(Uptake_Eqn2)[names(Uptake_Eqn2) == "UaNO3_gNm2day"] <- 
    "UaNO3_gNm2day.desoto"
  
  # Add column to denote during waste release or after
  # During: dates prior to 1 April 2018
  # After: dates post 1 April 2018
  Uptake_Eqn2$ReleaseStatus <- "During"
  Uptake_Eqn2$ReleaseStatus[Uptake_Eqn2$Date >= ymd("2018-04-01")] <- "After"
  
  # Save dataframe
  write.csv(Uptake_Eqn2, file = "./Outputs/NitrateUptakeResults_Eqn2.csv", 
            row.names = FALSE)
}
```



```{r Uptake Calculations}
plot(x = a_uptake$Date, y = a_uptake$UaNO3_gNm2day/1000, ylim = c(0,450))
```


```{r Calculation: Merge Uptake data with Metabolism data}
# New dataframe: metabolism results and uptake calculations

# Load in metabolism model results
modelfit.eric <- readRDS("./Outputs/MetabResults_Eric.RData")
modelfit.steve <- readRDS("./Outputs/MetabResults_Steve.RData")
modelfit.desoto <- readRDS("./Outputs/MetabResults_Desoto.RData")

# Compile metabolism results into a single dataframe
Metabolism <- dplyr::full_join(modelfit.eric$predictions, modelfit.steve$predictions,
                               by = "date", suffix = c(".eric", ".steve"))
Metabolism <- dplyr::full_join(Metabolism, modelfit.desoto$predictions, by = "date")

# Cleanup and rename columns
Metabolism$msgs.fit.eric <- NULL
Metabolism$warnings.eric <- NULL
Metabolism$errors.eric <- NULL
Metabolism$msgs.fit.steve <- NULL
Metabolism$warnings.steve <- NULL
Metabolism$errors.steve <- NULL
Metabolism$msgs.fit <- NULL
Metabolism$warnings <- NULL
Metabolism$errors <- NULL
names(Metabolism)[names(Metabolism) == "GPP"] <- "GPP.desoto"
names(Metabolism)[names(Metabolism) == "GPP.lower"] <- "GPP.lower.desoto"
names(Metabolism)[names(Metabolism) == "GPP.upper"] <- "GPP.upper.desoto"
names(Metabolism)[names(Metabolism) == "ER"] <- "ER.desoto"
names(Metabolism)[names(Metabolism) == "ER.lower"] <- "ER.lower.desoto"
names(Metabolism)[names(Metabolism) == "ER.upper"] <- "ER.upper.desoto"
names(Metabolism)[names(Metabolism) == "date"] <- "Date"

# # Join uptake dataframe with metabolism dataframes
UptakeMetab <- dplyr::full_join(NitrateUptake, Metabolism, by = "Date")
```

```{r Calculation and Plot: UAGPP}
# Calculate expected autotrophic assimilation of nitrate
# based on GPP, as in Rode et al 2016
# Assumptions:
#   net autotrophic production is half of gross primary productivity
#       (ra -> 0.5)
#   net photosynthetic quotient is 1 (that is, 1 mol O2 produced = 
#       1 mol C converted from CO2 to organic biomass)
#   conversion rate of C to N is the same as the molar C:N ratio of 
#       the periphyton in the system
#       (using Whiles and Dodds 2002 for this value, site KR3 on the 
#       Kansas River, which has C:N of about 9 during winter to spring)

ra <- 0.5 # autotrophic production efficiency factor
N.C <- 1/9 # C:N ratio in Kansas River = 9C:1N

# Equation:
# GPP [g O2 / (m^2 day)] * [1 mol O2 / 32 g O2] * [1 mol C / 1 mol O2] * 
#   [1 mol N / 9 mol C ] C:N ratio * [14 g N / 1 mol N] * 
#   0.5 efficiency factor = Ua-GPP [g N / (m^2 day)]

UptakeMetab$UaGPP_gNm2day.eric <- UptakeMetab$GPP.eric * (1/32) * N.C * 14 * ra
UptakeMetab$UaGPP_gNm2day.steve <- UptakeMetab$GPP.steve * (1/32) * N.C * 14 * ra
UptakeMetab$UaGPP_gNm2day.desoto <- UptakeMetab$GPP.desoto * (1/32) * N.C * 14 * ra

# Eric
ggplot(data = UptakeMetab, aes(x = UaNO3_gNm2day.eric, y = UaGPP_gNm2day.eric)) +
  geom_point(shape = 21, fill = "white") +
  geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
              color = "#FF0000") +
  facet_grid(.~ReleaseStatus) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", strip.background = element_blank(),
        strip.text.x = element_blank())
  
# Steve
ggplot(data = UptakeMetab, aes(x = UaNO3_gNm2day.steve, y = UaGPP_gNm2day.steve)) +
  geom_point(shape = 21, fill = "white") +
  geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
              color = "#23baaf") +
  facet_grid(.~ReleaseStatus) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", strip.background = element_blank(),
        strip.text.x = element_blank())
  
# Desoto
ggplot(data = UptakeMetab, aes(x = UaNO3_gNm2day.desoto, y = UaGPP_gNm2day.desoto)) +
  geom_point(shape = 21, fill = "white") +
  geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
              color = "#F2AD00") +
  facet_grid(.~ReleaseStatus) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r Calculation: Vf}
# Calculate assimilatory uptake velocity (Vf)
# where Vf is the average downward velocity at which 
# NO3- ions are removed from the water and is a measure
# of efficiency relative to availability (Rode et al 2016)
#
# Using Ua-NO3:
#     Ua-NO3 [kg-N / (m^2 day)] / [NO3] [mg-N / L] * [1 m3 / 1000L] * 
#         [1000 mg / 1 g] = Vfa [m2 / day]
UptakeMetab$Vf.NO3_mday.eric <- 
  UptakeMetab$UaNO3_gNm2day.eric / UptakeMetab$Mean.Nitrate_mgL.eric
UptakeMetab$Vf.NO3_mday.steve <- 
  UptakeMetab$UaNO3_gNm2day.steve / UptakeMetab$Mean.Nitrate_mgL.steve
UptakeMetab$Vf.NO3_mday.desoto <- 
  UptakeMetab$UaNO3_gNm2day.desoto / UptakeMetab$Mean.Nitrate_mgL.desoto

# Using Ua-GPP:
#     Ua-GPP [g-N / (m^2 day)] / [NO3] [mg-N / L] * [1 m3 / 1000L] * [1000 mg / g] 
#     = Vfa [m2 / day]
UptakeMetab$Vf.GPP_mday.eric <- 
  UptakeMetab$UaGPP_gNm2day.eric / UptakeMetab$Mean.Nitrate_mgL.eric
UptakeMetab$Vf.GPP_mday.steve <- 
  UptakeMetab$UaGPP_gNm2day.steve / UptakeMetab$Mean.Nitrate_mgL.steve
UptakeMetab$Vf.GPP_mday.desoto <- 
  UptakeMetab$UaGPP_gNm2day.desoto / UptakeMetab$Mean.Nitrate_mgL.desoto
```

```{r Calculation: Cleanup and NA suspicious dates}
# Cleanup for anomalies

# Change all exactly equal to 0 values to NA so they don't plot
UptakeMetab[UptakeMetab == 0] <- NA
# One row in steve has Inf value because Ua is divided by 0 value for nitrate
UptakeMetab$Vf.NO3_mday.steve[is.infinite(UptakeMetab$Vf.NO3_mday.steve)] <- NA
# Steve doesn't have nitrate data until the 10th
UptakeMetab$Mean.Nitrate_mgL.steve[UptakeMetab$Date >= ymd("2018-01-31") 
                                   & UptakeMetab$Date <= ymd("2018-02-10")] <- 
  NA
UptakeMetab$UaNO3_gNm2day.steve[UptakeMetab$Date >= ymd("2018-01-31") 
                                & UptakeMetab$Date <= ymd("2018-02-10")] <- 
  NA
UptakeMetab$Vf.NO3_mday.steve[UptakeMetab$Date >= ymd("2018-01-31") 
                              & UptakeMetab$Date <= ymd("2018-02-10")] <- 
  NA
```

```{r Calculation: Uhet}
# Calculate expected heterotrophic assimilation of nitrate (Uhet)
# based on GPP, as in Convino et al 2018
#
# ra      # Autotrophic production efficiency factor (previously defined) 
# N.C     # C:N ratio in Kansas River = 9C:1N (previously defined)
rh <- 0.2 # Heterotrophic growth efficiency factor
#
# Equation:
# ( ER [g O2 / (m^2 day)] - 0.5 efficiency factor * GPP [g O2 / (m^2 day)] )
#         * [1 mol O2 / 32 g O2] * [1 mol C / 1 mol O2]
#         * [1 mol N / 9 mol C ] C:N ratio * [14 g N / 1 mol N]
#         * 0.2 heterotrophic growth efficiency factor
#         = Uhet [g N / (m^2 day)]
-(UptakeMetab$ER.desoto - ra * UptakeMetab$GPP.desoto) * (1/32) * N.C * 14 * rh + UptakeMetab$UaGPP_gNm2day.desoto
```

```{r Calculation: NO3Supply}
# Calculate the supply of nitrate to the reach
# Supply [g-N / m2 day] = Q [m3 / s] * NO3 [mg / L] * 1/A [m2] * 86400 [2/day] 
#                         * 1000 [L/m3] * 1/1000 [g/mg]

# Until we have better data: use 130 as static riverbed area for whole reach

A <- 130

UptakeMetab$NSupply_gNm2day.eric <- 
  (UptakeMetab$Mean.Discharge_m3s.eric * UptakeMetab$Mean.Nitrate_mgL.eric * 
     86400) / A
UptakeMetab$NSupply_gNm2day.steve <- 
  (UptakeMetab$Mean.Discharge_m3s.steve * UptakeMetab$Mean.Nitrate_mgL.steve * 
     86400) / A
UptakeMetab$NSupply_gNm2day.desoto <- 
  (UptakeMetab$Mean.Discharge_m3s.desoto * UptakeMetab$Mean.Nitrate_mgL.desoto * 
     86400) / A

```

```{r Plot: nitrate uptake and nitrate supply}
# Eric
ggplot(data = UptakeMetab, aes(x = Date)) +
  geom_col(aes(y = -UaNO3_gNm2day.eric, fill = "NO3 Uptake")) +
  geom_col(aes(y = NSupply_gNm2day.eric, fill = "NO3 Supply")) +
  geom_line(aes(y = (NSupply_gNm2day.eric/-UaNO3_gNm2day.eric)*10^5)) +
  scale_y_continuous(limits = c(-3.5E6, 2E5),
                     sec.axis = sec_axis(~./10^5, name = "Supply:Uptake")) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e") +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis labels
  xlab(NULL) + 
  ylab(expression("(g-N" ~~ m^{2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), 
        legend.title = element_blank())
ggsave("./Plots/UptakevSupply_Eric.png", width = 6.75, height = 2.5, 
       units = "in")

# Steve
ggplot(data = UptakeMetab, aes(x = Date)) +
  geom_col(aes(y = -UaNO3_gNm2day.steve, fill = "NO3 Uptake")) +
  geom_col(aes(y = NSupply_gNm2day.steve, fill = "NO3 Supply")) +
  geom_line(aes(y = (NSupply_gNm2day.steve/-UaNO3_gNm2day.steve)*10^5)) +
  scale_y_continuous(limits = c(-5E5, 3E5),
                     sec.axis = sec_axis(~./10^5, name = "Supply:Uptake")) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e") +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis labels
  xlab(NULL) + 
  ylab(expression("(g-N" ~~ m^{2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), 
        legend.title = element_blank())
ggsave("./Plots/UptakevSupply_Steve.png", width = 6.75, height = 2.5, 
       units = "in")

# Desoto
ggplot(data = UptakeMetab, aes(x = Date)) +
  geom_col(aes(y = -UaNO3_gNm2day.desoto, fill = "NO3 Uptake")) +
  geom_col(aes(y = NSupply_gNm2day.desoto, fill = "NO3 Supply")) +
  geom_line(aes(y = (NSupply_gNm2day.desoto/-UaNO3_gNm2day.desoto)*10^5)) +
  scale_y_continuous(limits = c(-6E5, 2E5), 
                     sec.axis = sec_axis(~./10^5, name = "Supply:Uptake")) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e") +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis labels
  xlab(NULL) + 
  ylab(expression("(g-N" ~~ m^{2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), 
        legend.title = element_blank())
ggsave("./Plots/UptakevSupply_Desoto.png", width = 6.75, height = 2.5, 
       units = "in")
```


```{r Plot: Vf vs time}
# Plot uptake velocity vs time

ggplot(data = UptakeMetab, aes(x = Date)) +
  # Discharge (Eric)
  geom_point(aes(y = Vf.NO3_mday.eric, color = "Discharge"), shape = 21, 
             fill = "white") +
  # Downstream (Steve)
  geom_point(aes(y = Vf.NO3_mday.steve, color = "Downstream"), shape = 21, 
             fill = "white") +
  # Desoto
  geom_point(aes(y = Vf.NO3_mday.desoto, color = "Desoto"), shape = 21, 
             fill = "white") +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # Axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0, 1.5E6)) +
  scale_color_manual(values = c("Upstream" = "#000000", 
                                "Discharge" = "#FF0000", 
                                 "Downstream" = "#23baaf", 
                                "Desoto" = "#F2AD00"),
                     breaks = c("Upstream", "Discharge", 
                                "Downstream", "Desoto")) +
  # axis labels
  xlab(NULL) + 
  ylab(expression(V[f]-NO[3]^{"-"} ~~ "(m" ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), 
        legend.title = element_blank())

ggsave(file = "./Plots/Vf_time.png", width = 6.75, height = 2.5, units = "in")
```

```{r Plot: UaNO3 vs time in a single panel}
# Plotting nitrate uptake versus time, nitrate uptake 
# calculated using Heffernan and cohen 2010, Eqn. 2

ggplot(data = UptakeMetab, aes(x = Date)) +
  # Discharge (Eric)
  geom_point(aes(y = UaNO3_gNm2day.eric, color = "Discharge"), shape = 21, 
             fill = "white") +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.eric, color = "Discharge"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.eric, color = "Discharge"), 
              formula = y~x, method = "lm", se = FALSE) +
  # Downstream (Steve)
  geom_point(aes(y = UaNO3_gNm2day.steve, color = "Downstream"), shape = 21, 
             fill = "white") +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.steve, color = "Downstream"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.steve, color = "Downstream"), 
              formula = y~x, method = "lm", se = FALSE) +
  # Desoto
  geom_point(aes(y = UaNO3_gNm2day.desoto, color = "Desoto"), shape = 21, 
             fill = "white") +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.desoto, color = "Desoto"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.desoto, color = "Desoto"), 
              formula = y~x, method = "lm", se = FALSE) +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # Axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_log10(breaks = c(1E4, 1E5, 1E6, 1E7)) +
  #scale_y_continuous(limits = c(0, 1.5E6)) +
  scale_color_manual(values = c("Upstream" = "#000000", 
                                "Discharge" = "#FF0000", 
                                 "Downstream" = "#23baaf", 
                                "Desoto" = "#F2AD00"),
                     breaks = c("Upstream", "Discharge", 
                                "Downstream", "Desoto")) +
  # axis labels
  xlab(NULL) + 
  ylab(expression(Ua-NO[3]^{"-"} ~~ "(g-N" ~~ m^{2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), 
        legend.title = element_blank())

# Save plot
ggsave("./Plots/Uptake_time_singleaxis.png", width = 6.75, height = 2.5, 
       units = "in")
```

```{r Plot: UaNO3 vs time in two panels}
# Plotting nitrate uptake versus time, differing
# axis scales seperated by an axis break

# Eric
plot_eric.lm <- 
  ggplot(data = UptakeMetab, aes(x = Date)) +
  # Discharge (Eric)
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.eric, color = "Discharge"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.eric, color = "Discharge"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_point(aes(y = UaNO3_gNm2day.eric, color = "Discharge")) +
  geom_line(aes(y = UaNO3_gNm2day.eric, color = "Discharge")) +
  # Horizontal line at 1 April, pump shutoff date
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # Axis scales
  #scale_y_continuous(limits = c(-50, 6000)) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", labels = NULL) + 
  # Color scales
  scale_color_manual(values = c("Upstream" = "#000000", "Discharge" = "#FF0000", 
                                 "Downstream" = "#23baaf", "Desoto" = "#F2AD00"),
                     limits = c("Discharge", "Downstream", "Desoto"),
                     name = "Site") +
  # axis labels
  xlab(NULL) + 
  ylab(NULL) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = c(0.15, 0.72),
        legend.background = element_rect(color = "black"))

# Steve and desoto, with linear model for during and after pumping
plot_steve.desoto.lm <- 
  ggplot(data = UptakeMetab, aes(x = Date)) +
  # Downstream (Steve)
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.steve, color = "Downstream"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.steve, color = "Downstream"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_point(aes(y = UaNO3_gNm2day.steve, color = "Downstream")) +
  geom_line(aes(y = UaNO3_gNm2day.steve, color = "Downstream")) +
  # Desoto
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "During"), 
              aes(y = UaNO3_gNm2day.desoto, color = "Desoto"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_smooth(data = subset(UptakeMetab, ReleaseStatus == "After"), 
              aes(y = UaNO3_gNm2day.desoto, color = "Desoto"), 
              formula = y~x, method = "lm", se = FALSE) +
  geom_point(aes(y = UaNO3_gNm2day.desoto, color = "Desoto")) +
  geom_line(aes(y = UaNO3_gNm2day.desoto, color = "Desoto")) +
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis and color scales
  #scale_y_continuous(limits = c(-100, 500)) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_color_manual(values = c("Upstream" = "#000000", "Discharge" = "#FF0000", 
                                 "Downstream" = "#23baaf", "Desoto" = "#F2AD00"),
                     breaks = c("Upstream", "Discharge", "Downstream", "Desoto"),
                     name = "Site") +
  # axis labels
  xlab("Date") + 
  ylab(NULL) +
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none")

# Y-axis label
yaxis <- textGrob(label = expression(Ua-NO[3]^{"-"} ~~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")"),
                  rot = 90)
# Arrange plots
Plot.uptake_time <- grid.arrange(plot_eric.lm, plot_steve.desoto.lm, 
                                 left = yaxis)
# Save plot
ggsave("./Plots/Uptake_time.png", Plot.uptake_time, 
       height = 5, width = 6, units = "in")
```

```{r Plot: Uptake vs GPP in 6 tiles}
# Reshape data so you can use a facet operator
# Add a designator for site name
# Add a designator for ReleaseStatus (done)
# Order ReleaseStatus as a factor 

# Select data prior to May 1
UptakeMetab <- subset(UptakeMetab, Date <= ymd("2018-05-01"))

# Change factor levels of ReleaseStatus designation 
# so they plot in the correct order
UptakeMetab$ReleaseStatus <- factor(UptakeMetab$ReleaseStatus, 
                                    levels = c("During", "After"), ordered = T)

# GPP vs Uptake
Plot.uptake_GPP <- grid.arrange(
  # Eric
  ggplot(data = UptakeMetab, aes(x = GPP.eric, y = UaNO3_gNm2day.eric)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#FF0000") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Steve
  ggplot(data = UptakeMetab, aes(x = GPP.steve, y = UaNO3_gNm2day.steve)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#23baaf") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Desoto
  ggplot(data = UptakeMetab, aes(x = GPP.desoto, y = UaNO3_gNm2day.desoto)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#F2AD00") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  left = yaxis,
  bottom = textGrob(label = expression("GPP (g "*O[2] ~ m^{-2} ~ d^{-1} * ")"))
)
# Save plot
ggsave("./Plots/Uptake_GPP.png", Plot.uptake_GPP,
       height = 5.5, width = 4.25, units = "in")
```

```{r Plot: Uptake vs ER in 6 tiles}
# ER vs Uptake
Plot.uptake_ER <- grid.arrange(
  # Eric
  ggplot(data = UptakeMetab, aes(x = ER.eric, y = UaNO3_gNm2day.eric)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#FF0000") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Steve
  ggplot(data = UptakeMetab, aes(x = ER.steve, y = UaNO3_gNm2day.steve)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#23baaf") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Desoto
  ggplot(data = UptakeMetab, aes(x = ER.desoto, y = UaNO3_gNm2day.desoto)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#F2AD00") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  left = yaxis,
  bottom = textGrob(label = expression("ER (g "*O[2] ~ m^{-2} ~ d^{-1} * ")"))
)
# Save plot
ggsave("./Plots/Uptake_ER.png", Plot.uptake_ER,
       height = 5.5, width = 4.25, units = "in")
```

```{r Plot: UaNO3 vs NO3 and During or Post}
# Nitrate vs Uptake
Plot.uptake_Nitrate <- grid.arrange(
  # Eric
  ggplot(data = UptakeMetab, aes(x = Mean.Nitrate_mgL.eric, y = UaNO3_gNm2day.eric)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#FF0000") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Steve
  ggplot(data = UptakeMetab, aes(x = Mean.Nitrate_mgL.steve, y = UaNO3_gNm2day.steve)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#23baaf") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  # Desoto
  ggplot(data = UptakeMetab, aes(x = Mean.Nitrate_mgL.desoto, y = UaNO3_gNm2day.desoto)) +
    geom_point(shape = 21, fill = "white") +
    geom_smooth(formula = y~x, method = "lm", se = FALSE, fullrange = TRUE,
                color = "#F2AD00") +
    facet_grid(.~ReleaseStatus) +
    # axis labels
    xlab(NULL) + 
    ylab(NULL) +
    # plot theme
    theme_classic() +
    theme(panel.border = element_rect(color = "black", fill = NA),
          legend.position = "none", strip.background = element_blank(),
          strip.text.x = element_blank()),
  
  left = yaxis,
  bottom = textGrob(label = expression(NO[3]^{"-"} ~~ "(mg-N" ~ L^{-1} *")"))
)
# Save plot
ggsave("./Plots/Uptake_Nitrate.png", Plot.uptake_Nitrate,
       height = 5.5, width = 4.25, units = "in")
```

```{r Calculation: Pearson Correlations}
# Compute linear correlations between uptake and predictors

# Uptake and GPP
# During pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$GPP.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$GPP.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$GPP.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")
# After pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$GPP.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$GPP.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$GPP.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")

# Uptake and ER
# During pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$ER.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$ER.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$ER.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")
# After pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$ER.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$ER.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$ER.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")

# Uptake and NO3
# During pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$Mean.Nitrate_mgL.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$Mean.Nitrate_mgL.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "During")$Mean.Nitrate_mgL.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "During")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")
# After pumping
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$Mean.Nitrate_mgL.eric, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.eric, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$Mean.Nitrate_mgL.steve, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.steve, 
    use = "pairwise.complete.obs", method = "pearson")
cor(x = subset(UptakeMetab, ReleaseStatus == "After")$Mean.Nitrate_mgL.desoto, 
    y = subset(UptakeMetab, ReleaseStatus == "After")$UaNO3_gNm2day.desoto, 
    use = "pairwise.complete.obs", method = "pearson")
```