---
title: "Spiraling"
author: "Michelle Kelly"
date: "September 24, 2018"
output: html_document
---

```{r setup}
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r load}
# load in chloride and NH4 data
WaterChem <- read.csv("./Data/KAWN_WaterChemistry.csv")
```

```{r sort}
# lubridate date column
WaterChem$Date <- lubridate::mdy(WaterChem$Date)
# gather from wide format to long format
WaterChem <- gather(WaterChem, parameter, measurement, Chloride_mgL:NH4_mgNL)
```

```{r plot}
theme_set(theme_classic())

ggplot(data = WaterChem, aes(x = DistanceDownstream_km, color = parameter)) +
  geom_point(aes(y = measurement)) + 
  geom_smooth(aes(y = measurement), method = lm) +
  scale_y_log10() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none") +
  labs(x = "Distance from release, km", y = "Concentration, mg/L") +
  facet_grid(parameter ~ Date, scales = "free")

ggsave("./Plots/NSpiraling.png", width = 6, height = 4.5, units = "in")
```

```{r}
WaterChem <- spread(WaterChem, parameter, measurement)

WaterChem_Feb1 <- WaterChem[WaterChem$Date == ymd("2018-02-01"),]
WaterChem_Mar1 <- WaterChem[WaterChem$Date == ymd("2018-03-01"),]
WaterChem_Mar15 <- WaterChem[WaterChem$Date == ymd("2018-03-15"),]

# Feb 1 linear model
#k <- lm(formula = WaterChem_Feb1$Chloride_mgL ~ WaterChem_Feb1$DistanceDownstream_km)$coefficients[2]
k <-lm(formula = log(WaterChem_Feb1$NH4_mgNL) ~ WaterChem_Feb1$DistanceDownstream_km)$coefficients[2]
# uptake length Sw (m) = 1/k
Sw_Feb1 <- 1/k

# Mar 1
k <-lm(formula = log(WaterChem_Mar1$NH4_mgNL) ~ WaterChem_Mar1$DistanceDownstream_km)$coefficients[2]
Sw_Mar1 <- 1/k

# Mar 15
k <-lm(formula = log(WaterChem_Mar15$NH4_mgNL) ~ WaterChem_Mar15$DistanceDownstream_km)$coefficients[2]
Sw_Mar15 <- 1/k

# overall
k <- lm(formula = log(WaterChem$NH4_mgNL) ~ WaterChem$DistanceDownstream_km)$coefficients[2]
Sw <- 1/k
```