---
title: 'KAWN RAPID: Wavelet Analysis'
author: "Michelle Catherine Kelly"
date: "13 July 2018"
output:
  html_document
---

```{r setup}
### General packages ###
#library(XML)
library(lubridate)
library(ggplot2)
#library(gridExtra)
#library(grid)
library(dplyr)
#library(magrittr)
#library(zoo)
#library(wesanderson) # pallets
#library(chron)
library(data.table)
library(WaveletComp) # wavelet analysis.
library(StreamPULSE)
library(streamMetabolizer)
```

```{r data.load}
# load data files, these are the same as those on the streamPULSE server, dateTime is in UTC
eric <- read.csv(file = "./SensorData_StreamPULSE_Downloaded/KS_KANSASREASTLAWRENCE_sensorData.csv",
                 header = TRUE, stringsAsFactors = FALSE)
steve <- read.csv(file = "./SensorData_StreamPULSE_Downloaded/KS_KANSASRFALLLEAF_sensorData.csv",
                  header = TRUE, stringsAsFactors = FALSE)
desoto <- read.csv(file = "./SensorData_StreamPULSE_Downloaded/KS_KANSASR_sensorData.csv",
                   header = TRUE, stringsAsFactors = FALSE)

# simplify site names
eric$site <- "ERIC"
steve$site <- "STEVE"
desoto$site <- "DESOTO"

# remove data flagged with "Bad Data"
eric$value[eric$flagtype %in% "Bad Data"] <- NA # set values to NA for points flagged "Bad Data"
# extrapolate data for "Bad Data" points
# to do this properly I think I'll need to modify the prep_metabolism function to ensure that N data has been cleaned in the same way as metabolism data

site_code.desoto <- "KS_KANSASR" # Region_SiteName https://data.streampulse.org/sitelist
user_token <- "a1a704245e5fda8ac9b4" # unique user token for user michelleckelly

desoto_data1 <- request_data(site_code.desoto, token = user_token)
desoto_data3 <- request_data(site_code.desoto, token = user_token, variables = 'Nitrate_mgL')

desoto_data <- request_data(site_code.desoto, token = user_token)
desoto_filldata <- prep_metabolism(desoto_data, type = "streamMetabolizer", 
                                   model = "bayes", rm_flagged = "Bad Data", 
                                   fillgaps = "interpolation")
```



```{r waveletComputation_April}
# start w/ DO data, that you know will have daily oscilations
# dt = 4 observations each hour with one time unit = one day

### Basic wavelet analysis ###
# April 2018
# [DO]
desoto.w.apr.DO <- 
analyze.wavelet(desoto.w.data.apr, my.series = "DO", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")
# DO % sat
desoto.w.apr.DOsat <- 
analyze.wavelet(desoto.w.data.apr, my.series = "DO.sat", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")
# [nitrateNitrite]
desoto.w.apr.N <- 
analyze.wavelet(desoto.w.data.apr, my.series = "nitrateNitrite", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")

### Cross wavelet power ###
# April 2018
# [nitrateNitrite] and [DO]
coher.apr.N.DO <- 
analyze.coherency(desoto.w.data.apr, my.pair = c(2,4), dt = 1/4, 
                  lowerPeriod = 6, upperPeriod = 60,
                  date.format = "%Y-%m-%d %H:%M:%S")
# [nitrateNitrite] and DO % sat
coher.apr.N.DOsat <- 
analyze.coherency(desoto.w.data.apr, my.pair = c(3,4), dt = 1/4, 
                  lowerPeriod = 6, upperPeriod = 60,
                  date.format = "%Y-%m-%d %H:%M:%S")
```

```{r waveletVisualizations_April}
### Basic wavelet analysis ###
# April 2018
# [DO]
wt.image(desoto.w.apr.DO, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: DO, April",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")
# DO % sat
wt.image(desoto.w.apr.DOsat, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: DO % saturation, April",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")
# nitrateNitrite
wt.image(desoto.w.apr.N, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: [NOx], April",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")

### Cross wavelet power ###
# April 2018
# setup hourly labels
at.pi <- seq(-pi, pi, by = pi/2)
labels.pi <- seq(-12, 12, by = 1)
# [nitrateNitrite] and [DO]
wc.avg(coher.apr.N.DO, periodlab = "Period (hours)")
wc.sel.phases(coher.apr.N.DO, main = "Cross wavelet power, April: [nitrate] and [DO]", 
              sel.period = 24,
              spec.phase.axis = list(at = at.pi, labels = labels.pi),
              show.date = TRUE, date.format = "%d-%m", timelab = "Date")
# [nitrateNitrite] and DO % sat, phase difference at period of 24 hrs
wc.avg(coher.apr.N.DOsat, periodlab = "Period (hours)")
# convert axis from pi to hrs
at.phase <- seq(-pi, pi, by = pi/6)
labels.phase <- seq(-12, 12, by = 2)
wc.sel.phases(coher.apr.N.DOsat, sel.period = 24,
              spec.phase.axis = list(at = at.phase, labels = labels.phase),
              phaselab = "phase (hours)",
              main = "Cross wavelet power, April: [nitrate] and DOsat",
              show.date = TRUE, date.format = "%d-%m", timelab = "Date")

# extracting the time series of angles at the period of 24 hrs
row.closest.to.24 <- which.min((coher.apr.N.DOsat$Period - 24)^2)
# determine angle series
angle.series <- coher.apr.N.DOsat$Angle[row.closest.to.24,]
# convert to minutes
# 2pi corresponds to 24 hrs, because period = 24
lead.time.in.minutes <- 60*(24*(angle.series/(2*pi)))
plot(lead.time.in.minutes)
wc.phasediff.image(coher.apr.N.DOsat, 
                   show.date = TRUE, date.format = "%d-%m", timelab = "Date",
                   label.period.axis = TRUE)
```

```{r waveletComputation_Full}
### Basic wavelet analysis ###
# Full time series
# [DO]
desoto.w.DO <- 
analyze.wavelet(desoto.w.data, my.series = "DO", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")
# DO % sat
desoto.w.DOsat <- 
analyze.wavelet(desoto.w.data, my.series = "DO.sat", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")
# [nitrateNitrite]
desoto.w.N <- 
analyze.wavelet(desoto.w.data, my.series = "nitrateNitrite", 
                dt = 1/4, lowerPeriod = 6, upperPeriod = 60,
                make.pval = TRUE, date.format = "%Y-%m-%d %H:%M:%S")

### Cross wavelet power ###
# Full time series
# [nitrateNitrite] and [DO]
coher.N.DO <- 
analyze.coherency(desoto.w.data, my.pair = c(2,4), dt = 1/4, 
                  lowerPeriod = 6, upperPeriod = 60,
                  date.format = "%Y-%m-%d %H:%M:%S")
# [nitrateNitrite] and DO % sat
coher.N.DOsat <- 
analyze.coherency(desoto.w.data, my.pair = c(3,4), dt = 1/4, 
                  lowerPeriod = 6, upperPeriod = 60,
                  date.format = "%Y-%m-%d %H:%M:%S")
```

```{r waveletVisualizations_Full}
### Basic wavelet analysis ###
# Full time series
# [DO]
wt.image(desoto.w.DO, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: DO, full time series",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")
# DO % sat
wt.image(desoto.w.DOsat, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: DO % saturation, full time series",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")
# nitrateNitrite
wt.image(desoto.w.N, periodlab = "Period (hours)", timelab = "Date", 
         main = "Wavelet: [NOx], April",
         label.time.axis = TRUE, show.date = TRUE, date.format = "%Y-%m-%d")

### Cross wavelet power ###
# Full time series
# [nitrateNitrite] and [DO]
wc.avg(coher.N.DO, periodlab = "Period (hours)", 
       main = "Cross wavelet power, [nitrate] and [DO]")
wc.sel.phases(coher.N.DO, main = "Cross wavelet power, [nitrate] and [DO]", 
              show.date = TRUE, date.format = "%d-%m", timelab = "Date")
# [nitrateNitrite] and DO % sat
wc.avg(coher.N.DOsat, periodlab = "Period (hours)",
       main = "Cross wavelet power, [nitrate] and DOsat")
wc.sel.phases(coher.N.DOsat, 
              main = "Cross wavelet power, [nitrate] and DOsat",
              show.date = TRUE, date.format = "%d-%m", timelab = "Date")
```

