---
title: "KAWN_Sensors_MassBalance"
author: "Michelle Kelly"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup}
library(lubridate)
library(magrittr)
library(dplyr)
library(imputeTS)
library(ggplot2)
```

1. find daily mean nitrogen concentrations
2. compute mass load of N (N concetration * discharge)

```{r Qload}
# load in discharge data

# time period: 1 Jan 18 - 15 Jun 18
# load in USGS discharge data, units are [m^3 s^-1]
discharge <- read.csv(file = "./Data/SensorData_CompiledFiles/KAWN_USGSDischarge_dailymeans.csv")

# because of the water balance exercise, desoto data is negative, change the sign
discharge$Q5.desoto <- -1 * discharge$Q5.desoto
# ditch the difference column (used in the water balance exercise)
discharge$difference <- NULL

# rename columns to be more meaningful
names(discharge) <- c("date", "Q.lawrence_m3s", "Q.wakarusa_m3s", 
                      "Q.stranger_m3s", "Q.desoto_m3s", "Q.farmland_m3s")
# make sure date is correct format
discharge$date <- lubridate::mdy(discharge$date)

# after 03-30, farmland stops pumping, change Q to 0
discharge$Q.farmland_m3s[discharge$date >= mdy("03-30-2018")] <- 0

# convert [m^3 s^-1] to [L s^-1]
m3s_Ls <- function(x){
  x*1000
}

discharge$Q.lawrence_Ls <- m3s_Ls(discharge$Q.lawrence_m3s)
discharge$Q.wakarusa_Ls <- m3s_Ls(discharge$Q.wakarusa_m3s)
discharge$Q.stranger_Ls <- m3s_Ls(discharge$Q.stranger_m3s)
discharge$Q.desoto_Ls <- m3s_Ls(discharge$Q.desoto_m3s)
discharge$Q.farmland_Ls <- m3s_Ls(discharge$Q.farmland_m3s)

discharge$Q.lawrence_m3s <- NULL
discharge$Q.wakarusa_m3s <- NULL
discharge$Q.stranger_m3s <- NULL
discharge$Q.desoto_m3s <- NULL
discharge$Q.farmland_m3s <- NULL
```

```{r Nload}
# load in and format the nitrogen data

# Farmland NO3+NO2, NH3 --------------------------------------------------
# load in data provided by city
farmland <- read.csv(file = "./Data/SensorData_CompiledFiles/FarmlandDailyReport_CityofLawrence_MCK.csv")
farmland <- data.frame(date = lubridate::mdy(farmland$Date),
                       Nitrate.farmland_mgNL = farmland$OutflowWier_Farmland001A1_NitrateNitrite_mgN.L,
                       Ammonia.farmland_mgNL = farmland$OutflowWier_Farmland001A1_Ammonia_mgN.L)

# take data from only 1-Jan onwards
farmland <- farmland[farmland$date >= lubridate::mdy("1-1-2018"),]
# linearlly interpolate missing concentration values
# the point of this is to get an estimation of concentrations on weekends
# that pumping was done but samples were not taken. On dates that no pumping
# was done, a Q = 0 will be multiplied by these concentrations and they won't
# go into the N balance
farmland$Nitrate.farmland_mgNL <- imputeTS::na.interpolation(farmland$Nitrate.farmland_mgNL)
farmland$Ammonia.farmland_mgNL <- imputeTS::na.interpolation(farmland$Ammonia.farmland_mgNL)

# Bowersock NO3+NO2 -------------------------------------------------------
bowersock <- read.csv(file = "./Data/SensorData_CompiledFiles/KAWN_SensorData_Bowersock.csv")
# take average for each day
bowersock$dateTime <- lubridate::mdy_hm(bowersock$dateTime)
bowersock <- bowersock %>%
  dplyr::group_by(date = lubridate::date(dateTime)) %>%
  dplyr::summarise(Nitrate.bowersock_mgNL = mean(nitrateNitrite, na.rm = TRUE))

# Desoto, Steve, and Eric NO3+NO2 -----------------------------------------
# load in sensor data
desoto <- read.csv(file = "./Data/SensorData_StreamPULSE_Downloaded/KS_KANSASR_sensorData.csv")
steve <- read.csv(file = "./Data/SensorData_StreamPULSE_Downloaded/KS_KANSASRFALLLEAF_sensorData.csv")
eric <- read.csv(file = "./Data/SensorData_StreamPULSE_Downloaded/KS_KANSASREASTLAWRENCE_sensorData.csv")

# summarize sensor data: take daily averages
dailyavg <- function(sensor_data){
  # if sensor data has a "bad data" flag, set value to NA
  sensor_data$value[sensor_data$flagtype %in% c("Bad Data")] <- NA
  # reshape sensor data from long format to wide format
  sensor_data <- tidyr::spread(sensor_data, key = variable, value = value)
  # reformat datetime
  sensor_data$DateTime_UTC <- lubridate::mdy_hm(sensor_data$DateTime_UTC)
  # change time zone from UTC to central
  sensor_data$dateTime <- lubridate::with_tz(sensor_data$DateTime_UTC, tzone = "America/Chicago")
  # sort data file and find daily averages
  sensor_data <- sensor_data %>%
    dplyr::group_by(date = lubridate::date(dateTime)) %>% 
    dplyr::summarise(Nitrate_mgL.mean = mean(Nitrate_mgL, na.rm = TRUE))
  return(sensor_data)
}

desoto <- dailyavg(desoto)
steve <- dailyavg(steve)
eric <- dailyavg(eric)
names(desoto)[2] <- "Nitrate.desoto_mgNL"
names(steve)[2] <- "Nitrate.steve_mgNL"
names(eric)[2] <- "Nitrate.eric_mgNL"

# Desoto, Steve, Eric, Bowersock NH3 and NH4 -------------------------------------
NH3_NH4 <- read.csv(file = "./Data/SensorData_CompiledFiles/KAWN_Float_NH3_NH4.csv")
  # for future reference: NH3_NH4 also has data for Eudora and WWTP sites

# fix date format
NH3_NH4$date <- lubridate::mdy(NH3_NH4$date)
# seperate out each site from NH3_NH4 and merge with site dataframe
desoto <- dplyr::full_join(desoto, NH3_NH4 %>% dplyr::filter(site == "Desoto"))
desoto$site <- NULL
colnames(desoto)[3] <- c("Ammonium.desoto_mgNL")

steve <- dplyr::full_join(steve, NH3_NH4 %>% dplyr::filter(site == "Steve"))
steve$site <- NULL
colnames(steve)[3] <- c("Ammonium.steve_mgNL")

eric <- dplyr::full_join(eric, NH3_NH4 %>% dplyr::filter(site == "Eric"))
eric$site <- NULL
colnames(eric)[3] <- c("Ammonium.eric_mgNL")

bowersock <- dplyr::full_join(bowersock, NH3_NH4 %>% dplyr::filter(site == "Bowersock"))
bowersock$site <- NULL
colnames(bowersock)[3] <- c("Ammonium.bowersock_mgNL")
```

```{r merge}
# merge discharge, farmland, desoto, eric, steve, bowersock
massBal <- merge(discharge, farmland, by = "date", all = TRUE)
massBal <- merge(massBal, bowersock, by = "date", all = TRUE)
massBal <- merge(massBal, desoto, by = "date", all = TRUE)
massBal <- merge(massBal, steve, by = "date", all = TRUE)
massBal <- merge(massBal, eric, by = "date", all = TRUE)

# set NA's to zero
# if NA's aren't set to zero, the division step in the
# mass load calculations won't work
#massBal[is.na(massBal)] <- 0

# mass load     m [mg s-1] = Q [L s-1] * [NO3 as N] [mg L-1]
# conversion    [kg day-1] = [mg s-1] / 1000 [g/mg] / 1000 [kg/g] 
#                                 * 60 [s/min] * 60 [min/hr] * 24 [hr/day]

# nitrate load calculations
massBal$NitrateLoad.farmland_kgNday <- 
  massBal$Q.farmland_Ls * massBal$Nitrate.farmland_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$NitrateLoad.bowersock_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Nitrate.bowersock_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$NitrateLoad.desoto_kgNday <- 
  massBal$Q.desoto_Ls * massBal$Nitrate.desoto_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$NitrateLoad.steve_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Nitrate.steve_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$NitrateLoad.eric_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Nitrate.eric_mgNL / 1000 / 1000 * 60 * 60 * 24

# ammonium load calculations
massBal$AmmoniumLoad.bowersock_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Ammonium.bowersock_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$AmmoniumLoad.desoto_kgNday <- 
  massBal$Q.desoto_Ls * massBal$Ammonium.desoto_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$AmmoniumLoad.steve_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Ammonium.steve_mgNL / 1000 / 1000 * 60 * 60 * 24
massBal$AmmoniumLoad.eric_kgNday <- 
  massBal$Q.lawrence_Ls * massBal$Ammonium.eric_mgNL / 1000 / 1000 * 60 * 60 * 24

# ammonia load calculations
massBal$AmmoniaLoad.farmland_kgNday <- 
  massBal$Q.farmland_Ls * massBal$Ammonia.farmland_mgNL / 1000 / 1000 * 60 * 60 * 24

# trunkate the data at May 1
massBal <- massBal[massBal$date <= "2018-05-01",]

# export massBal dataframe
write.csv(massBal, file = "./Outputs/NMassBalance.csv", row.names = FALSE)
```

```{r plot}
theme_set(theme_classic())

# tiny plots
# bowersock
ggplot(data = massBal, aes(x = date)) +
  geom_line(aes(y = NitrateLoad.bowersock_kgNday, col = "NO3 + NO2")) +
  geom_point(aes(y = NitrateLoad.bowersock_kgNday, col = "NO3 + NO2"), shape = 21, size = 1.5, fill = "white") +
  geom_line(data = massBal[!is.na(massBal$AmmoniumLoad.bowersock_kgNday),],
            aes(y = AmmoniumLoad.bowersock_kgNday, col = "NH4"), size = 1) +
  geom_point(aes(y = AmmoniumLoad.bowersock_kgNday, col = "NH4"), fill = "white", shape = 24, size = 2.5) +
  scale_y_continuous(limits = c(0, 5000)) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01"))) + 
  scale_color_manual(values = c("black", "red", "blue"), limits = c("NO3 + NO2", "NH4", "NH3")) +
  theme(legend.position = c(0.6,0.65), legend.title = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        legend.background = element_rect(color = "black")) +
  xlab(NULL) + ylab(expression(paste("N load (kg-N ", day^-1, ")"))) + labs(tag = "(a)")
ggsave("./Plots/NBal_bowersock.png", width = 2.5, height = 2, units = "in")
# farmland
ggplot(data = massBal, aes(x = date)) +
  geom_line(aes(y = NitrateLoad.farmland_kgNday, col = "NO3 + NO2")) +
  geom_point(aes(y = NitrateLoad.farmland_kgNday, col = "NO3 + NO2"), shape = 21, size = 1.5, fill = "white") +
  geom_line(data = massBal[!is.na(massBal$AmmoniaLoad.farmland_kgNday),],
            aes(y = AmmoniaLoad.farmland_kgNday, col = "NH3"), size = 1) +
  geom_point(aes(y = AmmoniaLoad.farmland_kgNday, col = "NH3"), shape = 22, size = 2.5, fill = "white") +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01"))) + 
  scale_y_continuous(limits = c(0, 5000)) +
  scale_color_manual(values = c("black", "blue"), limits = c("NO3 + NO2", "NH3")) +
  theme(legend.position = "none", panel.border = element_rect(color = "black", fill = NA)) +
  xlab(NULL) + ylab(expression(paste("N load (kg-N ", day^-1, ")"))) + labs(tag = "(b)")
ggsave("./Plots/NBal_farmland.png", width = 2.5, height = 2, units = "in")
# eric
ggplot(data = massBal, aes(x = date)) +
  geom_line(aes(y = NitrateLoad.eric_kgNday, col = "NO3 + NO2")) +
  geom_point(aes(y = NitrateLoad.eric_kgNday, col = "NO3 + NO2"), shape = 21, size = 1.5, fill = "white") +
  geom_line(data = massBal[!is.na(massBal$AmmoniumLoad.eric_kgNday),],
            aes(y = AmmoniumLoad.eric_kgNday, col = "NH4"), size = 1) +
  geom_point(aes(y = AmmoniumLoad.eric_kgNday, col = "NH4"), shape = 24, size = 2.5, fill = "white") +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01"))) + 
  scale_y_continuous(limits = c(0, 25000), labels = scales::scientific) +
  scale_color_manual(values = c("black", "red"), limits = c("NO3 + NO2", "NH4")) +
  theme(legend.position = "none", panel.border = element_rect(color = "black", fill = NA)) +
  xlab(NULL) + ylab(expression(paste("N load (kg-N ", day^-1, ")")))
ggsave("./Plots/NBal_eric.png", width = 2.5, height = 3, units = "in")
# steve
ggplot(data = massBal, aes(x = date)) +
  geom_line(aes(y = NitrateLoad.steve_kgNday, col = "NO3 + NO2")) +
  geom_point(aes(y = NitrateLoad.steve_kgNday, col = "NO3 + NO2"), shape = 21, size = 1.5, fill = "white") +
  geom_line(data = massBal[!is.na(massBal$AmmoniumLoad.steve_kgNday),],
            aes(y = AmmoniumLoad.steve_kgNday, col = "NH4"), size = 1) +
  geom_point(aes(y = AmmoniumLoad.steve_kgNday, col = "NH4"), shape = 24, size = 2.5, fill = "white") +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01"))) + 
  scale_y_continuous(limits = c(0, 25000), labels = NULL) +
  scale_color_manual(values = c("black", "red"), limits = c("NO3 + NO2", "NH4")) +
  theme(legend.position = "none", panel.border = element_rect(color = "black", fill = NA)) +
  xlab(NULL) + ylab(NULL)
ggsave("./Plots/NBal_steve.png", width = 1.75, height = 3, units = "in")
# desoto
ggplot(data = massBal, aes(x = date)) +
  geom_line(aes(y = NitrateLoad.desoto_kgNday, col = "NO3 + NO2")) +
  geom_point(aes(y = NitrateLoad.desoto_kgNday, col = "NO3 + NO2"), shape = 21, size = 1.5, fill = "white") +
  geom_line(data = massBal[!is.na(massBal$AmmoniumLoad.desoto_kgNday),],
            aes(y = AmmoniumLoad.desoto_kgNday, col = "NH4"), size = 1) +
  geom_point(aes(y = AmmoniumLoad.desoto_kgNday, col = "NH4"), shape = 24, size = 2.5, fill = "white") +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01"))) + 
  scale_y_continuous(limits = c(0, 25000), labels = NULL) +
  scale_color_manual(values = c("black", "red", "blue"), limits = c("NO3 + NO2", "NH4", "NH3")) +
  theme(legend.position = c(0.6,0.8), legend.title = element_blank(), 
        legend.background = element_rect(color = "black"),
        panel.border = element_rect(color = "black", fill = NA)) +
  xlab(NULL) + ylab(NULL)
ggsave("./Plots/NBal_desoto.png", width = 1.75, height = 3, units = "in")


#####################
ggplot(data = massCalcs, aes(x = date, y = farmland_kgNday)) +
  geom_line() +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab(NULL) + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))
ggplot(data = massCalcs, aes(x = date, y = eric_kgNday)) +
  geom_line() +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab(NULL) + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))
ggplot(data = massCalcs, aes(x = date, y = steve_kgNday)) +
  geom_line() +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab(NULL) + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))
ggplot(data = massCalcs, aes(x = date, y = desoto_kgNday)) +
  geom_line() +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab(NULL) + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))





# subset just the calculated mass loads
massCalcs <- data.frame(date = massBal$date,
                        bowersock_kgNday = massBal$NitrateLoad.bowersock_kgNday,
                        farmland_kgNday = massBal$NitrateLoad.farmland_kgNday,
                        eric_kgNday = massBal$NitrateLoad.eric_kgNday,
                        steve_kgNday = massBal$NitrateLoad.steve_kgNday,
                        desoto_kgNday = massBal$NitrateLoad.desoto_kgNday)

# make a "calculated load" for erics
massCalcs$bowersock.add.farmland <- massCalcs$bowersock_kgNday + massCalcs$farmland_kgNday

# plotting measured load at desoto, measured load at steve, 
# and calculated load at eric's (bowersock load + farmland load)
ggplot(data = massCalcs, aes(x = date)) +
  geom_area(aes(y = desoto_kgNday, fill = "desoto measured"), col = "black") +
  geom_area(aes(y = steve_kgNday, fill = "steve measured"), col = "blue") +
  geom_area(aes(y = bowersock.add.farmland, fill = "eric calculated"), col = "red") +
  scale_fill_manual(name = NULL, values = alpha(c("white", "red", "blue"), 0.5)) +
  theme(legend.position = c(0.15,0.85)) +
  guides(fill = guide_legend(override.aes = list(alpha = 0.5))) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab("Date") + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))

ggplot(data = massCalcs, aes(x = date)) +
  geom_area(aes(y = desoto_kgNday, fill = "desoto measured"), col = "black") +
  geom_area(aes(y = steve_kgNday, fill = "steve measured"), col = "blue") +
  geom_area(aes(y = bowersock.add.farmland, fill = "eric calculated"), col = "red") +
  geom_area(aes(y = eric_kgNday, fill = "eric measured"), col = "green") +
  scale_fill_manual(name = NULL, values = alpha(c("white", "red", "green","blue"), 0.5)) +
  theme(legend.position = c(0.15,0.85)) +
  guides(fill = guide_legend(override.aes = list(alpha = 0.5))) +
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-30"))) +
  xlab("Date") + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")")))




# plot the data
ggplot(data = massBal) +
  geom_line(aes(x = date, y = NitrateLoad.bowersock_kgNday, col = "Bower"), size = 1.2) +
  geom_line(aes(x = date, y = NitrateLoad.desoto_kgNday, col = "Desoto"), size = 1.2) +
  geom_line(aes(x = date, y = NitrateLoad.farmland_kgNday, col = "Farmland"), size = 1.2) +
  geom_line(aes(x = date, y = NitrateLoad.eric_kgNday, col = "Eric"), size = 1.2) +
  geom_line(aes(x = date, y = NitrateLoad.steve_kgNday, col = "Steve"), size = 1.2) +
  xlab("Date") + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")"))) +
  theme(panel.border = element_rect(color = "black", fill = NA))

ggplot(data = massBal) +
  geom_area(aes(x = date, y = NitrateLoad.desoto_kgNday, fill = "Desoto"), 
            alpha = 0.8, col = "black", size = 1) +
  geom_area(aes(x = date, y = NitrateLoad.bowersock_kgNday, fill = "Bowersock"), 
            alpha = 0.8, col = "black", size = 1) +
  geom_area(aes(x = date, y = NitrateLoad.farmland_kgNday, fill = "Farmland"), 
            alpha = 0.8, col = "black", size = 1) +
  xlab("Date") + ylab(expression(paste("Nitrate load (kg-N ", day^-1, ")"))) +
  theme(panel.border = element_rect(color = "black", fill = NA))
```

```{r}
# load in USGS nutrient csv and reformat, rename parameter codes with parameter names
# change from long format to wide format
# keep only N data
# save as csv and commit

# examine float data
# 

```
