---
title: 'KAWN: Metabolism Calculations'
author: "Michelle Catherine Kelly"
date: "3 June 2018"
output:
  html_notebook
---

```{r setup, echo = FALSE, warning=FALSE, error=FALSE, message=FALSE}
### Global options ###
knitr::opts_chunk$set(#fig.height = 8, 
                      #fig.width = 10, 
                      cache=TRUE) # enable caching globally

### General packages ###
library(XML)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(grid)
library(dplyr)
library(magrittr)
library(zoo)
library(wesanderson) # pallets
library(chron)
library(data.table)

### USGS loading ###
library(dataRetrieval)

### NEON loading ###
# library(devtools)
# install_github("NEONScience/NEON-utilities/neonUtilities", dependencies = TRUE)
library(neonUtilities)

### Stream metabolism ###
# install.packages("streamMetabolizer", dependencies = TRUE, repos = c("https://owi.usgs.gov/R", "https://cran.rstudio.com"))
library(streamMetabolizer)
library(rstan)
# install.packages("installr")
# library("installr")
# install.Rtools()

# check if Rtools is installed properly, output should be 4
# install.packages("Rcpp")
# library(Rcpp)
# Rcpp::evalCpp("2+2")

### wavelet analysis ###
library(WaveletComp)
```

```{r data-load, child = 'KAWN_Sensors_DataLoading.Rmd'}
```



## DO, Temp, N Plots  

Function setup for individual, simple plots for each site  
```{r simplePlotFunction, include=FALSE}
# Function name:
      # simplePlot
# Function description:
      # function to output a simple plot from specified input variables
# Input variable definitions:
      # dataset = the time series dataset from which the plot will be generated, dataframe
      # xAxis = variable to be plotted on the x axis, POSIXct format
      # yAxis = variable to be plotted on the y axis, numeric
      # plotBegin = date that plot should start, POSIXct format
      # plotEnd = date that plot should end, POSIXct format
      # yMin = minimum value of y axis, numeric
      # yMax = maximum value of y axis, numeric
      # yLabel = desired label of y axis, character string
      # xLabel = desired label of x axis, character string
      # title = desired title of plot, character string
# Outputs:
      # time series plot

simplePlot <- function(dataset, xAxis, yAxis, plotBegin, plotEnd, yMin, yMax, xLabel, yLabel, title){
  ggplot(NULL) + 
    geom_point(data = dataset, aes(x = xAxis, y = yAxis, color = title), 
               show.legend = FALSE, size = 1) +
    coord_cartesian(xlim = c(plotBegin, plotEnd), 
                    ylim = c(yMin, yMax)) +
    labs(y = yLabel, x = xLabel, title = title) +
    theme_classic()
}
```

```{r DO_N_temp_Plots, echo=FALSE, warning=FALSE, eval=FALSE}
colorBlindPalette <- c("blue2", "red", "darkorchid1", "black")

# bowersock
bowersockPlot_N <- simplePlot(dataset = bowersock_N, 
                              xAxis = bowersock_N$`Date and time`, 
                              yAxis = bowersock_N$`Nitrate plus nitrite as mg-N/L`,
                              plotBegin = pullBegin, plotEnd = pullEnd, xLabel = "Date",
                              yMin = 0, yMax = 1.5, 
                              yLabel = "Nitrate plus nitrite [mg-N/L]",
                              title = "Upstream") +
  scale_color_manual(values=colorBlindPalette[1])

bowersockPlot_N

# Eric
ericPlot_N <- simplePlot(dataset = eric_N, 
                         xAxis = eric_N$`Date and time`,
                         yAxis = eric_N$`Nitrate plus nitrite as mg-N/L`,
                         plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                         yMin = 0, yMax = 20, yLabel = "Nitrate plus nitrite [mg-N/L]",
                         title = "Discharge point") +
  scale_color_manual(values=colorBlindPalette[2])

ericPlot_DO <- simplePlot(dataset = eric_DO, 
                         xAxis = eric_DO$time_CST,
                         yAxis = eric_DO$DO_mgL,
                         plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                         yMin = 0, yMax = 20, yLabel = "Dissolved oxygen [mg/L]",
                         title = "Discharge point") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[2])

ericPlot_temp <- simplePlot(dataset = eric_DO, 
                         xAxis = eric_DO$time_CST,
                         yAxis = eric_DO$temp_C,
                         plotBegin = pullBegin, plotEnd = pullEnd, xLabel = "Date",
                         yMin = -5, yMax = 25, yLabel = "Temperature [C]",
                         title = "Discharge point") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[3])

grid.arrange(ericPlot_N, ericPlot_DO, ericPlot_temp, ncol = 1, nrow = 3)

# Steve (downstream)
stevePlot_N <- simplePlot(dataset = steve_N, 
                          xAxis = steve_N$`Date and time`,
                          yAxis = steve_N$`Nitrate plus nitrite as mg-N/L`,
                          plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                          yMin = 0, yMax = 1.5, yLabel = "Nitrate plus nitrite [mg-N/L]",
                          title = "Downstream (5 km)") + 
  scale_color_manual(values=colorBlindPalette[3])

stevePlot_DO <- simplePlot(dataset = steve_DO, 
                         xAxis = steve_DO$time_CST,
                         yAxis = steve_DO$DO_mgL,
                         plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                         yMin = 0, yMax = 20, yLabel = "Dissolved oxygen [mg/L]",
                         title = "Downstream (5 km)") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[2])

stevePlot_temp <- ericPlot_temp <- simplePlot(dataset = steve_DO, 
                         xAxis = steve_DO$time_CST,
                         yAxis = steve_DO$temp_C,
                         plotBegin = pullBegin, plotEnd = pullEnd, xLabel = "Date",
                         yMin = -5, yMax = 25, yLabel = "Temperature [C]",
                         title = "Downstream (5 km)") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[3])

grid.arrange(stevePlot_N, stevePlot_DO, stevePlot_temp, ncol = 1, nrow = 3)

# Desoto
desotoPlot_N <- simplePlot(dataset = desoto, 
                           xAxis = desoto$dateTime,
                           yAxis = desoto$nitrateNitrite,
                           plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                           yMin = 0, yMax = 1.5, yLabel = "Nitrate plus nitrite [mg-N/L]",
                           title = "Far downstream (30 km)") +
  scale_color_manual(values=colorBlindPalette[4])

desotoPlot_DO <- simplePlot(dataset = desoto, 
                           xAxis = desoto$dateTime,
                           yAxis = desoto$DO_Inst,
                           plotBegin = pullBegin, plotEnd = pullEnd, xLabel = NULL,
                           yMin = 0, yMax = 20, yLabel = "Dissolved oxygen [mg/L]",
                           title = "Far downstream (30 km)") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[2])

desotoPlot_temp <- simplePlot(dataset = desoto, 
                              xAxis = desoto$dateTime,
                              yAxis = desoto$Wtemp_Inst,
                              plotBegin = pullBegin, plotEnd = pullEnd, xLabel = "Date",
                              yMin = -5, yMax = 25, yLabel = "Temperature [C]",
                              title = "Far downstream (30 km)") +
  theme(plot.title = element_blank()) +
  scale_color_manual(values=wes_palette(n=3, name="Darjeeling")[3])

grid.arrange(desotoPlot_N, desotoPlot_DO, desotoPlot_temp, ncol = 1, nrow = 3)
```

***  

# Metabolism modeling

```{r StreamMetabolizer, eval=FALSE}
# round datetime_solar
#desoto$dateTime_solar <- round_date(desoto$dateTime_solar, "10 minutes")

# estimate stream depth from discharge data
  # using d = c*Q^f Leopold and Maddock 1953
  # default values for c and f as suggested in Raymond et al 2012
      # c = 0.409 m, f = 0.294 **verify if these are representative of Kaw
desoto$depth <- calc_depth(desoto$Flow_Inst)
  # this gives us close the the GH readings for depth

# assemble data frame of data needed for metabolism model
desoto_MetabData <- merge.data.frame(desoto, PAR, by = "dateTime")
# calculate solar time
desoto_longitude <- -94.964616
desoto_MetabData$dateTime_solar <- calc_solar_time(desoto_MetabData$dateTime, 
                                                   longitude = desoto_longitude)
# cleanup data frame 
desoto_MetabData <- 
data.frame(solar.time = desoto_MetabData$dateTime_solar,
           temp.water = desoto_MetabData$Wtemp_Inst,
           discharge = desoto_MetabData$Flow_Inst,
           DO.obs = desoto_MetabData$DO_Inst,
           DO.sat = desoto_MetabData$DO_percentsat,
           depth = desoto_MetabData$depth,
           light = desoto_MetabData$mean)

# model fitting
    # using the basic MLE model
mle_name <- mm_name(type='mle', ode_method = "trapezoid")
mle_specs <- specs(mle_name)
mle_specs <- revise(mle_specs, day_start = 4, day_end = 28, required_timestep = NA,
                    split_dates = TRUE, verbose = TRUE)
mm_mle_desoto <- metab(mle_specs, data = desoto_MetabData)

# model plotting
plot_metab_preds(mm_mle_desoto)
plot_DO_preds(mm_mle_desoto)
# still having gapping between dates

# view errors
get_params(mm_mle_desoto) %>% select(date, warnings, errors)

# trying a bayseian model for better prediction of multi-day metabolism
bayes_name <- mm_name(type = "bayes", pool_K600 = "binned")
bayes_specs <- specs(bayes_name) 
bayes_specs <- revise(bayes_specs, burnin_steps=500, saved_steps=500,
                      split_dates = FALSE, verbose = TRUE, GPP_fun = "limlight",
                      ER_fun = "q10temp", deficit_src = "DO_obs", ode_method = "trapezoid",
                      control = list(max_treedepth = 30))
mm_bayes_desoto <- metab_bayes(specs = bayes_specs, data = desoto_MetabData)
mm_bayes_desoto_stanobj <- get_mcmc(mm_bayes_desoto)

traceplot(mm_bayes_desoto_stanobj)
get_fit(mm_bayes_desoto)$warnings


get_params(mm_bayes_desoto) %>% select(date, warnings, errors)

plot_metab_preds(mm_bayes_desoto)
plot_DO_preds(mm_bayes_desoto)

# what if we estimate K first, then find GPP and ER with fixed K
kmodel_name <- mm_name(type = "Kmodel", engine = "mean")
kmodel_desoto <- metab_Kmodel(specs = kmodel_name, data = desoto_MetabData)
```

```{r MetabolismModel_HotchkissHall_Equations, eval=FALSE}
# simpler hotchkiss & hall approach, let's start with steve [supp materials from lamberti textbook]

# [2] calculate oxygen saturation at temperature (the minidot already does this)
osat<- function(temp, bp) {
	
	tstd<-log((298.15-temp) / (273.15 + temp))
	
	a0<-2.00907
	a1<-3.22014
	a2<-4.0501
	a3<-4.94457
	a4<- -0.256847
	a5<- 3.88767
	
	u<-10^(8.10765-(1750.286/(235+temp)))
	
	sato<-(exp(a0 + a1*tstd + a2*tstd^2 + a3*tstd^3 + a4*tstd^4+a5*tstd^5))*((bp-u)/(760-u))*1.42905
	sato
}

# [3] calculate barometric pressure

## Function to correct barometric pressure for altitude. From Colt (2012).
## This function gives bp in mmHg for altitude given nearby measurement of standardized barometric pressure. 
	## temp is degC 
	## alt is m
	## bpst is in inches of Hg and the sort of data you will find from U.S. weather stations.  Delete the *25.4 if you in the rest of the world where pressure is given in metric units
####function returns mm of Hg
bpcalc<- function(bpst, alt) {
  bpst*25.4*exp((-9.80665*0.0289644*alt)/(8.31447*(273.15+15)))
}

# [4] load gas exchange (K) functions

## This code estimates K600 for KO2 at a given temperature. From Wanninkhof (1992).
K600fromO2<-function (temp, KO2) {
    ((600/(1800.6 - (120.1 * temp) + (3.7818 * temp^2) - (0.047608 * temp^3)))^-0.5) * KO2
}

# [5] load river metabolism function 

# parameter names (and units)
	# oxy.mod = modeled O2 (mg/L)
	# oxy = O2 data (mg/L)
	# MET[1] = GPP = estimated daily gross primary production (g O2 m-2 d-1); + flux of O2 production
	# MET[2] = ER = estimated daily ecosystem respiration (g O2 m-2 d-1); - flux of O2 consumption 
	# MET[3] = K = estimated K600 (d-1)
	# z = estimated site depth (m)
	# Kcor = KO2 corrected for temperature, calculated from K600 (d-1)
	# bp = barometric pressure (mmHg)
	# temp = water temperature (C)
	# light = PAR data (or modlight from above light function)
	# ts = time step of O2 data from logger (10 min intervals --> units are day, so 10/1440=0.06944)

Kcor<-function (temp,K600) {
	K600/(600/(1800.6-(temp*120.1)+(3.7818*temp^2)-(0.047608*temp^3)))^-0.5
}

# Model to calculate GPP, ER and K simultaneously
  # This model is advantageous in the sense that one can estimate K from the data, 
  # but beware that it may be an overparameterized model.  

# rivermetabK is the master function that calls the MLE function (onestationmleK) and plotting function (onestationplot) below
rivermetabK<-function(o2file, z, bp, ts){
  temp<-o2file$temp
  oxy<-o2file$oxy
  light<-o2file$light

  ##This calls onestationmleK (below) to calculate metabolism by non-linear minimization. We use nlm() function in R stats package; for more information see "help(nlm)"  The first argument is the function to be minimized, the second defines the starting values.  The function that is minimized (onestationmleK, see below) always has as its first argument, a vector of parameters (MET), and second argument a vector of starting values for those parameters, p=c(3,-5, 10).

  river.mle<-nlm(onestationmleK, p=c(3,-5, 10), 
                 oxy=oxy, z=z, temp=temp, 
                 light=light, bp=bp, ts=ts)

  ##plot modeled and measaured O2 given MLE estimates of GPP, ER, and K600.  It calls a function below onestationplot()

  mle_estimates <- onestationplot(GPP = river.mle$estimate[1],
                 ER = river.mle$estimate[2],
                 oxy=oxy, z=z, temp=temp, light=light, 
                 K=river.mle$estimate[3], bp=bp, ts=ts)
  
  ##return GPP, ER, K600, and MLE values
	b <- list(GPP = river.mle$estimate[1],
	          ER = river.mle$estimate[2], 
	          K600 = river.mle$estimate[3], 
	          neglogL = river.mle$minimum[1])
	b
}

# This function returns the negative log likelihood value given O2 data and estimates of GPP, ER, and K (which is vector MET); is included in master rivermetabK function above
onestationmleK <- function(MET, temp, oxy, light, z, bp, ts) {

  oxy.mod <- numeric(length(data))
  # give starting value from oxygen data; this is the only time O2 data is used to model GPP and ER
  oxy.mod[1] <- oxy[1]

  # this is the metabolism equation as in Van de Bogert et al 2007 L&OMethods
  for (i in 2:length(oxy)) {
    oxy.mod[i] <- oxy.mod[i-1] + 
                  ((MET[1]/z) * (light[i]/sum(light))) +
                  MET[2]*ts/z + 
                  (Kcor(temp[i],MET[3])) * ts * (osat(temp[i],bp) - oxy.mod[i-1]) 
    }

  # below is MLE calculation; output is -log likelihood
  # diff in measured and modeled O2
  sqdiff <- (oxy-oxy.mod)^2

  # likelihood function
  L <- length(oxy) * (log(((sum(sqdiff)/length(oxy))^0.5)) + 
       0.5*log(6.28)) + 
       ((2*sum(sqdiff)/length(oxy))^-1) * sum(sqdiff)
	L
}

# this function plots modeled O2 and O2 data from estimates of daily GPP, ER, and K; is included in master rivermetabK function above
# Calls same metabolism equation as in mle function, but plots modeled O2 as a function of GPP, ER, and K estimates from mle
# use this to visually assess your model estimates (should be good agreement between modeled and measured O2)
onestationplot <- function(GPP, ER, oxy, z, temp, K, light, bp, ts) {

  oxy.mod<-numeric(length(oxy))
  oxy.mod[1]<-oxy[1]

  # this is the metabolism equation as in Van de Bogert et al (2007) L&OMethods
  for (i in 2:length(oxy)) { 
    oxy.mod[i] <- oxy.mod[i-1] + 
                  ((GPP/z)*(light[i]/sum(light))) +
                  ER*ts/z + 
                  (Kcor(temp[i],K)) * ts * (osat(temp[i],bp)-oxy.mod[i-1]) 
    }

  plot(seq(1:length(oxy)),
       oxy.mod, 
       type="l", xlab="Time", ylab="Dissolved oxygen  (mg/L)", 
       cex.lab=1.5, cex.axis=1.5, lwd=2)
  points(seq(1:length(oxy)), oxy)
}
```

```{r MetabolismModel_HotchkissHall_Evaluation, eval=FALSE}
# [1] load data, date and time must be in different columns
eric_metab <- 
data.frame(
  dateTime = ymd_hms(eric_DO$time_CST, tz = "America/Chicago")
)
steve_metab <- 
data.frame(
  dateTime = ymd_hms(steve_DO$time_CST, tz = "America/Chicago")
)
desoto_metab <- 
  data.frame(
  dateTime = ymd_hms(desoto$dateTime, tz = "America/Chicago")
)

# [2] calculate oxygen saturation at temperature (the minidot already does this)
eric_metab$DOmgL <- eric_DO$DO_mgL
eric_metab$temp <- eric_DO$temp_C

steve_metab$DOmgL <- steve_DO$DO_mgL
steve_metab$temp <- steve_DO$temp_C

desoto_metab$DOmgL <- desoto$DO_Inst
desoto_metab$temp <- desoto$Wtemp_Inst

# [3] calculate barometric pressure
eric_alt <- 246.89 # m
eric_pressure <- 
  data.frame(
    dateTime = BarPress$dateTime,
    mean_pressure = BarPress$mean
  )
steve_alt <- 249.02 # m
steve_pressure <- 
  data.frame(
    dateTime = BarPress$dateTime,
    mean_pressure = BarPress$mean
  )
desoto_alt <- 229.78 # m
desoto_pressure <- 
  data.frame(
    dateTime = BarPress$dateTime,
    mean_pressure = BarPress$mean
  )

# [4] load gas exchange (K) functions
eric_metab$K600 <- K600fromO2(temp = eric_metab$temp, KO2 = eric_metab$DOmgL)
steve_metab$K600 <- K600fromO2(temp = steve_metab$temp, KO2 = steve_metab$DOmgL)
desoto_metab$K600 <- K600fromO2(temp = desoto_metab$temp, KO2 = desoto_metab$DOmgL)

# [5] depth
#     using streamMetabolizer package and desoto discharge data here. this won't be entirely accurate.
# estimate stream depth from discharge data
  # using d = c*Q^f Leopold and Maddock 1953
  # default values for c and f as suggested in Raymond et al 2012
      # c = 0.409 m, f = 0.294 **verify if these are representative of Kaw
eric_depth <- 
  data.frame(
    dateTime = ymd_hms(desoto$dateTime, tz = "America/Chicago"),
    z = calc_depth(desoto$Flow_Inst)
  )
steve_depth <- 
  data.frame(
    dateTime = ymd_hms(desoto$dateTime, tz = "America/Chicago"),
    z = calc_depth(desoto$Flow_Inst)
  )
desoto_depth <- 
  data.frame(
    dateTime = ymd_hms(desoto$dateTime, tz = "America/Chicago"),
    z = calc_depth(desoto$Flow_Inst)
  )

# [6] combine metabolism data frame into one, while making sure dates match

# need to combine steve_metab with steve_pressure, steve_depth, and PAR
steve_metab$dateTime <- round_date(steve_metab$dateTime, "10 minutes") # round to nearest 10 min interval
eric_metab$dateTime <- round_date(eric_metab$dateTime, "10 minutes") 

# merge function
merge_metab <- function(metabDataframe, pressureDataframe, depthDataframe, rounddateTime){
  if (rounddateTime == TRUE){
    metabDataframe$dateTime <- round_date(metabDataframe$dateTime, "10 minutes")
  }
  metabDataframe <- 
    merge(metabDataframe,
          pressureDataframe,
          by = "dateTime")
  metabDataframe <- 
    merge(metabDataframe,
          depthDataframe,
          by = "dateTime")
  metabDataframe <- 
    merge(metabDataframe,
          PAR,
          by = "dateTime")
  metabDataframe <- 
    data.frame(dateTime = metabDataframe$dateTime,
               oxy = metabDataframe$DOmgL,
               temp = metabDataframe$temp,
               K600 = metabDataframe$K600,
               bp = metabDataframe$mean_pressure,
               z = metabDataframe$z,
               light = metabDataframe$mean)
  metabDataframe
}

eric_metab <- merge_metab(eric_metab, eric_pressure, eric_depth, TRUE)
steve_metab <- merge_metab(steve_metab, steve_pressure, steve_depth, TRUE)
desoto_metab <- merge_metab(desoto_metab, desoto_pressure, desoto_depth, FALSE)

# [7] run metabolism model
eric_metab_output <- rivermetabK(o2file = na.omit(eric_metab), 
                                  z = 0.2, 
                                  bp = mean(eric_metab$bp, na.rm = TRUE), 
                                  ts = 0.02083333)
eric_metab_output
steve_metab_output <- rivermetabK(o2file = na.omit(steve_metab), 
                                  z = 0.2, 
                                  bp = mean(steve_metab$bp, na.rm = TRUE), 
                                  ts = 0.02083333)
steve_metab_output
desoto_metab_output <- rivermetabK(o2file = na.omit(desoto_metab),
                                   z = 0.2,
                                   bp = mean(desoto_metab$bp, na.rm = TRUE),
                                   ts = 0.02083333)
desoto_metab_output

# function to subset metabolism data and run model for specific time period
metab_timeperiods <- function(metab_dataframe, startTime, endTime){
  metab_timeperiod_subsection <- metab_dataframe[metab_dataframe$dateTime 
                                                 %between% 
                                                   c(ymd_hms(startTime, tz = "America/Chicago"),
                                                     ymd_hms(endTime, tz = "America/Chicago")),]
  metab_output <- rivermetabK(o2file = metab_timeperiod_subsection,
                              z = 0.2,
                              bp = mean(metab_timeperiod_subsection$bp, na.rm = TRUE),
                              ts = 0.02083333)
  return(metab_output)
}

# eric
metabmodels_eric <- 
  list(
    feb_26 = metab_timeperiods(eric_metab, "2018-02-25 02:00:00", "2018-02-27 02:00:00"), # Feb 25-27
    mar_03 = metab_timeperiods(eric_metab, "2018-03-03 09:30:00", "2018-03-05 09:30:00"), # Mar 2-4
    mar_23 = metab_timeperiods(eric_metab, "2018-03-22 00:00:00", "2018-03-24 00:00:00"), # Mar 22-24
    mar_29 = metab_timeperiods(eric_metab, "2018-03-28 22:00:00", "2018-03-30 23:30:00"), # Mar 28-30
    apr_06 = metab_timeperiods(eric_metab, "2018-04-05 12:00:00", "2018-04-07 12:00:00"), # Apr 05-07
    apr_09 = metab_timeperiods(eric_metab, "2018-04-08 00:00:00", "2018-04-09 12:00:00"), # Apr 08-10
    apr_12 = metab_timeperiods(eric_metab, "2018-04-11 17:30:00", "2018-04-13 17:30:00"), # Apr 11-13
    apr_21 = metab_timeperiods(eric_metab, "2018-04-20 00:00:00", "2018-04-22 00:00:00"), # Apr 20-22
    apr_24 = metab_timeperiods(eric_metab, "2018-04-23 19:00:00", "2018-04-25 19:00:00") # Apr 23-25
    )
metabmodels_eric_results <- 
  data.frame(
    GPP = t(as.data.frame(lapply(metabmodels_eric, `[[`, 1))),
    ER = t(as.data.frame(lapply(metabmodels_eric, `[[`, 2)))
  )
metabmodels_eric_results$date <- strptime(row.names(metabmodels_eric_results), format = "%b_%d")
metabmodels_eric_results$date <- as.Date(metabmodels_eric_results$date)

# steve
metabmodels_steve <- 
  list(
    feb_05 = metab_timeperiods(steve_metab, "2018-02-04 00:00:00", "2018-02-06 00:00:00"), # Feb 4-6
    feb_12 = metab_timeperiods(steve_metab, "2018-02-11 00:00:00", "2018-02-13 00:00:00"), # Feb 11-13
    feb_21 = metab_timeperiods(steve_metab, "2018-02-20 00:00:00", "2018-02-22 00:00:00"), # Feb 20-22
    feb_26 = metab_timeperiods(steve_metab, "2018-02-25 02:00:00", "2018-02-27 02:00:00"), # Feb 25-27
    mar_03 = metab_timeperiods(steve_metab, "2018-03-02 09:30:00", "2018-03-04 09:30:00"), # Mar 2-4
    mar_08 = metab_timeperiods(steve_metab, "2018-03-07 17:00:00", "2018-03-09 17:00:00"), # Mar 7-9
    mar_14 = metab_timeperiods(steve_metab, "2018-03-13 09:00:00", "2018-03-15 09:00:00"), # Mar 13-15
    mar_19 = metab_timeperiods(steve_metab, "2018-03-17 09:00:00", "2018-03-19 09:00:00"), # Mar 18-20
    mar_23 = metab_timeperiods(steve_metab, "2018-03-22 00:00:00", "2018-03-24 00:00:00"), # Mar 22-24
    mar_29 = metab_timeperiods(steve_metab, "2018-03-28 12:00:00", "2018-03-30 12:00:00"), # Mar 28-30
    apr_10 = metab_timeperiods(steve_metab, "2018-04-09 13:00:00", "2018-04-10 23:30:00"), # Apr 9-10
    apr_12 = metab_timeperiods(steve_metab, "2018-04-11 17:30:00", "2018-04-13 17:30:00"), # Apr 11-13
    apr_15 = metab_timeperiods(steve_metab, "2018-04-14 00:00:00", "2018-04-16 00:00:00"), # Apr 14-16
    apr_19 = metab_timeperiods(steve_metab, "2018-04-19 00:00:00", "2018-04-19 23:30:00") # Apr 18-20
  )
metabmodels_steve_results <- 
  data.frame(
    GPP = t(as.data.frame(lapply(metabmodels_steve, `[[`, 1))),
    ER = t(as.data.frame(lapply(metabmodels_steve, `[[`, 2)))
  )
metabmodels_steve_results$date <- strptime(row.names(metabmodels_steve_results), format = "%b_%d")
metabmodels_steve_results$date <- as.Date(metabmodels_steve_results$date)

# desoto
metabmodels_desoto <- 
  list(
    Feb_05 = metab_timeperiods(desoto_metab, "2018-02-04 00:00:00", "2018-02-06 00:00:00"), # Feb 4-6
    feb_21 = metab_timeperiods(desoto_metab, "2018-02-20 00:00:00", "2018-02-22 00:00:00"), # Feb 20-22
    feb_26 = metab_timeperiods(desoto_metab, "2018-02-25 02:00:00", "2018-02-27 02:00:00"), # Feb 25-27
    mar_03 = metab_timeperiods(desoto_metab, "2018-03-02 09:30:00", "2018-03-04 09:30:00"), # Mar 2-4
    mar_08 = metab_timeperiods(desoto_metab, "2018-03-07 17:00:00", "2018-03-09 17:00:00"), # Mar 7-9
    mar_19 = metab_timeperiods(desoto_metab, "2018-03-18 09:00:00", "2018-03-20 09:00:00"), # Mar 18-20
    mar_23 = metab_timeperiods(desoto_metab, "2018-03-22 00:00:00", "2018-03-24 00:00:00"), # Mar 22-24
    mar_30 = metab_timeperiods(desoto_metab, "2018-03-30 00:00:00", "2018-03-31 00:00:00"), # Mar 30-31
    apr_02 = metab_timeperiods(desoto_metab, "2018-04-01 00:00:00", "2018-04-03 00:00:00"), # Apr 1-3
    apr_09 = metab_timeperiods(desoto_metab, "2018-04-08 12:00:00", "2018-04-09 12:00:00"), # Apr 8-9
    apr_15 = metab_timeperiods(desoto_metab, "2018-04-14 00:00:00", "2018-04-16 00:00:00"), # Apr 14-16
    apr_19 = metab_timeperiods(desoto_metab, "2018-04-18 00:00:00", "2018-04-20 00:00:00"), # Apr 18-20
    apr_23 = metab_timeperiods(desoto_metab, "2018-04-22 00:00:00", "2018-04-24 00:00:00"), # Apr 22-24
    apr_29 = metab_timeperiods(desoto_metab, "2018-04-28 00:00:00", "2018-04-30 12:00:00") # Apr 28-30
  )
metabmodels_desoto_results <- 
  data.frame(
    GPP = t(as.data.frame(lapply(metabmodels_desoto, `[[`, 1))),
    ER = t(as.data.frame(lapply(metabmodels_desoto, `[[`, 2)))
  )
metabmodels_desoto_results$date <- strptime(row.names(metabmodels_desoto_results), format = "%b_%d")
metabmodels_desoto_results$date <- as.Date(metabmodels_desoto_results$date)
```

```{r metabPlotting, fig.width=9, fig.height=3, eval=FALSE}
GPP_plot <- 
ggplot(NULL) +
  geom_point(data = metabmodels_eric_results, aes(x = date, y = GPP, color = "Site 2",
                                                  shape = "19", size = 2), show.legend = FALSE) +
  geom_point(data = metabmodels_steve_results, aes(x = date, y = GPP, color = "Site 3", 
                                                   shape = "17", size = 2), show.legend = FALSE) +
  geom_point(data = metabmodels_desoto_results, aes(x = date, y = GPP, color = "Site 4", 
                                                    shape = "15", size = 2), show.legend = FALSE) +
  theme_classic() +
  xlab(NULL) +
  ylab("GPP (g O2 m-2 d-1)") +
  coord_cartesian(y = c(0,5), x = c(mdy("02/01/2018"), mdy("05/01/2018"))) +
  ggtitle(NULL) +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 14)) +
  scale_x_date(date_breaks = "2 weeks", date_labels = "%b %d") +
  scale_color_discrete(name = "Site", breaks = c("Site 2", "Site 3", "Site 4"), 
                       labels = c("Site 2", "Site 3", "Site 4")) +
  scale_shape_discrete(name = "Site", breaks = c("Site 2", "Site 3", "Site 4"), 
                       labels = c("Site 2", "Site 3", "Site 4")) +
  scale_color_manual(breaks = c("Site 2", "Site 3", "Site 4"),
                     values = colorBlindPalette[2:4]) +
    geom_vline(xintercept = mdy("04/01/2018"))
ggsave(filename = "GPP_plot.png", plot = GPP_plot, dpi = 500, width = 9, height = 3)
GPP_plot

ER_plot <- 
ggplot(NULL) +
  geom_point(data = metabmodels_eric_results, aes(x = date, y = ER, color = "Site 2",
                                                  shape = "19", size = 2), show.legend = FALSE) +
  geom_point(data = metabmodels_steve_results, aes(x = date, y = ER, color = "Site 3", 
                                                   shape = "17", size = 2), show.legend = FALSE) +
  geom_point(data = metabmodels_desoto_results, aes(x = date, y = ER, color = "Site 4", 
                                                    shape = "15", size = 2), show.legend = FALSE) +
  theme_classic() +
  xlab(NULL) +
  ylab(NULL) +
  coord_cartesian(y = c(-2,0.5), x = c(mdy("02/01/2018"), mdy("05/01/2018"))) +
  geom_vline(xintercept = mdy("04/01/2018")) +
  ggtitle(NULL) +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 14)) +
  scale_x_date(date_breaks = "2 weeks", date_labels = "%b %d", position = "top") +
  scale_color_discrete(name = "Site", breaks = c("Site 2", "Site 3", "Site 4"), 
                       labels = c("Site 2", "Site 3", "Site 4")) +
  scale_shape_discrete(name = "Site", breaks = c("Site 2", "Site 3", "Site 4"), 
                       labels = c("Site 2", "Site 3", "Site 4")) +
  scale_color_manual(breaks = c("Site 2", "Site 3", "Site 4"),
                     values = colorBlindPalette[2:4]) 

ER_plot
ggsave(filename = "ER.png", plot = ER_plot, dpi = 500, width = 9, height = 3)

```
