---
title: "Kaw N plotting"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Written by: Michelle Catherine Kelly
License: 

This code is 

```{r Setup}
library(lubridate)
library(ggplot2)
library(dplyr)
library(ggmap) # Mapping libraries
library(maps)
library(mapdata)
library(ggpubr)
library(gridExtra)
```

```{r Load data}
# Site location data ---------------------------------------------------------
coords <- read.csv("./Data/GPScoordinates_12Nov18.csv", 
                   stringsAsFactors = FALSE)
# Rename site names
coords$SiteNickname[coords$SiteNickname == "Bowersock"] <- "S0"
coords$SiteNickname[coords$SiteNickname == "Eric"] <- "S1"
coords$SiteNickname[coords$SiteNickname == "Steve"] <- "S2"
coords$SiteNickname[coords$SiteNickname == "Desoto"] <- "S3"

# Sensor data ----------------------------------------------------------------
sensor_eric <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASREASTLAWRENCE_sensorData.csv")
sensor_steve <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASRFALLLEAF_sensorData.csv")
sensor_desoto <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASR_sensorData.csv")
# Count total percent of "Bad Data" points out of all data points
sum(sensor_eric$flagtype %in% c("Bad Data"))/nrow(sensor_eric)*100 +
  sum(sensor_steve$flagtype %in% c("Bad Data"))/nrow(sensor_steve)*100 +
  sum(sensor_desoto$flagtype %in% c("Bad Data"))/nrow(sensor_desoto)*100
# summarize sensor data: take daily averages & merge w/ metabolism
dailyavg <- function(sensor_data, avgs){
  # if sensor data has a "bad data" flag, set value to NA
  sensor_data$value[sensor_data$flagtype %in% c("Bad Data")] <- NA
  # reshape sensor data from long format to wide format
  sensor_data <- tidyr::spread(sensor_data, key = variable, value = value)
  # reformat datetime
  sensor_data$DateTime_UTC <- lubridate::ymd_hms(sensor_data$DateTime_UTC)
  # change time zone from UTC to central
  sensor_data$dateTime <- lubridate::with_tz(sensor_data$DateTime_UTC, 
                                             tzone = "America/Chicago")
  if (avgs) {
    # sort data file and find daily averages
    sensor_data <- sensor_data %>%
      dplyr::group_by(date = lubridate::date(dateTime)) %>% 
      dplyr::summarise(Nitrate_mgL = mean(Nitrate_mgL, na.rm = TRUE),
                       Discharge_m3s = mean(Discharge_m3s, na.rm = TRUE),
                       DO_mgL = mean(DO_mgL, na.rm = TRUE),
                       Light_PAR = mean(Light_PAR, na.rm = TRUE),
                       WaterTemp_C = mean(WaterTemp_C, na.rm = TRUE))
  }
  # Factorize release status
  sensor_data$ReleaseStatus <- NA
  sensor_data$ReleaseStatus[sensor_data$date < ymd("2018-04-01")] <- "During"
  sensor_data$ReleaseStatus[sensor_data$date >= ymd("2018-04-01")] <- "After"
  sensor_data$ReleaseStatus <- factor(sensor_data$ReleaseStatus, 
                                      levels = c("During", "After"))
  return(sensor_data)
}

diel_eric <- dailyavg(sensor_eric, avgs = FALSE)
diel_steve <- dailyavg(sensor_steve, avgs = FALSE)
diel_desoto <- dailyavg(sensor_desoto, avgs = FALSE)

sensor_eric <- dailyavg(sensor_eric, avgs = TRUE)
sensor_steve <- dailyavg(sensor_steve, avgs = TRUE)
sensor_desoto <- dailyavg(sensor_desoto, avgs = TRUE)



# Mass balance data ----------------------------------------------------------
massbal <- readRDS("./Outputs/NMassBalance.rds")
# bowersock load gets down to 0 which doesnt show up well on a log10 scaled 
# plot, so bump up to 20 for plotting
#massbal$NitrateLoad.bowersock_gNday[massbal$date > ymd("2018-02-26")] <- 10000
#massbal$Nitrate.bowersock_mgNL[massbal$date >= ymd("2018-02-26")] <- 0.1
#massbal$Nitrate.bowersock_mgNL[massbal$date == ymd("2018-03-31")] <- 0
# Steve nitrate sensor burial
massbal$Nitrate.steve_mgNL[massbal$date >= ymd("2018-03-10") & 
                             massbal$date <= ymd("2018-03-26")] <- NA

# Metabolism results ---------------------------------------------------------
metab_eric <- readRDS("./Outputs/MetabResults_Eric.RData")$predictions
metab_steve <- readRDS("./Outputs/MetabResults_Steve.RData")$predictions
metab_desoto <- readRDS("./Outputs/MetabResults_Desoto.RData")$predictions
names(metab_desoto)[2:10] <- paste0(names(metab_desoto)[2:10], ".desoto")
# Merge into one dataframe
metab <- dplyr::full_join(metab_eric, metab_steve, by = "date", 
                          suffix = c(".eric", ".steve")) %>%
  dplyr::full_join(., metab_desoto, by = "date")
# Join with sensor data
sensor_eric <- dplyr::full_join(sensor_eric, metab_eric, by = "date")
sensor_steve <- dplyr::full_join(sensor_steve, metab_steve, by = "date")
sensor_desoto <- dplyr::full_join(sensor_desoto, metab_desoto, by = "date")

# Edits that need to happen: taking out dates that have bad data
# For eric:
# 2018-02-20 thru 2018-02-23 sensor burial
# 2018-03-06 thru 2018-03-12 sensor burial
# 2018-04-01 thru 2018-04-04 sensor burial
# 2018-04-14 thru 2018-04-17 sensor burial
# 2018-04-25 thru 2018-04-27 sensor burial
# Steve:
# 2018-02-01 thru 2018-02-10 N sensor not yet deployed
# 2018-03-10 thru 2018-03-22 N sensor burial

# Reshape metabolism dataframe -----------------------------------------------
# Factorize release status
metab$ReleaseStatus <- NA
metab$ReleaseStatus[metab$date < ymd("2018-04-01")] <- "During"
metab$ReleaseStatus[metab$date >= ymd("2018-04-01")] <- "After"
metab$ReleaseStatus <- factor(metab$ReleaseStatus, 
                              levels = c("During", "After"))
# Adjust from wide to long format
metab.long <- tidyr::gather(metab[c(-3:-4,-6:-10, -12:-13, -15:-19, -21:-22, 
                                    -24:-28)], key = site, value = value,
                            GPP.eric:ER.desoto)
# Factorize site and change labels
metab.long$site <- factor(metab.long$site)
# Initialize column to store metab model type (GPP or ER)
metab.long$model <- metab.long$site
# Rename factor levels
levels(metab.long$model)[levels(metab.long$site)=="GPP.eric"] <- "GPP"
levels(metab.long$site)[levels(metab.long$site)=="GPP.eric"] <- "S1"
levels(metab.long$model)[levels(metab.long$site)=="GPP.steve"] <- "GPP"
levels(metab.long$site)[levels(metab.long$site)=="GPP.steve"] <- "S2"
levels(metab.long$model)[levels(metab.long$site)=="GPP.desoto"] <- "GPP"
levels(metab.long$site)[levels(metab.long$site)=="GPP.desoto"] <- "S3"
levels(metab.long$model)[levels(metab.long$site)=="ER.eric"] <- "ER"
levels(metab.long$site)[levels(metab.long$site)=="ER.eric"] <- "S1"
levels(metab.long$model)[levels(metab.long$site)=="ER.steve"] <- "ER"
levels(metab.long$site)[levels(metab.long$site)=="ER.steve"] <- "S2"
levels(metab.long$model)[levels(metab.long$site)=="ER.desoto"] <- "ER"
levels(metab.long$site)[levels(metab.long$site)=="ER.desoto"] <- "S3"
metab.long$model <- factor(metab.long$model, levels = c("GPP", "ER")) # Reorder
metab.long$site <- factor(metab.long$site, levels = c("S1", "S2", "S3"))

# Predicted uptake from metabolism results
stoich.eric <- readRDS(file = "./Outputs/StoichUptake_Eric.RData")
stoich.steve <- readRDS(file = "./Outputs/StoichUptake_Steve.RData")
stoich.desoto <- readRDS(file = "./Outputs/StoichUptake_Desoto.RData")

# Nitrate uptake results -----------------------------------------------------
# HAVE bad dates removed
uptake <- readRDS("./Outputs/NitrateUptakeResults_Eqn1.rds")
uptake$UaNO3_gNm2day.steve[uptake$Date == "2018-03-01"] <- NA # affected by 
# rapid discharge change, U calculation overestimate
uptake$UaNO3_gNm2day.steve[uptake$Date == "2018-03-09"] <- NA # affected by 
# sensor burial that started around 03-10
# Section date
uptake <- uptake[uptake$Date >= ymd("2018-02-01") & 
                   uptake$Date < ymd("2018-05-01"),]
# Set values of U below 0 (from days when SumNitrateDiff was negative, which 
# indicates that biologic activity (may have been present) but was not observed
# in a diel swing of NO3 (could have been caused by disturbance, increase in Q, etc)
uptake$UaNO3_gNm2day.eric[uptake$UaNO3_gNm2day.eric < 0] <- NA
uptake$UaNO3_gNm2day.steve[uptake$UaNO3_gNm2day.steve < 0] <- NA
uptake$UaNO3_gNm2day.desoto[uptake$UaNO3_gNm2day.desoto < 0] <- NA

# Adjust from wide to long format
uptake.long <- 
  uptake %>%
  tidyr::gather(site, UaNO3_gNm2day, UaNO3_gNm2day.eric, UaNO3_gNm2day.steve, 
         UaNO3_gNm2day.desoto) %>%
  select(Date, site, UaNO3_gNm2day)

# Rename site names
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.eric"] <- "S1"
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.steve"] <- "S2"
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.desoto"] <- "S3"
supply.long <- 
  uptake %>%
  tidyr::gather(site, Supply_gNm2day, Supply_gNm2day.eric, Supply_gNm2day.steve,
         Supply_gNm2day.desoto) %>%
  select(Date, site, Supply_gNm2day)
# Rename site names
supply.long$site[supply.long$site == "Supply_gNm2day.eric"] <- "S1"
supply.long$site[supply.long$site == "Supply_gNm2day.steve"] <- "S2"
supply.long$site[supply.long$site == "Supply_gNm2day.desoto"] <- "S3"
# Factorize site name
uptake.long$site <- factor(uptake.long$site)
supply.long$site <- factor(supply.long$site)
# Add Month column
uptake.long <- 
  uptake.long %>% 
  mutate(Month = factor(month(Date, label = TRUE, abbr = TRUE)),
         WeekGroup = factor(round_date(Date, period(week = 3))))
supply.long <- 
  supply.long %>% 
  mutate(Month = factor(month(Date, label = TRUE, abbr = TRUE)),
         WeekGroup = factor(round_date(Date, period(week = 3))))
uptake.long <- na.omit(uptake.long)

# Merge uptake data and metabolism data
metab.long$Date <- metab.long$date
uptake.metab.long <- dplyr::full_join(metab.long, uptake.long, 
                                      by = c("Date", "site"))
uptake.metab.long$date <- NULL
uptake.metab.long <- subset(uptake.metab.long, Date < ymd("2018-05-01"))

# DOC data -------------------------------------------------------------------
DOC <- read.csv("./Data/KAW_RAPID_DOC.csv", header = TRUE, 
                stringsAsFactors = FALSE)
DOC$SamplingDate <- lubridate::mdy(DOC$SamplingDate)

# Meta analysis data ---------------------------------------------------------
# Tank et al 2008 uptake meta-analysis
tank <- read.csv("./Data/Meta-analysis/Tank_2008_uptakedata.csv",
                 header = TRUE)
tank$NO3_Cb_mgNL <- tank$NO3_Cb_ugNL/1000
# Rode et al 2016
rode.hensley <- read.csv("./Data/Meta-analysis/Rode_Hensley_SensorUptake.csv")
# Hall et al 2016 metabolism meta-analysis
hall <- read.csv("./Data/Meta-analysis/Hall_2016_metabolismdata.csv", 
                 header = TRUE)
hall$q_m3s <- hall$q_Ls/1000
```

```{r Calculation: Vf}
## Calculate uptake velocity ###################################################

# vf = U [g-N / m2 day] / NO3 [mg-N / L] * 1000 [mg-N / g-N] / 1000 [m3 / L] 
#    = vf [m / day] / 1440 [day / min] * 1000 [mm/m] = vf [mm/min]
uptake$vf_mmmin.eric <- 
  uptake$UaNO3_gNm2day.eric / uptake$Mean.Nitrate_mgL.eric / 1440 * 1000
uptake$vf_mmmin.steve <- 
  uptake$UaNO3_gNm2day.steve / uptake$Mean.Nitrate_mgL.steve / 1440 * 1000
uptake$vf_mmmin.desoto <- 
  uptake$UaNO3_gNm2day.desoto / uptake$Mean.Nitrate_mgL.desoto / 1440 * 1000
# Adjust data frame structure
vf <- tidyr::gather(uptake, key = site, value = vf_mmmin, 
                    vf_mmmin.eric:vf_mmmin.desoto)
vf$site <- factor(vf$site, levels = c("vf_mmmin.eric", "vf_mmmin.steve", 
                                      "vf_mmmin.desoto"))
levels(vf$site)[levels(vf$site)=="vf_mmmin.eric"] <- "S1"
levels(vf$site)[levels(vf$site)=="vf_mmmin.steve"] <- "S2"
levels(vf$site)[levels(vf$site)=="vf_mmmin.desoto"] <- "S3"
vf <- vf[-c(2:16)]
vf <- subset(vf, Date < "2018-05-01")
vf$Month <- lubridate::month(vf$Date, label = TRUE, abbr = TRUE)
# Set values of vf below 0 (from below 0 U measurements, from days when biologic 
# activity in the diel swing can't be detected/ no measureable dip in diel swing
# of NO3, could be caused by disturbance, increase in Q, etc)
vf$vf_mmmin[vf$vf_mmmin < 0] <- NA

# Join with metabolism data
vf.metab <- dplyr::full_join(metab.long, vf, by = c("Date", "site", "ReleaseStatus"))
vf.metab$date <- NULL
```

```{r Calculation: P/R}
PR <- 
  metab.long %>%
  tidyr::spread(model, value) %>%
  group_by(site) %>%
  mutate(PR = GPP/abs(ER))
```

```{r Stats}
metab.long$Month <- lubridate::month(metab.long$Date)
# Correct date spans
metab.long <- 
  metab.long[metab.long$Date < "2018-05-01" & metab.long$Date >= "2018-02-01",]
PR <- PR[PR$date < "2018-05-01" & PR$date >= "2018-02-01",]
vf.metab <- vf.metab[vf.metab$Date < "2018-05-01" & vf.metab$Date >="2018-02-01",]
# Factorize release status
uptake.long$ReleaseStatus <- NA
uptake.long$ReleaseStatus[uptake.long$Date < ymd("2018-04-01")] <- "During"
uptake.long$ReleaseStatus[uptake.long$Date >= ymd("2018-04-01")] <- "After"
uptake.long$ReleaseStatus <- factor(uptake.long$ReleaseStatus, 
                              levels = c("During", "After"))

## Metabolism ##################################################################
# Test whether GPP was significanly different between sites using non-parametric 
# ANOVA (Kruskal-wallace test)
ggpubr::compare_means(value~site, data = subset(metab.long, model == "GPP"),
                      method = "kruskal.test") 
# Test whether GPP significantly changed through time
ggpubr::compare_means(value~Month, data = subset(metab.long, model == "GPP"),
                      group.by = c("site"), method = "kruskal.test") 
# Test ER between sites
ggpubr::compare_means(value~site, data = subset(metab.long, model == "ER"),
                      method = "kruskal.test") 
# ER through time
ggpubr::compare_means(value~Month, data = subset(metab.long, model == "ER"),
                      group.by = c("site"), method = "kruskal.test") 

#P/R difference between sites
ggpubr::compare_means(PR~site, data = PR, method = "kruskal.test")
#P/R difference within a site through time

## Uptake ######################################################################
# Test whether mean U was different between sites
ggpubr::compare_means(UaNO3_gNm2day~site, data = uptake.long, 
                      method = "kruskal.test")
# Test uptake during vs after
ggpubr::compare_means(UaNO3_gNm2day~Month, data = uptake.long, 
                      method = "kruskal.test", group.by = c("site"))
## Uptake velocity #############################################################
# Test whether mean Vf was different between sites
ggpubr::compare_means(vf_mmmin~site, data = vf, method = "kruskal.test")
# Test Vf during vs after
ggpubr::compare_means(vf_mmmin~Month, data = vf, method = "kruskal.test", group.by = c("site"))

## Uptake vs GPP & ER ##########################################################
# U
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER"))


cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP" & 
                         ReleaseStatus == "During"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP" & 
                         ReleaseStatus == "After"),
         method = c("pearson"))
# These correlations are different numbers than what's on the R plots because
# The R plots are broken down into during and after
# Also on the R plots the stats for "during" appear on top
# S1
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP" & 
                         site == "S1"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S1"),
         method = c("pearson"))
# S2
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP" & 
                         site == "S2"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S2"),
         method = c("pearson"))
# S3
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "GPP" & 
                         site == "S3"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S3"),
         method = c("pearson"))
# Vf
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "GPP"), 
         method = c("pearson"))
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "ER"), 
         method = c("pearson"))
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "GPP" & site == "S2"), 
         method = c("pearson"))
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "ER" & site == "S2"), 
         method = c("pearson"))
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "GPP" & site == "S3"), 
         method = c("pearson"))
cor.test(~vf_mmmin+value, 
         data = subset(vf.metab, model == "ER" & site == "S3"), 
         method = c("pearson"))

cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S1"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S2"),
         method = c("pearson"))
cor.test(~UaNO3_gNm2day+value, 
         data = subset(uptake.metab.long, model == "ER" & 
                         site == "S3"),
         method = c("pearson"))
```

```{r Calculation: Mean data}
### Assemble means of our data #################################################
# Set up empty data frame
means <- data.frame(Site = c("S1", "S2", "S3"),
                    Nitrate_mgL.Overall = numeric(length = 3),
                    Nitrate_mgL.During = numeric(length = 3),
                    Nitrate_mgL.After = numeric(length = 3),
                    Discharge_m3s.Overall = numeric(length = 3),
                    U_gNm2day.Overall = numeric(length = 3),
                    U_gNm2day.During = numeric(length = 3),
                    U_gNm2day.After = numeric(length = 3),
                    GPP_gO2m2day.Overall = numeric(length = 3),
                    ER_gO2m2day.Overall = numeric(length = 3))
# Ammonium
mean(massbal$Ammonium.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
mean(massbal$Ammonium.eric_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.eric_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
mean(massbal$Ammonium.steve_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.steve_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
mean(massbal$Ammonium.desoto_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.desoto_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)


# Nitrate
mean(massbal$Nitrate.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Nitrate.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)

means$Nitrate_mgL.Overall <- 
  c(mean(uptake$Mean.Nitrate_mgL.eric[uptake$Date >= "2018-02-01" & 
                                        uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.steve[uptake$Date >= "2018-02-01" & 
                                         uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.desoto[uptake$Date >= "2018-02-01" & 
                                          uptake$Date < "2018-05-01"], 
         na.rm = TRUE))
means$Nitrate_mgL.SD <- 
  c(sd(uptake$Mean.Nitrate_mgL.eric[uptake$Date >= "2018-02-01" & 
                                        uptake$Date < "2018-05-01"], 
       na.rm = TRUE),
    sd(uptake$Mean.Nitrate_mgL.steve[uptake$Date >= "2018-02-01" & 
                                         uptake$Date < "2018-05-01"], 
       na.rm = TRUE),
    sd(uptake$Mean.Nitrate_mgL.desoto[uptake$Date >= "2018-02-01" & 
                                          uptake$Date < "2018-05-01"], 
       na.rm = TRUE))
means$Nitrate_mgL.During <- 
  c(mean(uptake$Mean.Nitrate_mgL.eric[uptake$Date >= "2018-02-01" & 
                                        uptake$Date < "2018-04-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.steve[uptake$Date >= "2018-02-01" & 
                                         uptake$Date < "2018-04-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.desoto[uptake$Date >= "2018-02-01" & 
                                          uptake$Date < "2018-04-01"], 
         na.rm = TRUE))
means$Nitrate_mgL.After <- 
  c(mean(uptake$Mean.Nitrate_mgL.eric[uptake$Date >= "2018-04-01" & 
                                        uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.steve[uptake$Date >= "2018-04-01" & 
                                         uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Nitrate_mgL.desoto[uptake$Date >= "2018-04-01" & 
                                          uptake$Date < "2018-05-01"], 
         na.rm = TRUE))
# Discharge
mean(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                             massbal$date <= "2018-05-01"], na.rm = TRUE)/1000
sd(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)/1000

means$Discharge_m3s.Overall <- 
  c(mean(uptake$Mean.Discharge_m3s.eric[uptake$Date >= "2018-02-01" & 
                                        uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Discharge_m3s.steve[uptake$Date >= "2018-02-01" & 
                                         uptake$Date < "2018-05-01"], 
         na.rm = TRUE),
    mean(uptake$Mean.Discharge_m3s.desoto[uptake$Date >= "2018-02-01" & 
                                          uptake$Date < "2018-05-01"], 
         na.rm = TRUE))
means$Discharge_m3s.Overall.sd <- 
  c(sd(uptake$Mean.Discharge_m3s.eric[uptake$Date >= "2018-02-01" & 
                                        uptake$Date < "2018-05-01"], 
       na.rm = TRUE),
    sd(uptake$Mean.Discharge_m3s.steve[uptake$Date >= "2018-02-01" & 
                                         uptake$Date < "2018-05-01"], 
       na.rm = TRUE),
    sd(uptake$Mean.Discharge_m3s.desoto[uptake$Date >= "2018-02-01" & 
                                          uptake$Date < "2018-05-01"], 
       na.rm = TRUE))
# Uptake
means$U_gNm2day.Overall <- 
  c(mean(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-02-01" & 
                                   uptake$Date < "2018-05-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-02-01" & 
                                    uptake$Date < "2018-05-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-02-01" & 
                                     uptake$Date < "2018-05-01"], na.rm = TRUE))
means$U_gNm2day.Overall.sd <- 
  c(sd(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-02-01" & 
                                   uptake$Date < "2018-05-01"], na.rm = TRUE),
    sd(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-02-01" & 
                                    uptake$Date < "2018-05-01"], na.rm = TRUE),
    sd(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-02-01" & 
                                     uptake$Date < "2018-05-01"], na.rm = TRUE))
means$U_gNm2day.During <- 
  c(mean(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-02-01" & 
                                   uptake$Date < "2018-04-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-02-01" & 
                                    uptake$Date < "2018-04-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-02-01" & 
                                     uptake$Date < "2018-04-01"], na.rm = TRUE))
means$U_gNm2day.After <- 
  c(mean(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-04-01" & 
                                   uptake$Date < "2018-05-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-04-01" & 
                                    uptake$Date < "2018-05-01"], na.rm = TRUE),
    mean(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-04-01" & 
                                     uptake$Date < "2018-05-01"], na.rm = TRUE))
# Vf
means$vf_mmmin.Overall <- c(mean(vf$vf_mmmin[vf$site == "S1"], na.rm = TRUE),
                            mean(vf$vf_mmmin[vf$site == "S2"], na.rm = TRUE),
                            mean(vf$vf_mmmin[vf$site == "S3"], na.rm = TRUE))
means$vf_mmmin.Overall.sd <- c(sd(vf$vf_mmmin[vf$site == "S1"], na.rm = TRUE),
                               sd(vf$vf_mmmin[vf$site == "S2"], na.rm = TRUE),
                               sd(vf$vf_mmmin[vf$site == "S3"], na.rm = TRUE))

# GPP
means$GPP_gO2m2day.Overall <- 
  c(mean(metab$GPP.eric[metab$date >= "2018-02-01" & 
                          metab$date < "2018-05-01"], na.rm = TRUE),
    mean(metab$GPP.steve[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE),
    mean(metab$GPP.desoto[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE))
means$GPP_gO2m2day.Overall.sd <- 
  c(sd(metab$GPP.eric[metab$date >= "2018-02-01" & 
                          metab$date < "2018-05-01"], na.rm = TRUE),
    sd(metab$GPP.steve[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE),
    sd(metab$GPP.desoto[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE))
# ER
means$ER_gO2m2day.Overall <- 
  c(-mean(metab$ER.eric[metab$date >= "2018-02-01" & 
                          metab$date < "2018-05-01"], na.rm = TRUE),
    -mean(metab$ER.steve[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE),
    -mean(metab$ER.desoto[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE))
means$ER_gO2m2day.Overall.sd <- 
  c(sd(metab$ER.eric[metab$date >= "2018-02-01" & 
                          metab$date < "2018-05-01"], na.rm = TRUE),
    sd(metab$ER.steve[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE),
    sd(metab$ER.desoto[metab$date >= "2018-02-01" & 
                           metab$date < "2018-05-01"], na.rm = TRUE))
# P/R
PR %>%
  filter(date >= "2018-02-01" & date <= "2018-05-01") %>%
  arrange(date) %>%
  group_by(site) %>%
  summarise(PR.mean = mean(PR, na.rm = TRUE), PR.sd = sd(PR, na.rm = TRUE))

# Mean and standard deviation of DOC data
DOC %>%
  filter(SamplingDate >= "2018-02-01" & SamplingDate <= "2018-05-01") %>%
  arrange(SamplingDate) %>%
  group_by(Site) %>%
  filter(Site == "Dam" | Site == "Disch" | Site == "Steve" | Site == "Desoto") %>%
  summarise(mean_NPOC_mgL = mean(Result_NPOC_mg.L), sd = sd(Result_NPOC_mg.L), 
            n = length(Result_NPOC_mg.L))

# Mean water temperature
mean(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
# Feb
mean(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-03-01"], na.rm = TRUE)
# March
mean(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-03-01" & 
                            sensor_desoto$date <= "2018-04-01"], na.rm = TRUE)
# Apr
mean(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-04-01" & 
                            sensor_desoto$date <= "2018-04-30"], na.rm = TRUE)

# Q
mean(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-04-01"], na.rm = TRUE)
sd(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-04-01"], na.rm = TRUE)


mean(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-04-01" & 
                            sensor_desoto$date <= "2018-04-30"], na.rm = TRUE)
sd(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-04-01" & 
                            sensor_desoto$date <= "2018-04-30"], na.rm = TRUE)
```

```{r Fig 1. Map}
# Pull country, state, county map data
state.map <- map_data("state")
kansas.map <- subset(state.map, region == "kansas")
counties.map <- subset(map_data("county"), region == "kansas")

# Pull rivers map data:
# Data provided by Esri, National Atlas of the United States and the United 
# States Geological Survey, accessed 26-Jan-19, ArcGIS "USA Rivers and Streams" 
# dataset www.arcgis.com
load(url("https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/datasets/usa_rivers.RData"))
lines.rivers2 <- subset(lines.rivers, STATE %in% c("KS") & 
                          NAME %in% c("Kansas River", "Republican River", "Little Blue River",
                                      "Big Blue River", "West Fork Big Blue River",
                                      "North Branch West Fork Big Blue River",
                                      "Big Blue Creek", "North Fork Smoky Hill River",
                                      "Smoky Hill River", "Saline River",
                                      "Saline Branch", "North Fork Saline River",
                                      "South Fork Saline River", "Solomon River",
                                      "North Fork Solomon River", "South Fork Solomon River"))
ks_rivers <- fortify(lines.rivers2)
ks_rivers.all <- fortify(subset(lines.rivers, STATE %in% c("KS")))

unique(lines.rivers$NAME[grep("Kansas", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Blue", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Smoky", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Saline", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Solomon", lines.rivers$NAME)])

# USA map
a <- 
ggplot() +
  theme_nothing() +
  geom_polygon(data = state.map, 
               aes(x = long, y = lat, group = group), 
               color = "grey", fill = NA) +
  # Location marker
  geom_point(data = coords, mapping = aes(x = long[5], y = lat[5]), 
              shape = 0, size = 7, stroke = 1, col = "black") +
  coord_fixed(1.3) +
  guides(fill = FALSE)
# State map
b <- 
  ggplot() +
  theme_nothing() +
  # Rivers
  geom_path(data = ks_rivers, aes(x = long, y = lat, group = group), col = "#23baaf") +
  # State border
  geom_polygon(data = kansas.map, aes(x = long, y = lat, group = group), 
               fill = NA, color = "grey") +
  # Location marker
  geom_point(data = coords, mapping = aes(x = long[5], y = lat[5]), 
              shape = 0, size = 8, stroke = 1, col = "black") +
  coord_fixed(1.3) +
  guides(fill = FALSE) +
    labs(tag = "A") 

ggsave("./Map.png", height = 1.5, width = 3.5, units = "in")

c <-  
ggplot() +
  theme_nothing() +
  # Rivers
  geom_path(data = ks_rivers.all, aes(x = long, y = lat, group = group, col = "S2")) +
  geom_path(data = ks_rivers, aes(x = long, y = lat, group = group, col = "S2"), 
            size = 1.5) +
  # Site location bubbles
  geom_point(data = coords, mapping = aes(x = long[1], y = lat[1], col = "S0"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[5], y = lat[5], col = "S1"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[8], y = lat[8], col = "S2"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[15], y = lat[15], col = "S3"), 
             shape = 1, size = 5, stroke = 2) +
  # Lawrence
  geom_point(data = NULL, mapping = aes(y = 38.94, x = -95.28, col = "S0"), 
             shape = 2, size = 5) +
  # Release point
  geom_point(data = NULL, mapping = aes(y = 38.969, x = -95.21, col = "S0"), 
             shape = 4, size = 5) +
  # Site names
  geom_text(data = coords, aes(x = long, y = lat, label = SiteNickname), 
            nudge_y = -0.017, size = 5) +
  scale_color_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  coord_fixed(1.3)  +
  coord_quickmap(xlim = c(-95.3, -94.9), ylim = c(38.83, 39.1)) +
  theme(panel.border = element_rect(color = "black", fill = NA))

grob <- grid.arrange(a, b, nrow = 2)
grob <- grid.arrange(grob, c, ncol = 2)


# Save plot
ggsave("./Plots/Map.png", grob, height = 3.3, width = 7, units = "in")


# Plot local map
c <- 

# Save plot
ggsave("./Plots/Map_local.png", height = 5, width = 6, units = "in")


# Set up a map box using coordinates
coord.box <- make_bbox(lon = coords$long[5], lat = coords$lat[5])
googmap <- get_stamenmap(bbox = coord.box, zoom = 10, maptype = "watercolor")
ggmap(googmap)
```

```{r Fig 2. N concentration}
# N concentration plot
a <- 
  ggplot(data = massbal, aes(x = date)) +
  # S0
  geom_point(data = massbal[massbal$date < as.Date("2018-02-26"),], 
             aes(x = date, y = Nitrate.bowersock_mgNL, fill = "white"), 
             size = 2, shape = 21) +
  # S0 BDL
  geom_segment(aes(x = as.Date("2018-02-26"), xend = as.Date("2018-05-01"),
                   y = 0.01, yend = 0.01), linetype = 1) +
  # S1
  geom_point(aes(y = Nitrate.eric_mgNL, fill = "S1"), size = 2, shape = 21) +
  # S2
  geom_point(aes(y = Nitrate.steve_mgNL, fill = "S2"), size = 2, shape = 21) +
  # S3
  geom_point(aes(y = Nitrate.desoto_mgNL, fill = "S3"), size = 2, shape = 21) +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_log10()+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "a") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
ggsave("./Plots/Nitrate_time.png",a,height = 2.5, width = 4.5)

# Temperature and discharge
b <- 
  ggplot(data = sensor_desoto, aes(x = date)) +
  geom_line(aes(y = WaterTemp_C), color = "black") +
  geom_line(aes(y = Discharge_m3s/2), linetype = 2) +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0,50), 
                     sec.axis = sec_axis(~.*2, name = expression("Q ("*m^3 ~ s^{-1} *")"))) +
  # axis labels
  labs(tag = "b") +
  xlab(NULL) + 
  ylab(expression("T ("*{degree}*C * ")"))+
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", legend.title = element_blank(), 
        axis.text = element_text(color = "black"))
ggsave("./Plots/T.Q_time.png", b,height = 1.75, width = 4.8)

# Arrange plots
lay <- rbind(c(1),
             c(1),
             c(2))
grob1 <- gridExtra::grid.arrange(a, b, layout_matrix = lay)

# Diel zoom-in 
c <- 
  ggplot(data = diel_eric, aes(x = dateTime)) +
  # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-23 00:00:00"),
                xmax = ymd_hms("2018-03-23 06:00:00"),
                ymin = 0, ymax = 11), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-23 20:00:00"),
                xmax = ymd_hms("2018-03-24 06:00:00"),
                ymin = 0, ymax = 11), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-24 20:00:00"),
                xmax = ymd_hms("2018-03-25 06:00:00"),
                ymin = 0, ymax = 11), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-25 20:00:00"),
                xmax = ymd_hms("2018-03-26 00:00:00"),
                ymin = 0, ymax = 11), fill = "grey") +
  # Plot S1 data on top
  geom_point(aes(y = Nitrate_mgL, fill = "S1"), size = 1.2, shape = 21) +
  
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-23 00:00:00"), 
                              ymd_hms("2018-03-26 00:00:00")),
               date_breaks = "1 day", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0, 11))+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "c") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
d <- 
  ggplot(data = diel_steve, aes(x = dateTime)) +
    # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-28 00:00:00"),
                xmax = ymd_hms("2018-03-28 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-28 20:00:00"),
                xmax = ymd_hms("2018-03-29 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-29 20:00:00"),
                xmax = ymd_hms("2018-03-30 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-30 20:00:00"),
                xmax = ymd_hms("2018-03-31 00:00:00"),
                ymin = 0, ymax = 0.6), fill = "grey") +
  # S2
  geom_point(aes(y = Nitrate_mgL, fill = "S2"), size = 1.2, shape = 21) +
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-28 00:00:00"), 
                              ymd_hms("2018-03-31 00:00:00")),
               date_breaks = "1 days", date_labels = "%b %e" ) + 
  #scale_y_log10()+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  scale_y_continuous(limits = c(0, 0.6)) +
  # axis labels
  labs(tag = "d") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
e <- 
  ggplot(data = diel_desoto, aes(x = dateTime)) +
  # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-24 00:00:00"),
                xmax = ymd_hms("2018-03-24 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-24 20:00:00"),
                xmax = ymd_hms("2018-03-25 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-25 20:00:00"),
                xmax = ymd_hms("2018-03-26 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "grey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-26 20:00:00"),
                xmax = ymd_hms("2018-03-27 00:00:00"),
                ymin = 0, ymax = 0.75), fill = "grey") +
  # S3
  geom_point(aes(y = Nitrate_mgL, fill = "S3"), size = 1.2, shape = 21) +
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-24 00:00:00"), 
                              ymd_hms("2018-03-27 00:00:00")),
               date_breaks = "1 days", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0, 0.75)) +
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "e") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

grob2 <- gridExtra::grid.arrange(c, d, e, ncol = 1)
gridExtra::grid.arrange(grob1, grob2, ncol = 2)

ggsave("./Plots/DielN.png", grob2, height = 3.95, width = 2)

### Depreciated ###

# N load plot
ggplot(data = massbal, aes(x = date)) +
  # Upstream (Bowersock)
  geom_line(aes(y = NitrateLoad.bowersock_gNday/1000, color = "S0")) +
  geom_point(aes(y = NitrateLoad.bowersock_gNday/1000, color = "S0")) +
  # Bowersock: BDL designation
  geom_point(data = massbal[massbal$Nitrate.bowersock_mgNL <= 0.1,],
             aes(y = NitrateLoad.bowersock_gNday/1000), shape = 21, fill = "white") +
  # Discharge (Eric)
  geom_line(aes(y = NitrateLoad.eric_gNday/1000, color = "S1")) +
  geom_point(aes(y = NitrateLoad.eric_gNday/1000, color = "S1")) +
  # Downstream (Steve)
  geom_line(aes(y = NitrateLoad.steve_gNday/1000, color = "S2")) +
  geom_point(aes(y = NitrateLoad.steve_gNday/1000, color = "S2")) +
  # Desoto
  geom_line(aes(y = NitrateLoad.desoto_gNday/1000, color = "S3")) +
  geom_point(aes(y = NitrateLoad.desoto_gNday/1000, color = "S3")) +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_log10()+
  scale_color_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  scale_shape_manual(values = 21) +
  # axis labels
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"}-N ~~ "Load  (kg" ~~ day^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", legend.title = element_blank())
ggsave("./Plots/NitrateLoad_time.png", height = 4, width = 6, units = "in")

# N supply plot
ggplot(data = massbal, aes(x = date)) +
  # Upstream (Bowersock)
  #geom_line(aes(y = NitrateLoad.bowersock_gNday/1000, color = "S0")) +
  #geom_point(aes(y = NitrateLoad.bowersock_gNday/1000, color = "S0")) +
  # Bowersock: BDL designation
  #geom_point(data = massbal[massbal$Nitrate.bowersock_mgNL <= 0.1,],
   #          aes(y = NitrateLoad.bowersock_gNday/1000), shape = 21, fill = "white") +
  # Discharge (Eric)
  geom_line(aes(y = NitrateSupply.eric_gNm2day, color = "S1")) +
  geom_point(aes(y = NitrateSupply.eric_gNm2day, color = "S1")) +
  # Downstream (Steve)
  geom_line(aes(y = NitrateSupply.steve_gNm2day, color = "S2")) +
  geom_point(aes(y = NitrateSupply.steve_gNm2day, color = "S2")) +
  # Desoto
  geom_line(aes(y = NitrateSupply.desoto_gNm2day, color = "S3")) +
  geom_point(aes(y = NitrateSupply.desoto_gNm2day, color = "S3")) +
  # Vertical line at 1-Apr-18
  geom_vline(aes(xintercept = as_date("2018-04-01")), linetype = 2) +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_log10()+
  scale_color_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  scale_shape_manual(values = 21) +
  # axis labels
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"}-N ~~ "Supply  (g" ~~ m^{-2} ~ day^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "bottom", legend.title = element_blank())
```

```{r Fig 3. Metabolism}
# GPP, Eric
a <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = GPP.lower.eric, ymax = GPP.upper.eric), fill = "lightgrey") +
  geom_point(aes(y = GPP.eric, fill = "S1"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-5, 25)) +
  # Axis labels
  labs(x = NULL, tag = "a",
       y = bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# GPP, Steve
b <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = GPP.lower.steve, ymax = GPP.upper.steve), fill = "lightgrey") +
  geom_point(aes(y = GPP.steve, fill = "S2"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-5, 25)) +
  # Axis labels
  labs(x = NULL, tag = "b",
       y = bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# GPP, DeSoto
c <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = GPP.lower.desoto, ymax = GPP.upper.desoto), fill = "lightgrey") +
  geom_point(aes(y = GPP.desoto, fill = "S3"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-5, 25)) +
  # Axis labels
  labs(x = NULL, tag = "c",
       y = bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# ER, eric
d <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = ER.lower.eric, ymax = ER.upper.eric), fill = "lightgrey") +
  geom_point(aes(y = ER.eric, fill = "S1"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-30, 5)) +
  # Axis labels
  labs(x = NULL, tag = "d",
       y = bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
e <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = ER.lower.steve, ymax = ER.upper.steve), fill = "lightgrey") +
  geom_point(aes(y = ER.steve, fill = "S2"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-30, 5)) +
  # Axis labels
  labs(x = NULL, tag = "e",
       y = bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
f <- 
  ggplot(data = metab, aes(x = date)) +
  # Dots
  geom_ribbon(aes(ymin = ER.lower.desoto, ymax = ER.upper.desoto), fill = "lightgrey") +
  geom_point(aes(y = ER.desoto, fill = "S3"), size = 2, shape = 21) +
  # Axis limits
  scale_x_date(limits = c(as.Date("2018-02-01"), as.Date("2018-05-01"))) +
  scale_y_continuous(limits = c(-30, 5)) +
  # Axis labels
  labs(x = NULL, tag = "f",
       y = bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

grob <- grid.arrange(a,b,c,d,e,f, ncol = 3, nrow = 2)
ggsave("./Plots/MetabPlot.png", grob, height = 4.5, width = 8.75, units = "in")

ggpubr::compare_means(data = metab.long, value~site, 
                      group.by = c("model", "Month"))
# Average stats
mean(subset(metab_eric, date >= "2018-02-01" & date < "2018-05-01")$GPP, 
            na.rm = TRUE)
mean(subset(metab_steve, date >= "2018-02-01" & date < "2018-05-01")$GPP, 
            na.rm = TRUE)
mean(subset(metab_desoto, date >= "2018-02-01" & date < "2018-05-01")$GPP.desoto, 
            na.rm = TRUE)
mean(subset(metab_eric, date >= "2018-02-01" & date < "2018-05-01")$ER, 
            na.rm = TRUE)
mean(subset(metab_steve, date >= "2018-02-01" & date < "2018-05-01")$ER, 
            na.rm = TRUE)
mean(subset(metab_desoto, date >= "2018-02-01" & date < "2018-05-01")$ER.desoto, 
            na.rm = TRUE)
```

```{r Fig 4: Uptake and Vf}
### Assemble data into a boxplot ##############################################
#uptake.metab.long <- 
#  uptake.metab.long %>% 
#  mutate(Month = factor(month(Date, label = TRUE, abbr = TRUE)),
#         WeekGroup = factor(round_date(Date, period(week = 3))))
#str(uptake.metab.long)

# U ############################################################################
# Broken up by ReleaseStatus
a <- 
  ggplot(data = uptake.long, aes(x = Month, 
                                          y = UaNO3_gNm2day, fill = site)) +
  facet_wrap(~site, nrow = 1) +
  # Error bars
  stat_boxplot(geom = "errorbar", width = 0.5, 
               position = position_dodge(width = 0.75)) +
  # Add text for significance
  ggpubr::stat_compare_means(aes(group = Month), label = "p.format", 
                             label.y.npc = "bottom") +
  # Boxplots
  geom_boxplot(outlier.shape = NA) +
  # Jitter points
  geom_point(position = position_jitterdodge(dodge.width = 1, 
                                             jitter.width = 1), 
             shape = 1, size = 2) +
  scale_y_log10() +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S1_scaled" = "#FF0000",
                               "S2" = "#23baaf", 
                               "S3" = "#F2AD00"),
                     limits = c("S1", "S1_scaled", "S2", "S3")) +
  # axis labels
  labs(tag = "a") +
  xlab(NULL) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

# Vf ###########################################################################
b <- 
  ggplot(data = vf, aes(x = Month, y = vf_mmmin, fill = site)) +
  facet_grid(~site) +
  # Error bars
  stat_boxplot(geom = "errorbar", width = 0.5, 
               position = position_dodge(width = 0.75)) +
  # Box plots
  geom_boxplot(outlier.shape = NA) +
  # Jitter points
  geom_point(position = position_jitterdodge(dodge.width = 1, 
                                             jitter.width = 1), 
             shape = 1, size = 2) +
  # Add text for significance
  ggpubr::stat_compare_means(aes(group = Month), label = "p.format", 
                             label.y.npc = "top") +
  # Labels
  labs(tag = "b") +
  xlab(NULL) +
  ylab(expression(V[f] ~~ "(mm" ~ min^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
grob <- grid.arrange(a,b)
ggsave("./Plots/U.Vf_boxplot.png", grob, height = 5, width = 5.25, units = "in")

ggsave("./Plots/U_boxplot.png", a, height = 2.5, width = 5, units = "in")
ggsave("./Plots/Vf_boxplot.png", b, height = 2.5, width = 4.8, units = "in")

# Merge uptake.long with supply.long
SU.long <- 
  left_join(supply.long, uptake.long, by = c("Date", "Month", 
                                             "site", "WeekGroup"))
# Gather for plotting
plotdata <- gather(SU.long, type, value, Supply_gNm2day, UaNO3_gNm2day)
plotdata$type <- factor(plotdata$type, 
                        levels = c("Supply_gNm2day", "UaNO3_gNm2day"),
                        labels = c("Supply", "Uptake"))

ggplot(data = subset(plotdata, Date < "2018-05-01"), 
       aes(x = Month, y = value)) +
  facet_wrap(~site, nrow = 1) +
  # Boxplots
  geom_boxplot(aes(fill = type), position = position_dodge(1), 
               outlier.shape = NA) +
  # Points
  geom_point(aes(group = type, fill = type), 
             position = position_jitterdodge(jitter.width = 0.2, 
                                             dodge.width = 1), shape = 21) +
  # axis labels
  xlab(NULL) + 
  ylab(expression("Supply or Uptake (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(legend.title = element_blank(), legend.position = "bottom",
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

## Plot supply
ggplot(data = subset(supply.long, Date < "2018-05-01"), 
       aes(x = Month, y = Supply_gNm2day, fill = site)) +
  facet_wrap(~site, nrow = 1) +
  # Error bars
  stat_boxplot(geom = "errorbar", width = 0.5, 
               position = position_dodge(width = 0.75)) +
  # Add text for significance
  ggpubr::stat_compare_means(aes(group = Month), label = "p.format", 
                             label.y.npc = "bottom") +
  # Boxplots
  geom_boxplot(outlier.shape = NA) +
  # Jitter points
  geom_point(position = position_jitterdodge(dodge.width = 1, 
                                             jitter.width = 1), 
             shape = 1, size = 2) +
  scale_y_log10() +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S1_scaled" = "#FF0000",
                               "S2" = "#23baaf", 
                               "S3" = "#F2AD00"),
                     limits = c("S1", "S1_scaled", "S2", "S3")) +
  # axis labels
  #labs(tag = "A") +
  xlab(NULL) + 
  ylab(expression("Supply (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
ggsave("./Plots/Supply_boxplot.png", height = 3, width = 7, units = "in")



```

```{r Fig 5: Predicted uptake fig}
# Select columns you want
stoich.eric <- 
  stoich.eric %>%
  dplyr::select(Date = date, Ua_gNm2day.eric = Uaut_gNm2day, 
                Uhet_gNm2day.eric = Uhet_gNm2day, 
                Ustoic_gNm2day.eric = U_gNm2day)
stoich.steve <- 
  stoich.steve %>%
  dplyr::select(Date = date, Ua_gNm2day.steve = Uaut_gNm2day, 
                Uhet_gNm2day.steve = Uhet_gNm2day, 
                Ustoic_gNm2day.steve = U_gNm2day)
stoich.desoto <- 
  stoich.desoto %>%
  dplyr::select(Date = date, Ua_gNm2day.desoto = Uaut_gNm2day, 
                Uhet_gNm2day.desoto = Uhet_gNm2day, 
                Ustoic_gNm2day.desoto = U_gNm2day)
# Merge with uptake
stoich <- 
  uptake%>%
  dplyr::full_join(stoich.eric) %>% 
  dplyr::full_join(stoich.steve) %>%
  dplyr::full_join(stoich.desoto)

## Correlation testing
# Full time series
cor.test(~UaNO3_gNm2day.eric+Ustoic_gNm2day.eric, 
         data = stoich)
cor.test(~UaNO3_gNm2day.steve+Ustoic_gNm2day.steve, 
         data = stoich)
cor.test(~UaNO3_gNm2day.desoto+Ustoic_gNm2day.desoto, 
         data = stoich)
# During
cor.test(~UaNO3_gNm2day.eric+Ustoic_gNm2day.eric, 
         data = subset(stoich, ReleaseStatus == "During"))
cor.test(~UaNO3_gNm2day.steve+Ustoic_gNm2day.steve, 
         data = subset(stoich, ReleaseStatus == "During"))
cor.test(~UaNO3_gNm2day.desoto+Ustoic_gNm2day.desoto, 
         data = subset(stoich, ReleaseStatus == "During"))
# After
cor.test(~UaNO3_gNm2day.eric+Ustoic_gNm2day.eric, 
         data = subset(stoich, ReleaseStatus == "After"))
cor.test(~UaNO3_gNm2day.steve+Ustoic_gNm2day.steve, 
         data = subset(stoich, ReleaseStatus == "After"))
cor.test(~UaNO3_gNm2day.desoto+Ustoic_gNm2day.desoto, 
         data = subset(stoich, ReleaseStatus == "After"))


# Black points: After (April), White points: during (Feb, March)
# Eric
#a <- 
  ggplot(data = stoich, aes(x = Ustoic_gNm2day.eric, 
                          y = UaNO3_gNm2day.eric, 
                          shape = ReleaseStatus)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point() +
  # Add correlation coeff
  ggpubr::stat_cor(method = "pearson", label.y.npc = "top", label.x = c(0.56),
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 19)) +
  #scale_color_manual(values = c("During" = "black", "After" = "green", 
  #                              "S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00")) +
  #scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00"),
  #                   limits = c("S1", "S2", "S3")) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# Steve
b <- 
  ggplot(data = stoich, aes(x = Ustoic_gNm2day.steve, 
                          y = UaNO3_gNm2day.steve, 
                          shape = ReleaseStatus)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point() +
  # Add correlation coeff
  ggpubr::stat_cor(method = "pearson", label.y.npc = "top", label.x = c(0.46),
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 19)) +
  #scale_color_manual(values = c("During" = "black", "After" = "green", 
  #                              "S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00")) +
  #scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00"),
  #                   limits = c("S1", "S2", "S3")) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "b") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# Desoto
c <- 
  ggplot(data = stoich, aes(x = Ustoic_gNm2day.desoto, 
                            y = UaNO3_gNm2day.desoto, 
                            shape = ReleaseStatus)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point() +
  # Add correlation coeff
  ggpubr::stat_cor(method = "pearson", label.y.npc = "top", label.x = c(0.3),
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 19)) +
  #scale_color_manual(values = c("During" = "black", "After" = "green", 
  #                              "S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00")) +
  #scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
  #                              "S3" = "#F2AD00"),
  #                   limits = c("S1", "S2", "S3")) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "c") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

grob <- grid.arrange(a,b,c, ncol = 3, nrow = 1)
ggsave(grob, file = "./Plots/U_Upred.png", height = 2.75, width = 8.5, 
       units = "in")
```

```{r Fig 6. GPP vs U & GPP vs Vf}
a <- 
  ggplot(subset(uptake.metab.long, model == "GPP"), 
       aes(x = value, y = UaNO3_gNm2day, fill = site, 
           shape = ReleaseStatus)) +
  facet_grid(site~., scales = "free", switch = "y") +
  # Linear model for During release
  # LM for S1, after, GPP
  geom_smooth(data = subset(uptake.metab.long, 
                            model == "GPP" & 
                            ReleaseStatus == "After" & 
                            site == "S1"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.6) +
  # LM for S2, after, GPP
  geom_smooth(data = subset(uptake.metab.long, 
                            model == "GPP" & 
                            ReleaseStatus == "After" & 
                            site == "S2"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.6) +
  # Plot points on top
  geom_point(size = 2) +
  # Add correlation coeff
  #ggpubr::stat_cor(method = "pearson", label.y.npc = "top", label.x = 0,
  #                 aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_color_manual(values = c("During" = "black", "After" = "green", 
                                "S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00")) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# GPP vs Vf
b <- 
  ggplot(subset(vf.metab, model == "GPP"), 
       aes(x = value, y = vf_mmmin, fill = site, shape = ReleaseStatus)) +
  facet_grid(site~., scales = "free", switch = "y") +
  # LM: S1, after, GPP
  geom_smooth(data = subset(vf.metab, model == "GPP" & 
                              ReleaseStatus == "After" &
                              site == "S1"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.2) +
  # LM: S2, after, GPP
  geom_smooth(data = subset(vf.metab, model == "GPP" & 
                              ReleaseStatus == "After" & 
                              site == "S2"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.6) +
  # LM: S3, during, GPP
  geom_smooth(data = subset(vf.metab, model == "GPP" & 
                              ReleaseStatus == "During" & 
                              site == "S3"),
              method = "lm", fullrange = F, aes(color = ReleaseStatus), 
              fill = "lightgrey", alpha = 0.6) +
  # Plot points on top
  geom_point(size = 2) +
    # Add correlation coeff
  #ggpubr::stat_cor(data = subset(vf.metab, model == "GPP"),
  #                 method = "pearson", #label.x = c(10), 
  #                 aes(label = paste(..rr.label.., ..p.label.., 
  #                                   sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_color_manual(values = c("During" = "black", "After" = "green", 
                                "S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00")) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Axis labels
  scale_x_continuous(limits = c(-3, 17)) +
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "b") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

grob <- grid.arrange(a,b, ncol = 2)
ggsave("./Plots/GPP_U_Vf.png", grob, height = 5.5, width = 5, 
       units = "in")


#######################################
# Combined GPP vs U plot

#a <- 
  ggplot(subset(uptake.metab.long, model == "GPP"), 
       aes(x = value, y = UaNO3_gNm2day, fill = ReleaseStatus, color = site,
           shape = site)) +
  #facet_grid(site~., scales = "free", switch = "y") +
  # Linear model for During release
  # LM for S1, after, GPP
  geom_smooth(data = subset(uptake.metab.long, 
                            model == "GPP" & 
                            ReleaseStatus == "After" & 
                            site == "S1"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.6) +
  # LM for S2, after, GPP
  geom_smooth(data = subset(uptake.metab.long, 
                            model == "GPP" & 
                            ReleaseStatus == "After" & 
                            site == "S2"),
              method = "lm", fullrange = F, aes(color = site), 
              fill = "lightgrey", alpha = 0.6) +
  # Plot points on top
  geom_point(size = 2.5) +
  # Add correlation coeff
  #ggpubr::stat_cor(method = "pearson", label.y.npc = "top", label.x = 0,
  #                 aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("S1" = 22, "S2" = 24, "S3" = 21)) +
  scale_color_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00")) +
  scale_fill_manual(values = c("During" = "white", "After" = "black")) +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))





#######################################

##Plotting diel swing
Uptake_Eqn1$Month <- month(Uptake_Eqn1$Date, label = TRUE, abbr = TRUE)
Uptake_Eqn1$Month <- factor(Uptake_Eqn1$Month)

a <- gather(Uptake_Eqn1, "site", "NitrateChange_Perc", NitrateChange_Perc.eric,
       NitrateChange_Perc.steve, NitrateChange_Perc.desoto)
a$site <- factor(a$site, levels = c("NitrateChange_Perc.eric", 
                          "NitrateChange_Perc.steve",
                          "NitrateChange_Perc.desoto"), 
       labels = c("S1", "S2", "S3"))
# percent change over time
ggplot(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"), 
       aes(x = Month, y = -NitrateChange_Perc, color = site)) +
  geom_boxplot(position = position_dodge2())

# merge diel swing w/ metabolism
metab.long$Date <- metab.long$date
a <- dplyr::full_join(a, metab.long, by = c("Date", "site", "ReleaseStatus"))

## Plot diel swing v GPP
#plot1 <- 
  ggplot(subset(a, Date < "2018-05-01" & Date >= "2018-02-01" & model == "GPP"),
       aes(y = -NitrateChange_Perc, x = value, shape = ReleaseStatus)) +
  facet_grid(site~., scales= "free_x", switch = "both") +
  # Pearson correlation
  #ggpubr::stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~")),
   #                label.x = 25, size = 3)+
  # Add points
  geom_point(aes(fill = site), size = 2.5) +
  # Add trendlines
  geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
                            & site == "S3" & model == "GPP" & 
                              ReleaseStatus == "During"),
              method = "lm", color = "black") +
  #geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
  #                          & site == "S2" & model == "ER"),
  #            method = "lm", color = "black", se = FALSE) +
  #geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
   #                         & site == "S3" & model == "GPP"),
    #          method = "lm", color = "black", se = FALSE) +
  ggpubr::stat_cor(method = "spearman", 
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Labels
  ylab(expression(Delta ~ NO[3]^{"-"})) +
  xlab("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")") +
  #color
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  scale_x_continuous(limits = c(0, 17))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

## Plot diel swing v ER
plot2 <- 
  ggplot(subset(a, Date < "2018-05-01" & Date >= "2018-02-01" & model == "ER"),
       aes(y = -NitrateChange_Perc, x = -value, shape = ReleaseStatus)) +
  facet_grid(site~., scales= "free_x", switch = "both") +
  
  # Add points
  geom_point(aes(fill = site), size = 2.5) +
  # Add trendlines
  #geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
   #                         & site == "S3" & model == "GPP" & 
    #                          ReleaseStatus == "During"),
     #         method = "lm", color = "black") +
  geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
                            & site == "S2" & model == "ER" & 
                              ReleaseStatus == "After"),
              method = "lm", color = "#23baaf", se = T) +
  #geom_smooth(data = subset(a, Date < "2018-05-01" & Date >= "2018-02-01"
   #                         & site == "S3" & model == "GPP"),
    #          method = "lm", color = "black", se = FALSE) +
  #ggpubr::stat_cor(method = "spearman", 
  #                 aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Labels
  ylab(expression(Delta ~ NO[3]^{"-"})) +
  xlab("|ER| (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")") +
  scale_x_continuous(limits = c(-2, 25)) + # theres a point here thats weird and you need to double check it but sfs is in 3 days
  #color
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  #scale_x_continuous(limits = c(0, 17))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
grob2 <- grid.arrange(plot1, plot2, ncol = 2)
ggsave("./Plots/Diel_GPP.png", grob2, height = 6.5, width = 6.5, units = "in")

```

```{r Supplemental. ER vs U & ER vs Vf}
# ER vs U
a <- 
  ggplot(subset(uptake.metab.long, model == "ER"), 
       aes(x = -value, y = UaNO3_gNm2day, fill = site, 
           shape = ReleaseStatus)) +
  facet_grid(site~., scales = "free", switch = "y") +
  # Plot points on top
  geom_point(size = 2.5) +
    # Add correlation coeff
  ggpubr::stat_cor(data = subset(uptake.metab.long, model == "ER"),
                   method = "pearson", #label.x = c(5), 
                   #label.y = c(-300, -600, -100, -250, 850, 750), size = 3,
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_color_manual(values = c("During" = "black", "After" = "green", 
                                "S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00")) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Axis labels
  scale_x_continuous(limits = c(-2, 25)) +
  xlab(bquote("|ER| (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

# Vf vs ER
b <- 
  ggplot(subset(vf.metab, model == "ER"), 
       aes(x = -value, y = vf_mmmin, fill = site, shape = ReleaseStatus)) +
  facet_grid(site~., scales = "free", switch = "y") +
  # Linear model for During release
  #geom_smooth(data = subset(vf.metab, model == "ER" & ReleaseStatus == "During"),
  #            method = "lm", fullrange = F, aes( color = ReleaseStatus), 
  #            fill = "lightgrey", alpha = 0.2) +
  # Linear model for after release
  #geom_smooth(data = subset(vf.metab, model == "ER" & ReleaseStatus == "After"),
  #            method = "lm", fullrange = F, aes( color = site), 
  #            fill = "lightgrey", alpha = 0.6) +
  # Plot points on top
  geom_point(size = 2) +
    # Add correlation coeff
  ggpubr::stat_cor(data = subset(vf.metab, model == "ER"),
                   method = "pearson", #label.x = c(5), 
                   #label.y = c(1000, 870, 1000, 870, 1000, 870), size = 3,
                   aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~"))) +
  # Color scales
  #scale_y_continuous(limits = c(-500, 1200)) +
  scale_shape_manual(values = c("During" = 1, "After" = 21)) +
  scale_color_manual(values = c("During" = "black", "After" = "green", 
                                "S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00")) +
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Axis labels
  xlab(bquote("|ER| (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "b") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

grob <- grid.arrange(a,b, ncol = 2)
ggsave("./Plots/ER_U_Vf.png", grob, height = 6, width = 5.75,  units = "in")
```

```{r Fig 7: Meta-analysis}
### Meta-analysis Discharge vs GPP, Hall et al 2016 Data #######################
a <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = hall, aes(x = q_m3s, y = gpp_gm2d), shape = 21, 
             color = "darkgrey") +
  # Our data
  geom_point(data = means, aes(x = Discharge_m3s.Overall, 
                               y = GPP_gO2m2day.Overall, fill = Site), 
             size = 3, shape = 21) +
  # Add correlation coeff
  #ggpubr::stat_cor(color = "black", method = "spearman") +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("GPP (g" ~ O[2] ~ m^{-2} ~ d^{-1}*")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# Save plot
ggsave("./Plots/Meta_Q.GPP.png", height = 3, width = 3.25, units = "in")

### Meta-analysis Discharge vs ER, Hall et al 2016 Data #######################
b <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = hall, aes(x = q_m3s, y = er_gm2d), shape = 21, 
             color = "darkgrey") +
  # Our data
  geom_point(data = means, aes(x = Discharge_m3s.Overall, 
                               y = ER_gO2m2day.Overall, fill = Site), 
             size = 3, shape = 21) +
  # Add correlation coeff
  #ggpubr::stat_cor(color = "black", method = "spearman") +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  labs(tag = "b") +
  # Axis labels
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("|ER| (g" ~ O[2] ~ m^{-2} ~ d^{-1}*")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# Save plot
ggsave("./Plots/Meta_Q.ER.png", height = 3.5, width = 4.25, units = "in")

# Converting between uptake and uptake velocity
# vf mm/min * NO3 mg/L *[1000L/m3] *[1m/1000mm]*[1g/1000mg] *[1440 min/d] = gN/day*m2
tank$U_gNm2day <- tank$NO3_Vf_mmmin*(tank$NO3_Cb_mgNL/1000)*1440

### Discharge v. total uptake, tank et al 2008 ################################
c <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = tank, aes(x = Discharge_Ls/1000, 
                              y = NO3_Vf_mmmin*(NO3_Cb_mgNL/1000)*1440), 
             shape = 21, color = "darkgrey") +
  #geom_smooth(data = tank, aes(x = Discharge_Ls/1000, 
  #                            y = NO3_Vf_mmmin*(NO3_Cb_mgNL/1000)*1440), 
  #            method = "lm", fullrange = TRUE, 
  #            fill = "lightgrey", alpha = 0.2, color = "black") +
  geom_smooth(data = tank, aes(x = Discharge_Ls/1000, 
                              y = NO3_Vf_mmmin*(NO3_Cb_mgNL/1000)*1440), 
              method = "lm", fullrange = TRUE, 
              fill = "lightgrey", alpha = 0.2, color = "darkgrey") +
  # Rode et al 2016 and Hensley et al 2014 data
  geom_point(data = rode.hensley, aes(x = Discharge_m3s,
                                      y = U_mgNm2day/1000),
             shape = 21, color = "darkgrey") +
  # Our data
  geom_point(data = means, aes(x = Discharge_m3s.Overall, 
                               y = U_gNm2day.Overall, 
                               fill = Site), 
             size = 3, shape = 21) +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1), limits = c(NA, 105)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  labs(tag = "c") +
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ d^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

### Discharge v. Uptake velocity (Tank et al. 2008) ###########################
d <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = tank, aes(x = Discharge_Ls/1000, y = NO3_Vf_mmmin), 
             shape = 21, color = "darkgrey") +
  geom_smooth(data = tank, aes(x = Discharge_Ls/1000, 
                              y = NO3_Vf_mmmin), 
              method = "lm", fullrange = TRUE, color = "darkgrey",
              fill = "lightgrey", alpha = 0.2) +
  # Rode et al 2016 and Hensley et al 2014 data
  geom_point(data = rode.hensley, aes(x = Discharge_m3s,
                                      y = Vf_mmmin),
             shape = 21, color = "darkgrey") +
  # Our data
  geom_point(data = means, aes(x = Discharge_m3s.Overall, 
                               y = vf_mmmin.Overall, 
                               fill = Site), 
             size = 3, shape = 21) +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1), limits = c(NA, 105)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  labs(tag = "d") +
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression(V[f] ~~ "(mm" ~ min^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

arrange <- grid.arrange(a,c,b,d, nrow = 2, ncol = 2)
ggsave("./Plots/Meta_Q.png", arrange, height = 5, width = 5.5, units = "in")

# vf mm/min * NO3 mg/L *[1000L/m3] *[1m/1000mm] *[1g/1000mg] * [1440 min/d] = gN/day*m2
# I don't think the snake r is included in this dataset
# discharge vs uptake velocity dotplot
ggplot() +
  # Data from tank metanalysis
  geom_point(data = tank, aes(x = Discharge_Ls, y = NO3_Vf_mmmin*NO3_Cb_mgNL*1000/1000/1000*1440), 
             shape = 21) +
  #geom_point(data=desoto_uptakemeans, aes(x = Discharge_m3s.Overall*1000, y = UaNO3_gNm2day.Overall), 
  #           color = "blue") +
  geom_point(data=desoto_uptakemeans, aes(x = Discharge_m3s.During*1000, y = UaNO3_gNm2day.During), 
             color = "red") +
  geom_point(data=desoto_uptakemeans, aes(x = Discharge_m3s.After*1000, y = UaNO3_gNm2day.After), 
             color = "green") +
  geom_smooth(data = tank, aes(x = Discharge_Ls, y = NO3_Vf_mmmin*NO3_Cb_mgNL*1000/1000/1000*1440), method = "lm") +
  #geom_point(data = desoto_uptakemeans, aes(x = Discharge_m3s.Overall, y = )
  # Add correlation coeff
  ggpubr::stat_cor(data = tank, aes(x = Discharge_Ls, y = NO3_Vf_mmmin*NO3_Cb_mgNL*1000/1000/1000*1440),
                   color = "black", method = "spearman") +
  # Axis scales
  scale_x_log10(limits = c(0.1, 100000)) +
  scale_y_log10(limits = c(0.0001, 10000)) +
  # Axis labels
  xlab(expression("Q ( L" ~ sec^{-1} * ")")) + 
  ylab(expression(U-NO[3]^{"-"} ~~ "(gN m2 day)")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))


# Discharge vs metabolism dotplot
# Extract mean GPP




```

```{r supplemental}
# Plotting gpp vs water temp to see if gpp vs ua relationships are temp dependent
# eric
ggplot(data = sensor_eric, aes(x = GPP, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# steve
ggplot(data = sensor_steve, aes(x = GPP, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# desoto
ggplot(data = sensor_desoto, aes(x = GPP.desoto, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# ER
# eric
ggplot(data = sensor_eric, aes(x = ER, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# steve
ggplot(data = sensor_steve, aes(x = ER, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))
# desoto
ggplot(data = sensor_desoto, aes(x = ER.desoto, y = WaterTemp_C)) +
  facet_grid(~ReleaseStatus) +
  geom_point(alpha = 0.4, shape = 16) +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  # Add correlation coeff
  ggpubr::stat_cor(method = "spearman", color = "black") +
  # Axis labels
  xlab(bquote("ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab("Daily average water temp (deg C)") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"))

```
