---
title: "Figure File"
author: "Michelle Catherine Kelly"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Copyright (c) 2019 Michelle Catherine Kelly  

License: MIT License  

```{r Setup}
library(lubridate)
library(ggplot2)
library(dplyr)
library(ggmap) # Mapping libraries
library(maps)
library(mapdata)
library(ggpubr)
library(gridExtra)
```

```{r Load data}
# Site location data ---------------------------------------------------------
coords <- read.csv("./Data/GPScoordinates_12Nov18.csv", 
                   stringsAsFactors = FALSE)
# Rename site names
coords$SiteNickname[coords$SiteNickname == "Bowersock"] <- "S0"
coords$SiteNickname[coords$SiteNickname == "Eric"] <- "S1"
coords$SiteNickname[coords$SiteNickname == "Steve"] <- "S2"
coords$SiteNickname[coords$SiteNickname == "Desoto"] <- "S3"

# Sensor data ----------------------------------------------------------------
sensor_eric <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASREASTLAWRENCE_sensorData.csv")
sensor_steve <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASRFALLLEAF_sensorData.csv")
sensor_desoto <- 
  read.csv("./Data/StreamPULSE_Downloaded/KS_KANSASR_sensorData.csv")
# Count total percent of "Bad Data" points out of all data points
sum(sensor_eric$flagtype %in% c("Bad Data"))/nrow(sensor_eric)*100 +
  sum(sensor_steve$flagtype %in% c("Bad Data"))/nrow(sensor_steve)*100 +
  sum(sensor_desoto$flagtype %in% c("Bad Data"))/nrow(sensor_desoto)*100
# summarize sensor data: take daily averages & merge w/ metabolism
dailyavg <- function(sensor_data, avgs){
  # if sensor data has a "bad data" flag, set value to NA
  sensor_data$value[sensor_data$flagtype %in% c("Bad Data")] <- NA
  # reshape sensor data from long format to wide format
  sensor_data <- tidyr::spread(sensor_data, key = variable, value = value)
  # reformat datetime
  sensor_data$DateTime_UTC <- lubridate::ymd_hms(sensor_data$DateTime_UTC)
  # change time zone from UTC to central
  sensor_data$dateTime <- lubridate::with_tz(sensor_data$DateTime_UTC, 
                                             tzone = "America/Chicago")
  if (avgs) {
    # sort data file and find daily averages
    sensor_data <- sensor_data %>%
      dplyr::group_by(date = lubridate::date(dateTime)) %>% 
      dplyr::summarise(Nitrate_mgL = mean(Nitrate_mgL, na.rm = TRUE),
                       Discharge_m3s = mean(Discharge_m3s, na.rm = TRUE),
                       DO_mgL = mean(DO_mgL, na.rm = TRUE),
                       Light_PAR = mean(Light_PAR, na.rm = TRUE),
                       WaterTemp_C = mean(WaterTemp_C, na.rm = TRUE))
  }
  # Factorize release status
  sensor_data$ReleaseStatus <- NA
  sensor_data$ReleaseStatus[sensor_data$date < ymd("2018-04-01")] <- "During"
  sensor_data$ReleaseStatus[sensor_data$date >= ymd("2018-04-01")] <- "After"
  sensor_data$ReleaseStatus <- factor(sensor_data$ReleaseStatus, 
                                      levels = c("During", "After"))
  return(sensor_data)
}

diel_eric <- dailyavg(sensor_eric, avgs = FALSE)
diel_steve <- dailyavg(sensor_steve, avgs = FALSE)
diel_desoto <- dailyavg(sensor_desoto, avgs = FALSE)

sensor_eric <- dailyavg(sensor_eric, avgs = TRUE)
sensor_steve <- dailyavg(sensor_steve, avgs = TRUE)
sensor_desoto <- dailyavg(sensor_desoto, avgs = TRUE)

# Mass balance data ----------------------------------------------------------
massbal <- readRDS("./Outputs/NMassBalance.rds")
# Steve nitrate sensor burial
massbal$Nitrate.steve_mgNL[massbal$date >= ymd("2018-03-10") & 
                             massbal$date <= ymd("2018-03-26")] <- NA

# Metabolism results ---------------------------------------------------------
metab_S1S2 <- readRDS("./Outputs/MetabResults_TwoStation.RData")
metab_desoto <- readRDS("./Outputs/MetabResults_Desoto.RData")$predictions

# Create date sequence of everyday during sampling period, this is so that 
# geom_ribbon will correctly plot NA dates in Figure 3
dates <- data.frame(date = seq(as.Date("2018-02-01"), as.Date("2018-05-01"), 
                               by = "days"))
metab_desoto <- full_join(metab_desoto, dates)
rm(dates)

# Two station model: For days when ER is modeled as positive, remove day from
# dataframe - this is the approach used in Hall et al 2016
sum(metab_S1S2$ER > 0) # Count of days when ER is positive
metab_S1S2$date[metab_S1S2$ER > 0]
sum(metab_S1S2$ER > 0) / length(metab_S1S2$ER) * 100 # Percentage of data removed
metab_S1S2 <- metab_S1S2 %>% filter(metab_S1S2$ER < 0) # Filter data

# Merge into one dataframe and filter by time of interest
metab <- dplyr::full_join(metab_S1S2, metab_desoto, by = "date", 
                          suffix = c(".S1S2", ".S3")) %>%
  filter(date >= as.Date("2018-02-01") & date < as.Date("2018-05-01"))
metab <- metab[order(metab$date),]
rm(metab_S1S2)
rm(metab_desoto)

# Reshape metabolism dataframe -----------------------------------------------
# Factorize release status
metab$ReleaseStatus <- NA
metab$ReleaseStatus[metab$date < ymd("2018-04-01")] <- "During"
metab$ReleaseStatus[metab$date >= ymd("2018-04-01")] <- "After"
metab$ReleaseStatus <- factor(metab$ReleaseStatus, 
                              levels = c("During", "After"))

# Adjust from wide to long format
metab.long <- tidyr::gather(metab %>% select(date, ReleaseStatus, GPP.S1S2, 
                                             ER.S1S2, GPP.S3, ER.S3), 
                            key = site, value = value, GPP.S1S2:ER.S3)

# Factorize site and change labels
metab.long$site <- factor(metab.long$site)
# Initialize column to store metab model type (GPP or ER)
metab.long$model <- metab.long$site
# Rename factor levels
levels(metab.long$model)[levels(metab.long$site)=="GPP.S1S2"] <- "GPP"
levels(metab.long$site)[levels(metab.long$site)=="GPP.S1S2"] <- "S1S2"
levels(metab.long$model)[levels(metab.long$site)=="GPP.S3"] <- "GPP"
levels(metab.long$site)[levels(metab.long$site)=="GPP.S3"] <- "S3"
levels(metab.long$model)[levels(metab.long$site)=="ER.S1S2"] <- "ER"
levels(metab.long$site)[levels(metab.long$site)=="ER.S1S2"] <- "S1S2"
levels(metab.long$model)[levels(metab.long$site)=="ER.S3"] <- "ER"
levels(metab.long$site)[levels(metab.long$site)=="ER.S3"] <- "S3"
metab.long$model <- factor(metab.long$model, levels = c("GPP", "ER")) # Reorder
metab.long$site <- factor(metab.long$site, levels = c("S1S2", "S3"))

metab$PR.S1S2 <- metab$GPP.S1S2/abs(metab$ER.S1S2)
metab$PR.S3 <- metab$GPP.S3/abs(metab$ER.S3)

# Predicted uptake from metabolism results
stoich.S1S2 <- readRDS(file = "./Outputs/StoichUptake_S1S2.RData")
stoich.S1S2 <- stoich.S1S2[stoich.S1S2$date >= ymd("2018-02-01") & 
                   stoich.S1S2$date < ymd("2018-05-01"),]
stoich.desoto <- readRDS(file = "./Outputs/StoichUptake_Desoto.RData")
stoich.desoto <- stoich.desoto[stoich.desoto$date >= ymd("2018-02-01") & 
                   stoich.desoto$date < ymd("2018-05-01"),]

#### Stoichiometric scaling ##################################################

# Predict areal N uptake rate based on metabolism
# Assumptions: (Hall & Tank 2003)
# 1. C production will drive autotrophic & heterotrophic demand for N (AKA, 
#    assume a respiratory quotient = 1)
# 2. Molar C:N scaling ratio = 20 [g C / g N] (Hall & Tank 2003) OR 
#    Molar C:N scaling ratio = 12 [g C / g N] (Covino et al 2018, citing 
#    steltzer & lamberti 2001) OR
#    Molar C:N scaling ratio = 16 [g C / g N] average of algae in the Little 
#    MO River, from E. Arsenault unpublished data
# 3. Net autotrophic production is 0.5*GPP (Odum 1957, Webster & Myer 1997)
# 4. Heterotrophic respiration can be estimated from ecosystem respiration
#    using the equation HR = ER - ra*GPP where HR is herotrophic respiration, 
#    and ra is a growth efficiency term. Hall & Tank select a moderate growth 
#    efficiency = 0.2 and low growth efficiency = 0.05 to bound their estimate
# 5. Heterotrophic N assimilation can be calculated assuming a respiratory 
#    quotient of 1 and a C:N scaling ratio of 20:1 (both Hall & Tank 2003 and
#    Covino et al 2018 use 20 as ratio)

# Equations -----------------------------------------------------------------

# Autotrophic N assimilation = GPP [gO2/m2d] * Respiratory quotient [g C/g O2] 
#                                  * Autotrophic respiration coefficient 
#                                  * C:N scaling ratio [g N / g C]
# Ua [g N / m2 day ] = GPP * 1 * 0.5 * 1/20 or 1/12

# Heterotrophic respiration = ER - ra * GPP
# HR [g O2 / m2 day] = ER - 0.5 or 0.2 * GPP

# Heterotrophic N assimilation = HR [g O2 / m2 day] 
#                                * Respiratory quotient [g C / g O2]
#                                * C:N scaling ratio [g N / g C]
# Heterotrophic N assimilation = HR * 1 * 1/20

# Assumed constants ----------------------------------------------------------

RespQuot <- 1
AutoRespCoeff <- 0.5
CNscaleAut <- 20
CNscaleHet <- 20

ra.med <- 0.5
ra.low <- 0.2

# Run calculation ------------------------------------------------------------
stoich20 <-
  metab %>%
  mutate(# S1S2
         ER.S1S2 = abs(ER.S1S2),
         Uaut_gNm2day.S1S2 = GPP.S1S2 * RespQuot * AutoRespCoeff / CNscaleAut,
         HR = ER.S1S2 - ra.low * GPP.S1S2,
         Uhet_gNm2day.S1S2 = HR / CNscaleHet,
         Upred_gNm2day.S1S2 = Uaut_gNm2day.S1S2 + Uhet_gNm2day.S1S2,
         # S3
         ER.S3 = abs(ER.S3),
         Uaut_gNm2day.S3 = GPP.S3 * RespQuot * AutoRespCoeff / CNscaleAut,
         HR = ER.S3 - ra.low * GPP.S3,
         Uhet_gNm2day.S3 = HR / CNscaleHet,
         Upred_gNm2day.S3 = Uaut_gNm2day.S3 + Uhet_gNm2day.S3)

stoich16 <-
  metab %>%
  mutate(# S1S2
         ER.S1S2 = abs(ER.S1S2),
         Uaut_gNm2day.S1S2 = GPP.S1S2 * RespQuot * AutoRespCoeff / 16,
         HR = ER.S1S2 - ra.low * GPP.S1S2,
         Uhet_gNm2day.S1S2 = HR / CNscaleHet,
         Upred_gNm2day.S1S2 = Uaut_gNm2day.S1S2 + Uhet_gNm2day.S1S2,
         # S3
         ER.S3 = abs(ER.S3),
         Uaut_gNm2day.S3 = GPP.S3 * RespQuot * AutoRespCoeff / 16,
         HR = ER.S3 - ra.low * GPP.S3,
         Uhet_gNm2day.S3 = HR / CNscaleHet,
         Upred_gNm2day.S3 = Uaut_gNm2day.S3 + Uhet_gNm2day.S3)

# Nitrate uptake results -----------------------------------------------------
uptake <- readRDS("./Outputs/NitrateUptakeResults_Eqn1_twostation.rds")
uptake$UaNO3_gNm2day.steve[uptake$Date == "2018-03-01"] <- NA # affected by 
# rapid discharge change, U calculation overestimate
uptake$UaNO3_gNm2day.steve[uptake$Date == "2018-03-09"] <- NA # affected by 
# sensor burial that started around 03-10
# Section date
uptake <- uptake[uptake$Date >= ymd("2018-02-01") & 
                   uptake$Date < ymd("2018-05-01"),]

## Calculate uptake velocity ###################################################

# vf = U [g-N / m2 day] / NO3 [mg-N / L] * 1000 [mg-N / g-N] / 1000 [m3 / L] 
#    = vf [m / day] / 1440 [day / min] * 1000 [mm/m] = vf [mm/min]
uptake$vf_mmmin.eric <- 
  uptake$UaNO3_gNm2day.eric / uptake$Mean.Nitrate_mgL.eric / 1440 * 1000
uptake$vf_mmmin.steve <- 
  uptake$UaNO3_gNm2day.steve / uptake$Mean.Nitrate_mgL.steve / 1440 * 1000
uptake$vf_mmmin.desoto <- 
  uptake$UaNO3_gNm2day.desoto / uptake$Mean.Nitrate_mgL.desoto / 1440 * 1000
# Adjust data frame structure
vf <- tidyr::gather(uptake[c("Date", "vf_mmmin.eric", "vf_mmmin.steve", "vf_mmmin.desoto")], 
                    key = site, value = vf_mmmin, 
                    vf_mmmin.eric:vf_mmmin.desoto)
vf$site <- factor(vf$site, levels = c("vf_mmmin.eric", "vf_mmmin.steve", 
                                      "vf_mmmin.desoto"))
levels(vf$site)[levels(vf$site)=="vf_mmmin.eric"] <- "S1"
levels(vf$site)[levels(vf$site)=="vf_mmmin.steve"] <- "S2"
levels(vf$site)[levels(vf$site)=="vf_mmmin.desoto"] <- "S3"
vf <- subset(vf, Date < "2018-05-01")
vf$Month <- lubridate::month(vf$Date, label = TRUE, abbr = TRUE)

# Adjust from wide to long format
uptake.long <- 
  uptake %>%
  tidyr::gather(site, UaNO3_gNm2day, UaNO3_gNm2day.eric, UaNO3_gNm2day.steve, 
         UaNO3_gNm2day.desoto) %>%
  select(Date, site, UaNO3_gNm2day)

# Rename site names
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.eric"] <- "S1"
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.steve"] <- "S2"
uptake.long$site[uptake.long$site == "UaNO3_gNm2day.desoto"] <- "S3"

# Factorize site name
uptake.long$site <- factor(uptake.long$site)

# Merge stoich with uptake
stoich20 <- uptake %>%
  dplyr::full_join(stoich20, by = c("Date" = "date", "ReleaseStatus"))
stoich16 <- uptake %>%
  dplyr::full_join(stoich16, by = c("Date" = "date", "ReleaseStatus"))

# DOC data -------------------------------------------------------------------
DOC <- read.csv("./Data/KAW_RAPID_DOC.csv", header = TRUE, 
                stringsAsFactors = FALSE)
DOC$SamplingDate <- lubridate::mdy(DOC$SamplingDate)

# Meta analysis data ---------------------------------------------------------
# Tank et al 2008 uptake meta-analysis
tank <- read.csv("./Data/Meta-analysis/Tank_2008_uptakedata.csv",
                 header = TRUE)
tank$NO3_Cb_mgNL <- tank$NO3_Cb_ugNL/1000
# Rode et al 2016
rode.hensley <- read.csv("./Data/Meta-analysis/Rode_Hensley_SensorUptake.csv")
# Hall et al 2016 metabolism meta-analysis
hall <- read.csv("./Data/Meta-analysis/Hall_2016_metabolismdata.csv", 
                 header = TRUE)
hall$q_m3s <- hall$q_Ls/1000
```

```{r Calculation:stoichiometric scaling}


# Save to RData and CSV
saveRDS(stoich.S1S2, file = "./Outputs/StoichUptake_S1S2.RData")
write.csv(stoich.S1S2, file ="./Outputs/StoichUptake_S1S2.CSV", row.names = F)
saveRDS(stoich.desoto, file = "./Outputs/StoichUptake_Desoto.RData")
write.csv(stoich.desoto, file ="./Outputs/StoichUptake_Desoto.CSV", row.names = F)
```

```{r Stats}
#metab.long$Month <- lubridate::month(metab.long$Date)
# Correct date spans
#metab.long <- 
 # metab.long[metab.long$Date < "2018-05-01" & metab.long$Date >= "2018-02-01",]
#PR <- PR[PR$date < "2018-05-01" & PR$date >= "2018-02-01",]
vf.metab <- vf.metab[vf.metab$Date < "2018-05-01" & vf.metab$Date >="2018-02-01",]
# Factorize release status
uptake.long$ReleaseStatus <- NA
uptake.long$ReleaseStatus[uptake.long$Date < ymd("2018-04-01")] <- "During"
uptake.long$ReleaseStatus[uptake.long$Date >= ymd("2018-04-01")] <- "After"
uptake.long$ReleaseStatus <- factor(uptake.long$ReleaseStatus, 
                              levels = c("During", "After"))

## Metabolism ##################################################################
# Test whether GPP was different between S1-S2 and S3
# Need to compare the means of paired samples: Paired sample T-test
mean(metab$GPP.S1S2, na.rm = T) # Mean of GPP at S1S2
mean(metab[na.omit(metab$GPP.S1S2),]$GPP.S3, na.rm = T) # Mean of GPP at S3 during S1S2 data
mean(metab$GPP.S3, na.rm = T)
t.test(metab$GPP.S1S2, metab$GPP.S3, paired = TRUE, alternative = "two.sided")

# Test whether ER was different between S1-S2 and S3
mean(metab$ER.S1S2,na.rm = T) # Mean of ER at S1S2
mean(metab[na.omit(metab$ER.S1S2),]$ER.S3, na.rm = T) # Mean of ER at S3 during S1S2 data
mean(metab$ER.S3, na.rm = T)
t.test(abs(metab$ER.S1S2), abs(metab$ER.S3), paired = TRUE, alternative = "two.sided")

## Uptake ######################################################################
# Test whether mean U was different between sites
mean(uptake$UaNO3_gNm2day.eric, na.rm = T) # Mean of Udiel at S1
uptake.long %>% 
  filter(site == "S1") %>% 
  summarise(mean(UaNO3_gNm2day, na.rm = T)) # Just double checking
mean(uptake$UaNO3_gNm2day.steve, na.rm = T) # Mean of Udiel at S2
mean(uptake$UaNO3_gNm2day.desoto, na.rm = T) # Mean of Udiel at S3
# One-way ANOVA to assess differences between sites
# ANOVA for only days where we have data for all 3 sites
UANOVA_data <- na.omit(uptake %>% select(Date, UaNO3_gNm2day.eric, 
                                        UaNO3_gNm2day.steve, 
                                        UaNO3_gNm2day.desoto)) %>%
  tidyr::pivot_longer(cols = 2:4, names_to = "site", 
                      values_to = "UaNO3_gNm2day")
UANOVA <- aov(UaNO3_gNm2day ~ site, data = UANOVA_data)
summary(UANOVA)
# Posthoc testing
TukeyHSD(UANOVA)

# Linear model
forecast::tslm(UaNO3_gNm2day.eric ~ Date, data = uptake) # We can use regular lm even though this is time series data because the data does not have seasonality
cor.test(x = zoo::as.zoo(uptake$Date), y = uptake$UaNO3_gNm2day.eric, 
         method = "pearson", use = "complete.obs")
lmmodel <- lm(uptake$UaNO3_gNm2day.eric ~ zoo::as.zoo(uptake$Date)) # S1
summary(lmmodel) # S1
lmmodel <- lm(uptake$UaNO3_gNm2day.steve ~ zoo::as.zoo(uptake$Date)) # S2
summary(lmmodel) # S2
lmmodel <- lm(uptake$UaNO3_gNm2day.desoto ~ zoo::as.zoo(uptake$Date)) # S3
summary(lmmodel) # S3

## Uptake velocity #############################################################
# Test whether mean Vf was different between sites
mean(uptake$vf_mmmin.eric, na.rm = T) # S1
vf %>% 
  filter(site == "S1") %>% 
  summarise(mean(vf_mmmin, na.rm = T)) # Just double checking
mean(uptake$vf_mmmin.steve, na.rm = T) # S2
mean(uptake$vf_mmmin.desoto, na.rm = T) # S3
# One-way ANOVA to assess differences between sites
# ANOVA for only days where we have data for all 3 sites
VfANOVA_data <- na.omit(uptake %>% select(Date, vf_mmmin.eric, 
                                        vf_mmmin.steve, 
                                        vf_mmmin.desoto)) %>%
  tidyr::pivot_longer(cols = 2:4, names_to = "site", 
                      values_to = "vf_mmmin")
VfANOVA <- aov(vf_mmmin ~ site, data = VfANOVA_data)
summary(VfANOVA)
# Posthoc testing
TukeyHSD(VfANOVA)

# Linear model
forecast::tslm(vf_mmmin.eric ~ Date, data = uptake) # We can use regular lm even though this is time series data because the data does not have seasonality
cor.test(x = zoo::as.zoo(uptake$Date), y = uptake$vf_mmmin.eric, 
         method = "pearson", use = "complete.obs")
lmmodel <- lm(uptake$vf_mmmin.eric ~ zoo::as.zoo(uptake$Date)) # S1
summary(lmmodel) # S1
lmmodel <- lm(uptake$vf_mmmin.steve ~ zoo::as.zoo(uptake$Date)) # S2
summary(lmmodel) # S2
lmmodel <- lm(uptake$vf_mmmin.desoto ~ zoo::as.zoo(uptake$Date)) # S3
summary(lmmodel) # S3

## Udiel vs Upred  ############################################################
# Means
mean(stoich$Ustoic_gNm2day.S1S2, na.rm = T) # S1-S2 U pred
mean(stoich[-which(is.na(stoich$Ustoic_gNm2day.S1S2)),]$UaNO3_gNm2day.steve,
     na.rm = T) # U diel mean at S2 during S1S2 data
mean(stoich$Ustoic_gNm2day.S3, na.rm = T) # S3 U pred
mean(stoich[-which(is.na(stoich$Ustoic_gNm2day.S3)),]$UaNO3_gNm2day.desoto,
     na.rm = T) # U diel mean at S3 during S3 data
## Compare during release vs after at S3
stoich %>% 
  filter(ReleaseStatus == "During",
         !is.na(Ustoic_gNm2day.S3)) %>%
  summarise(mean(UaNO3_gNm2day.desoto, na.rm = T),
            mean(Ustoic_gNm2day.S3, na.rm = T))
stoich %>% 
  filter(ReleaseStatus == "After",
         !is.na(Ustoic_gNm2day.S3)) %>%
  summarise(mean(UaNO3_gNm2day.desoto, na.rm = T),
            mean(Ustoic_gNm2day.S3, na.rm = T))

# Linear model
lmmodel <- lm(stoich$Ustoic_gNm2day.S1S2 ~ stoich$UaNO3_gNm2day.eric) # S1S2 vs S1
summary(lmmodel) # S1S2 vs S1
lmmodel <- lm(stoich$Ustoic_gNm2day.S1S2 ~ stoich$UaNO3_gNm2day.steve) # S1S2 vs S2
summary(lmmodel) # S1S2 vs S2
lmmodel <- lm(stoich$Ustoic_gNm2day.S3 ~ stoich$UaNO3_gNm2day.desoto) # S3
summary(lmmodel) # S3
# During waste release
lmmodel <- lm(Ustoic_gNm2day.S3 ~ UaNO3_gNm2day.desoto,
              data = subset(stoich, ReleaseStatus == "During")) # S3
summary(lmmodel) # S3
lmmodel <- lm(Ustoic_gNm2day.S3 ~ UaNO3_gNm2day.desoto,
              data = subset(stoich, ReleaseStatus == "After")) # S3
summary(lmmodel) # S3

## Udiel & Vf vs GPP ################################################
# Linear model
# Udiel 
lmmodel <- lm(UaNO3_gNm2day.steve ~ GPP.S1S2, data = stoich) # S1S2
summary(lmmodel) # S1S2
lmmodel <- lm(UaNO3_gNm2day.desoto ~ GPP.S3, data = stoich) # S3
summary(lmmodel) # S3
# Vf
lmmodel <- lm(vf_mmmin.steve ~ GPP.S1S2, data = stoich) # S1S2
summary(lmmodel) # S1S2
lmmodel <- lm(vf_mmmin.desoto ~ GPP.S3, data = stoich) # S3
summary(lmmodel) # S3

# During waste release
lmmodel <- lm(UaNO3_gNm2day.desoto ~ GPP.S3,
              data = subset(stoich, ReleaseStatus == "During")) # S3
summary(lmmodel) # S3
lmmodel <- lm(UaNO3_gNm2day.desoto ~ GPP.S3,
              data = subset(stoich, ReleaseStatus == "After")) # S3
summary(lmmodel) # S3
cor.test(x = subset(stoich, ReleaseStatus == "During")$UaNO3_gNm2day.desoto,
    y = subset(stoich, ReleaseStatus == "During")$GPP.S3)
cor.test(x = subset(stoich, ReleaseStatus == "After")$UaNO3_gNm2day.desoto,
    y = subset(stoich, ReleaseStatus == "After")$GPP.S3)
cor.test(x = stoich$UaNO3_gNm2day.desoto,
    y = stoich$GPP.S3)

## Udiel & Vf vs ER ################################################
# Linear model
# Udiel 
lmmodel <- lm(UaNO3_gNm2day.steve ~ ER.S1S2, data = stoich) # S1S2
summary(lmmodel) # S1S2
lmmodel <- lm(UaNO3_gNm2day.desoto ~ ER.S3, data = stoich) # S3
summary(lmmodel) # S3

# Vf
lmmodel <- lm(vf_mmmin.steve ~ ER.S1S2, data = stoich) # S1S2
summary(lmmodel) # S1S2
lmmodel <- lm(vf_mmmin.desoto ~ ER.S3, data = stoich) # S3
summary(lmmodel) # S3

# Udiel vs PR
lmmodel <- lm(UaNO3_gNm2day.steve ~ GPP.S1S2/ER.S1S2, data = stoich) # S1S2
summary(lmmodel) # S1S2
lmmodel <- lm(UaNO3_gNm2day.desoto ~ GPP.S3/ER.S3, data = stoich) # S3
summary(lmmodel) # S3
lmmodel <- lm(vf_mmmin.desoto ~ GPP.S3/ER.S3, data = stoich) # S3
summary(lmmodel) # S3
```

```{r Calculation: Mean data}
### Ammonium ####
## S0
mean(massbal$Ammonium.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.bowersock_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
## S1
mean(massbal$Ammonium.eric_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.eric_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
## S2
mean(massbal$Ammonium.steve_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.steve_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)
## S3
mean(massbal$Ammonium.desoto_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)
sd(massbal$Ammonium.desoto_mgNL[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)

### Nitrate and Discharge ####
sensorData <- full_join(sensor_eric, sensor_steve, by = "date", 
               suffix =c(".S1", ".S2")) %>%
  full_join(., sensor_desoto, by = "date") %>%
  filter(date >= "2018-02-01" & date < "2018-05-01")
sensorMeans <-
  sensorData %>%
  summarise_if(is.numeric, mean, na.rm = T)
sensorSD <- 
  sensorData %>%
  summarise_if(is.numeric, sd, na.rm = T)

## Calculating mean nitrate when only all observations are present
a <- sensorData %>% 
  tidyr::drop_na() %>%
  summarise_if(is.numeric, mean, na.rm = T)

# Discharge
## S0
mean(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                             massbal$date <= "2018-05-01"], na.rm = TRUE)/1000
sd(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
   na.rm = TRUE)/1000

# Discharge at S1 and S2 is the same, calculated as S0 + farmland pump
ggplot() +
  geom_line(data = sensor_eric, aes(x = date, y = Discharge_m3s)) +
  geom_point(data = sensor_steve, aes(x = date, y = Discharge_m3s))

sensor_eric$date[1]
sensor_steve$date[1]

mean(sensor_steve$Discharge_m3s[sensor_steve$date>= "2018-02-01" &
                            sensor_steve$date<= "2018-05-01"])
sd(sensor_steve$Discharge_m3s[sensor_steve$date>= "2018-02-01" &
                            sensor_steve$date<= "2018-05-01"])

# Uptake ####
## S1
mean(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-02-01" & 
                                   uptake$Date < "2018-05-01"], na.rm = TRUE)
sd(uptake$UaNO3_gNm2day.eric[uptake$Date >= "2018-02-01" & 
                                   uptake$Date < "2018-05-01"], na.rm = TRUE)
## S2
mean(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-02-01" & 
                                    uptake$Date < "2018-05-01"], na.rm = TRUE)
sd(uptake$UaNO3_gNm2day.steve[uptake$Date >= "2018-02-01" & 
                                    uptake$Date < "2018-05-01"], na.rm = TRUE)
## S3
mean(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-02-01" & 
                                     uptake$Date < "2018-05-01"], na.rm = TRUE)
sd(uptake$UaNO3_gNm2day.desoto[uptake$Date >= "2018-02-01" & 
                                     uptake$Date < "2018-05-01"], na.rm = TRUE)

# Vf ####
## S1
mean(vf$vf_mmmin[vf$site == "S1"], na.rm = TRUE)
sd(vf$vf_mmmin[vf$site == "S1"], na.rm = TRUE)
## S2
mean(vf$vf_mmmin[vf$site == "S2"], na.rm = TRUE)
sd(vf$vf_mmmin[vf$site == "S2"], na.rm = TRUE)
## S3
mean(vf$vf_mmmin[vf$site == "S3"], na.rm = TRUE)
sd(vf$vf_mmmin[vf$site == "S3"], na.rm = TRUE)

# GPP ####
## S1S2
mean(metab$GPP.S1S2, na.rm = TRUE)
sd(metab$GPP.S1S2, na.rm = TRUE)
## S3
mean(metab$GPP.S3, na.rm = TRUE)
sd(metab$GPP.S3, na.rm = TRUE)

# ER ####
## S1S2
mean(stoich$ER.S1S2, na.rm = TRUE) #check
mean(metab$ER.S1S2, na.rm = TRUE) #check
sd(metab$ER.S1S2, na.rm = TRUE)
## S3
mean(metab$ER.S3, na.rm = TRUE)
sd(metab$ER.S3, na.rm = TRUE)

# K ####
## S1S2
mean(metab$K, na.rm = TRUE)
sd(metab$K, na.rm = TRUE)
## S3
d <- readRDS("./Outputs/MetabResults_Desoto.RData")$fit@fit$daily %>%
  filter(date >= "2018-02-01" & date <= "2018-05-01")
mean(d$K600_daily_mean, na.rm = TRUE)
sd(d$K600_daily_mean, na.rm = TRUE)

# P/R ####
## S1S2
mean(metab$PR.S1S2, na.rm = TRUE)
sd(metab$PR.S1S2, na.rm = TRUE)
## S3
mean(metab$PR.S3, na.rm = TRUE)
mean(metab[na.omit(metab$PR.S1S2),]$PR.S3, na.rm = T) # Mean of ER at S3 during S1S2 data
sd(metab$PR.S3, na.rm = TRUE)

# DOC ####
DOC %>%
  filter(SamplingDate >= "2018-02-01" & SamplingDate <= "2018-05-01") %>%
  arrange(SamplingDate) %>%
  group_by(Site) %>%
  filter(Site == "Dam" | Site == "Disch" | Site == "Steve" | Site == "Desoto") %>%
  summarise(mean_NPOC_mgL = mean(Result_NPOC_mg.L), sd = sd(Result_NPOC_mg.L), 
            n = length(Result_NPOC_mg.L))

# T ####
mean(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
max(sensor_desoto$WaterTemp_C[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)

# Q
# S0
mean(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)/1000
sd(massbal$Q.lawrence_Ls[massbal$date >= "2018-02-01" &
                                      massbal$date <= "2018-05-01"], 
     na.rm = TRUE)/1000
# S1
mean(sensor_eric$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
sd(sensor_eric$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
# S2
mean(sensor_steve$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
sd(sensor_steve$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
# S3
mean(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
sd(sensor_desoto$Discharge_m3s[sensor_desoto$date >= "2018-02-01" & 
                            sensor_desoto$date <= "2018-05-01"], na.rm = TRUE)
```

```{r Fig 1. Map}
# Pull country, state, county map data
state.map <- map_data("state")
kansas.map <- subset(state.map, region == "kansas")
counties.map <- subset(map_data("county"), region == "kansas")

# Pull rivers map data:
# Data provided by Esri, National Atlas of the United States and the United 
# States Geological Survey, accessed 26-Jan-19, ArcGIS "USA Rivers and Streams" 
# dataset www.arcgis.com
load(url("https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/datasets/usa_rivers.RData"))
lines.rivers2 <- subset(lines.rivers, STATE %in% c("KS") & 
                          NAME %in% c("Kansas River", "Republican River", "Little Blue River",
                                      "Big Blue River", "West Fork Big Blue River",
                                      "North Branch West Fork Big Blue River",
                                      "Big Blue Creek", "North Fork Smoky Hill River",
                                      "Smoky Hill River", "Saline River",
                                      "Saline Branch", "North Fork Saline River",
                                      "South Fork Saline River", "Solomon River",
                                      "North Fork Solomon River", "South Fork Solomon River"))
ks_rivers <- fortify(lines.rivers2)
ks_rivers.all <- fortify(subset(lines.rivers, STATE %in% c("KS")))

unique(lines.rivers$NAME[grep("Kansas", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Blue", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Smoky", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Saline", lines.rivers$NAME)])
unique(lines.rivers$NAME[grep("Solomon", lines.rivers$NAME)])

# USA map
#a <- 
ggplot() +
  theme_nothing() +
  geom_polygon(data = state.map, 
               aes(x = long, y = lat, group = group), 
               color = "black", size = 0.2, fill = NA) +
  coord_fixed(1.3) +
  guides(fill = FALSE)
ggsave("./Plots/Fig1_a_Map_USA.jpg", height = 40, width = 50, units = "mm", dpi = 600)
# State map
#b <- 
  ggplot() +
  theme_nothing() +
  # County border
  geom_polygon(data = counties.map, aes(x = long, y = lat, group = group), 
               fill = NA, color = "grey", size = 0.2) +
  # Rivers
  geom_path(data = ks_rivers, aes(x = long, y = lat, group = group), 
            col = "#23baaf", size = 0.2) +
  # State border
  geom_polygon(data = kansas.map, aes(x = long, y = lat, group = group), 
               fill = NA, color = "black", size = 0.2) +
 
  # Location marker
  geom_point(data = coords, mapping = aes(x = long[5], y = lat[5]), 
              shape = 0, size = 4, stroke = 0.5, col = "black") +
  coord_fixed(1.3) +
  guides(fill = FALSE)
ggsave("./Plots/Fig1_b_Map_KS.jpg", height = 40, width = 50, units = "mm", dpi = 600)

#c <-  
ggplot() +
  #theme_nothing() +
  # County border
  geom_polygon(data = counties.map, aes(x = long, y = lat, group = group), 
               fill = NA, color = "grey", size = 0.2) +
  # Rivers
  geom_path(data = ks_rivers.all, aes(x = long, y = lat, group = group, col = "S2")) +
  geom_path(data = ks_rivers, aes(x = long, y = lat, group = group, col = "S2"), 
            size = 1.5) +
  # Site location bubbles
  geom_point(data = coords, mapping = aes(x = long[1], y = lat[1], col = "S0"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[5], y = lat[5], col = "S1"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[8], y = lat[8], col = "S2"), 
             shape = 1, size = 5, stroke = 2) +
  geom_point(data = coords, mapping = aes(x = long[15], y = lat[15], col = "S3"), 
             shape = 1, size = 5, stroke = 2) +
  # Lawrence
  geom_point(data = NULL, mapping = aes(y = 38.94, x = -95.28, col = "S0"), 
             shape = 2, size = 5) +
  # Release point
  geom_point(data = NULL, mapping = aes(y = 38.969, x = -95.21, col = "S0"), 
             shape = 4, size = 5) +
  # Site names
  geom_text(data = coords, aes(x = long, y = lat, label = SiteNickname), 
            nudge_y = -0.017, size = 5) +
  scale_color_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  coord_fixed(1.3)  +
  coord_quickmap(xlim = c(-95.3, -94.9), ylim = c(38.83, 39.1)) +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", axis.title = element_blank(),
        text = element_text(size = 8))

ggsave("./Plots/Fig1_c_Map_local.jpg", height = 80, width = 80, units = "mm", 
       dpi = 600)

grob <- grid.arrange(a, b, nrow = 2)
grob <- grid.arrange(grob, c, ncol = 2)
```

```{r Fig 2. N concentration}
# N concentration plot
a <- 
  ggplot(data = massbal, aes(x = date)) +
  # Add vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # S0
  geom_point(data = massbal[massbal$date < as.Date("2018-02-26"),], 
             aes(x = date, y = Nitrate.bowersock_mgNL, fill = "white"), 
             size = 2, shape = 21) +
  # S0 BDL
  geom_segment(aes(x = as.Date("2018-02-26"), xend = as.Date("2018-05-01"),
                   y = 0.01, yend = 0.01), linetype = 1) +
  # S1
  geom_point(aes(y = Nitrate.eric_mgNL, fill = "S1"), size = 2, shape = 21) +
  # S2
  geom_point(aes(y = Nitrate.steve_mgNL, fill = "S2"), size = 2, shape = 21) +
  # S3
  geom_point(aes(y = Nitrate.desoto_mgNL, fill = "S3"), size = 2, shape = 21) +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_log10()+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "a") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
ggsave("./Plots/Fig2_a_Nitrate_time.png", a, height = 77, width = 120, 
       units = "mm", dpi = 600)

# Temperature and discharge
b <- 
  # Water temperature and discharge from the Desoto site
  ggplot(data = sensor_desoto, aes(x = date)) +
  # Add vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # Add data
  geom_line(aes(y = WaterTemp_C), color = "black") +
  geom_line(aes(y = Discharge_m3s/2), color = "grey") +
  # axis and color scales
  scale_x_date(limits = c(as_date("2018-02-01"), as_date("2018-05-01")),
               date_breaks = "2 weeks", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0,50), 
                     sec.axis = sec_axis(~.*2, 
                                         name = expression("Q ("*m^3 ~ s^{-1} *")"))) +
  # axis labels
  labs(tag = "b") +
  xlab(NULL) + 
  ylab(expression("T ("*{degree}*C * ")"))+
  # plot theme
  theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA),
        legend.position = "none", legend.title = element_blank(), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
ggsave("./Plots/Fig2_b_T.Q_time.png", b,height = 1.75, width = 4.8)

# Diel zoom-in 
c <- 
  ggplot(data = diel_eric, aes(x = dateTime)) +
  # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-23 00:00:00"),
                xmax = ymd_hms("2018-03-23 06:00:00"),
                ymin = 0, ymax = 11), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-23 20:00:00"),
                xmax = ymd_hms("2018-03-24 06:00:00"),
                ymin = 0, ymax = 11), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-24 20:00:00"),
                xmax = ymd_hms("2018-03-25 06:00:00"),
                ymin = 0, ymax = 11), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-25 20:00:00"),
                xmax = ymd_hms("2018-03-26 00:00:00"),
                ymin = 0, ymax = 11), fill = "lightgrey") +
  # Plot S1 data on top
  geom_point(aes(y = Nitrate_mgL, fill = "S1"), size = 2, shape = 21) +
  
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-23 00:00:00"), 
                              ymd_hms("2018-03-26 00:00:00")),
               date_breaks = "1 day", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0, 11))+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "c") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
d <- 
  ggplot(data = diel_steve, aes(x = dateTime)) +
    # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-28 00:00:00"),
                xmax = ymd_hms("2018-03-28 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-28 20:00:00"),
                xmax = ymd_hms("2018-03-29 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-29 20:00:00"),
                xmax = ymd_hms("2018-03-30 06:00:00"),
                ymin = 0, ymax = 0.6), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-30 20:00:00"),
                xmax = ymd_hms("2018-03-31 00:00:00"),
                ymin = 0, ymax = 0.6), fill = "lightgrey") +
  # S2
  geom_point(aes(y = Nitrate_mgL, fill = "S2"), size = 2, shape = 21) +
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-28 00:00:00"), 
                              ymd_hms("2018-03-31 00:00:00")),
               date_breaks = "1 days", date_labels = "%b %e" ) + 
  #scale_y_log10()+
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  scale_y_continuous(limits = c(0, 0.6)) +
  # axis labels
  labs(tag = "d") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
e <- 
  ggplot(data = diel_desoto, aes(x = dateTime)) +
  # Add grey bars for local nighttime
  geom_rect(aes(xmin = ymd_hms("2018-03-24 00:00:00"),
                xmax = ymd_hms("2018-03-24 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-24 20:00:00"),
                xmax = ymd_hms("2018-03-25 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-25 20:00:00"),
                xmax = ymd_hms("2018-03-26 06:00:00"),
                ymin = 0, ymax = 0.75), fill = "lightgrey") +
  geom_rect(aes(xmin = ymd_hms("2018-03-26 20:00:00"),
                xmax = ymd_hms("2018-03-27 00:00:00"),
                ymin = 0, ymax = 0.75), fill = "lightgrey") +
  # S3
  geom_point(aes(y = Nitrate_mgL, fill = "S3"), size = 2, shape = 21) +
  # axis and color scales
  scale_x_datetime(limits = c(ymd_hms("2018-03-24 00:00:00"), 
                              ymd_hms("2018-03-27 00:00:00")),
               date_breaks = "1 days", date_labels = "%b %e" ) + 
  scale_y_continuous(limits = c(0, 0.75)) +
  scale_fill_manual(values = c("S0" = "#000000", "S1" = "#FF0000", 
                                 "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S0", "S1", "S2", "S3")) +
  # axis labels
  labs(tag = "e") +
  xlab(NULL) + 
  ylab(expression(NO[3]^{"-"} ~~ "(mg-N" ~~ L^{-1} * ")"))+
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

grob2 <- gridExtra::grid.arrange(c, d, e, ncol = 1)
ggsave("./Plots/Fig2_cde_DielN.png", grob2, height = 115, width = 63, 
       units = "mm", dpi = 600)
```

```{r Fig 3. Metabolism}
# S1S2
a <- 
  ggplot(data = metab, aes(x = date)) +
  # Horizontal line at Y = 0
  geom_hline(yintercept = 0) +
  # Vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # Plot GPP
  geom_ribbon(aes(ymin = GPP.lower.S1S2, ymax = GPP.upper.S1S2), 
              fill = "lightgrey", alpha = 0.7) +
  geom_point(aes(y = GPP.S1S2, fill = "S2"), size = 2, shape = 21) +
  # Plot ER
  geom_ribbon(aes(ymin = ER.lower.S1S2, ymax = ER.upper.S1S2), 
              fill = "lightgrey", alpha = 0.7) +
  geom_point(aes(y = ER.S1S2), size = 2, shape = 21, fill = "white") +
  # y-axis limits
  scale_y_continuous(limits = c(-12, 17), breaks = c(-10, -5, 0, 5, 10, 15)) +
  # Axis labels
  labs(x = NULL, tag = "a",
       y = bquote("GPP or ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

# DeSoto (S3)
b <- 
  ggplot(data = metab, aes(x = date)) +
  # Horizontal line at Y = 0
  geom_hline(yintercept = 0) +
  # Vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # ER
  geom_ribbon(aes(ymin = ER.lower.S3, ymax = ER.upper.S3), 
              fill = "lightgrey", alpha = 0.7) +
  geom_point(aes(y = ER.S3), size = 2, shape = 21, fill = "white") +
  # GPP
  geom_ribbon(aes(ymin = GPP.lower.S3, ymax = GPP.upper.S3), 
              fill = "lightgrey", alpha = 0.7) +
  geom_point(aes(y = GPP.S3, fill = "S3"), size = 2, shape = 21) +
  # y-axis limits
  scale_y_continuous(limits = c(-12, 17), breaks = c(-10, -5, 0, 5, 10, 15)) +
  # Axis labels
  labs(x = NULL, tag = "b",
       y = bquote("GPP or ER (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) +
  # Theme adjustments
  theme_classic() +
  scale_fill_manual(values = c("S1" = "#FF0000", 
                               "S2" = "#23baaf", "S3" = "#F2AD00"),
                     breaks = c("S1", "S2", "S3")) +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

grob <- grid.arrange(a,b, ncol = 1)
ggsave("./Plots/Fig3_MetabPlot.png", grob, height = 95, width = 115, units = "mm", 
       dpi = 600)

# Average stats
mean(metab$GPP.S1S2, na.rm = T) # mean GPP at S1-S2
sd(metab$GPP.S1S2, na.rm = T) # sd of GPP at S1-S2
mean(metab$GPP.S3[metab$GPP.S1S2], na.rm = T) # mean GPP at S3 (during the same period as S1-S2)
sd(metab$GPP.S3[metab$GPP.S1S2], na.rm = T)  # sd of GPP at S3 (during the same period as S1-S2)
```

```{r Fig 4: Uptake and Vf}
# U ############################################################################
a <- 
  ggplot(data = uptake.long, aes(x = Date, y = UaNO3_gNm2day, fill = site)) +
  facet_wrap(~site, nrow = 1) +
  # Add vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # Add points
  geom_point(shape = 21) +
  # Add regression line to S2
  geom_smooth(data = subset(uptake.long, site == "S2"), method = lm, 
              color = "black", fill = "grey") +
  # Add regression line to S3
  geom_smooth(data = subset(uptake.long, site == "S3"), method = lm, 
              color = "black", fill = "grey") +
  # y-axis limits
  scale_y_log10(breaks = c(0.01, 0.1, 1, 10, 100), 
                labels = c(0.01, 0.1, 1, 10, 100)) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S1_scaled" = "#FF0000",
                               "S2" = "#23baaf", 
                               "S3" = "#F2AD00"),
                     limits = c("S1", "S1_scaled", "S2", "S3")) +
  # axis labels
  labs(tag = "a") +
  xlab(NULL) + 
  ylab(expression(U[Diel]*" (g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
ggsave("./Plots/Fig4_a_Udiel.png", a, height = 57.5, width = 127, units = "mm", 
       dpi = 600)

# Vf ###########################################################################
b <- 
  ggplot(data = vf, aes(x = Date, y = vf_mmmin, fill = site)) +
  facet_grid(~site) +
  # Add vertical line at release stop date
  geom_vline(xintercept = ymd("2018-04-01"), linetype = 2) +
  # Add points
  geom_point(shape = 21) +
  # Labels
  labs(tag = "b") +
  xlab(NULL) +
  ylab(expression(V[f] ~~ "(mm" ~ min^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
ggsave("./Plots/Fig4_b_Vf.png", b, height = 57.5, width = 122, units = "mm", 
       dpi = 600)

grob <- grid.arrange(a,b)
ggsave("./Plots/Fig4_U_Vf.png", grob, height = 57.5*2, width = 127, units = "mm", 
       dpi = 600)
```

```{r Fig 5: Predicted uptake fig}
# Revisions: compare autotrophic C:N of 16 to autotrophic C:N of 20
a <- ggplot(data = stoich16, aes(x = Upred_gNm2day.S1S2, y = UaNO3_gNm2day.steve)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point(data = subset(stoich16, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich16, ReleaseStatus == "After"), fill = "#23baaf", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a", title = "Upred calculated using autotrophic C:N = 16") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
b <- ggplot(data = stoich20, aes(x = Upred_gNm2day.S1S2, y = UaNO3_gNm2day.steve)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point(data = subset(stoich20, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich20, ReleaseStatus == "After"), fill = "#23baaf", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "b", title = "Upred calculated using autotrophic C:N = 20 (Original)") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
c <- 
  ggplot(data = stoich16, aes(x = Upred_gNm2day.S3, y = UaNO3_gNm2day.desoto)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Add regression line
  geom_smooth(method = lm, 
              color = "black", fill = "grey") +
  # Data points
  geom_point(data = subset(stoich16, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich16, ReleaseStatus == "After"), fill = "#F2AD00", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "c", title = "Upred calculated using autotrophic C:N = 16") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
d <- 
  ggplot(data = stoich20, aes(x = Upred_gNm2day.S3, y = UaNO3_gNm2day.desoto)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Add regression line
  geom_smooth(method = lm, 
              color = "black", fill = "grey") +
  # Data points
  geom_point(data = subset(stoich20, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich20, ReleaseStatus == "After"), fill = "#F2AD00", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "d", title = "Upred calculated using autotrophic C:N = 20 (Original)") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
grob <- grid.arrange(a, b, c, d, ncol = 2, nrow = 2)
ggsave(grob, file = "./Plots/Revisions_UpredStoichiometry.png", width = 8, height = 8, 
       units = "in", dpi = 600)

# Black points: After (April), White points: during (Feb, March)
# S2
a <- 
  ggplot(data = stoich, aes(x = Ustoic_gNm2day.S1S2, y = UaNO3_gNm2day.steve)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), fill = "#23baaf", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "a") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))
# S3
b <- 
  ggplot(data = stoich, aes(x = Ustoic_gNm2day.S3, y = UaNO3_gNm2day.desoto)) +
  # 1:1 line
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  # Add regression line
  geom_smooth(method = lm, 
              color = "black", fill = "grey") +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), fill = "white", 
             size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), fill = "#F2AD00", 
             size = 2, shape = 21) +
  # Axis labels
  xlab(expression(U[Pred] ~ "(g-N" ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g-N" ~~ m^{-2} ~ day^{-1} * ")")) +
  labs(tag = "b") +
  # Adjust limits using coord_cartesian to prevent cutoff of trend line ribbon
  coord_cartesian(xlim = c(0, 0.55), ylim = c(-0.1, 4)) +
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5)) +
  scale_y_continuous(breaks = c(0,1,2,3,4)) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

grob <- grid.arrange(a, b, ncol = 1, nrow = 2)
ggsave(grob, file = "./Plots/Fig5_U_Upred.png", width = 95, height = 115*2-50, 
       units = "mm", dpi = 600)
```

```{r Fig 6. GPP & ER vs Udiel}
# Plot
a <- 
  ggplot(data = NULL, aes(x = GPP.S1S2, y = UaNO3_gNm2day.steve)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"),
             fill = "#23baaf", size = 2, shape = 21) +
  # Axis limits
  coord_cartesian(xlim = c(-0.5, 15.5), ylim = c(-1, 4.5)) +
  scale_x_continuous(breaks = c(0, 5, 10, 15)) +
  scale_y_continuous(breaks = c(0, 2, 4)) +
  # Axis labels
  xlab(bquote("GPP (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g N" ~~ m^{-2} ~ d^{-1} * ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

b <- 
  ggplot(data = NULL, aes(x = GPP.S3, y = UaNO3_gNm2day.desoto)) +
  # Add regression line
  geom_smooth(data = stoich, method = lm, color = "black", 
              fill = "grey") +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#F2AD00", size = 2, shape = 21) +
  # Axis limits
  coord_cartesian(xlim = c(-0.5, 15.5), ylim = c(-1, 4.5)) +
  scale_x_continuous(breaks = c(0, 5, 10, 15)) +
  scale_y_continuous(breaks = c(0, 2, 4)) +
  # Axis labels
  xlab(bquote("GPP (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g N" ~~ m^{-2} ~ d^{-1} * ")")) +
  labs(tag = "b") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

c <- ggplot(data = NULL, aes(x = ER.S1S2, y = UaNO3_gNm2day.steve)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"),
             fill = "#23baaf", size = 2, shape = 21) +
  # Axis limits
  scale_x_continuous(limits = c(-0.5, 8.5), breaks = c(0,2,4,6,8,10)) +
  scale_y_continuous(limits = c(-1, 4.5), breaks = c(0, 2, 4)) +
  # Axis labels
  xlab(bquote("|ER| (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g N" ~~ m^{-2} ~ d^{-1} * ")")) +
  labs(tag = "c") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

d <- 
  ggplot(data = NULL, aes(x = ER.S3, y = UaNO3_gNm2day.desoto)) +
  # Add regression line
  geom_smooth(data = stoich, method = lm, color = "black", 
              fill = "grey") +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#F2AD00", size = 2, shape = 21) +
  # Axis limits
  coord_cartesian(xlim = c(-0.5, 8.5), ylim = c(-0.5, 4.5)) +
  scale_x_continuous(breaks = c(0,2,4,6,8,10)) +
  scale_y_continuous(breaks = c(0, 2, 4)) +
  # Axis labels
  xlab(bquote("|ER| (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(U[Diel] ~ "(g N" ~~ m^{-2} ~ d^{-1} * ")")) +
  labs(tag = "d") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))


grob <- grid.arrange(a, b, c, d, ncol = 2, nrow = 2)
ggsave("./Plots/Fig6_GPP_ER_Udiel.png", grob, height = 95, width = 115,
       units = "mm", dpi = 600)
```

```{r Supplemental. GPP & ER vs Vf}
# Plot
a <- 
  ggplot(data = NULL, aes(x = GPP.S1S2, y = vf_mmmin.steve)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#23baaf", size = 2, shape = 21) +
  # Axis limits
  scale_x_continuous(limits = c(-0.5, 15.5), breaks = c(0, 5, 10, 15)) +
  scale_y_continuous(limits = c(-0.5, 9.5), breaks = c(0, 3, 6, 9)) +
  # Axis labels
  xlab(bquote("GPP (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

b <-
  ggplot(data = NULL, aes(x = GPP.S3, y = vf_mmmin.desoto)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#F2AD00", size = 2, shape = 21) +
  # Axis limits
  scale_x_continuous(limits = c(-0.5, 15.5), breaks = c(0, 5, 10, 15)) +
  scale_y_continuous(limits = c(-0.5, 9.5), breaks = c(0, 3, 6, 9)) +
  # Axis labels
  xlab(bquote("GPP (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "b") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))



c <- ggplot(data = NULL, aes(x = ER.S1S2, y = vf_mmmin.steve)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#23baaf", size = 2, shape = 21) +
  # Axis limits
  scale_x_continuous(limits = c(-0.5, 8.5), breaks = c(0,2,4,6,8,10)) +
  scale_y_continuous(limits = c(-0.5, 9.5), breaks = c(0, 3, 6, 9)) +
  # Axis labels
  xlab(bquote("|ER| (g" ~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "c") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

d <-
  ggplot(data = NULL, aes(x = ER.S3, y = vf_mmmin.desoto)) +
  # Data points
  geom_point(data = subset(stoich, ReleaseStatus == "During"), 
             fill = "white", size = 2, shape = 21) +
  geom_point(data = subset(stoich, ReleaseStatus == "After"), 
             fill = "#F2AD00", size = 2, shape = 21) +
  # Axis limits
  scale_x_continuous(limits = c(-0.5, 8.5), breaks = c(0,2,4,6,8,10)) +
  scale_y_continuous(limits = c(-0.5, 9.5), breaks = c(0, 3, 6, 9)) +
  # Axis labels
  xlab(bquote("|ER| (g" ~~ O[2] ~ m^-2 ~ d^-1 ~ ")")) + 
  ylab(expression(V[f] ~ "(mm" ~~ min^{-1}* ")")) +
  labs(tag = "d") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

grob <- grid.arrange(a, b, c, d, ncol = 2, nrow = 2)
ggsave("./Plots/S1_GPP_ER_Vf.png", grob, height = 95, width = 115,
       units = "mm", dpi = 600)
```

```{r Fig 7: Meta-analysis}
### Calculate means
meanData <- data.frame(GPP.mean = c(NA,
                                    mean(metab$GPP.S1S2, na.rm = TRUE),
                                    mean(metab$GPP.S3, na.rm = TRUE)),
           ER.mean = c(NA,
                       abs(mean(metab$ER.S1S2, na.rm = TRUE)),
                       abs(mean(metab$ER.S3, na.rm = TRUE))),
           Q.mean = c(mean(massbal$Q.lawrence_Ls)/1000,
                      mean(massbal$Q.lawrence_Ls)/1000,
                      mean(massbal$Q.desoto_Ls)/1000), 
           U.mean = c(mean(uptake$UaNO3_gNm2day.eric, na.rm = TRUE),
                      mean(uptake$UaNO3_gNm2day.steve, na.rm = TRUE),
                      mean(uptake$UaNO3_gNm2day.desoto, na.rm = TRUE)),
           Vf.mean = c(mean(vf$vf_mmmin[vf$site == "S1"], na.rm = TRUE),
                       mean(vf$vf_mmmin[vf$site == "S2"], na.rm = TRUE),
                       mean(vf$vf_mmmin[vf$site == "S3"], na.rm = TRUE)),
           row.names = c("S1", "S2", "S3"))
# Converting between uptake and uptake velocity
# vf mm/min * NO3 mg/L *[1000L/m3] *[1m/1000mm]*[1g/1000mg] *[1440 min/d] = gN/day*m2
tank$U_gNm2day <- tank$NO3_Vf_mmmin*(tank$NO3_Cb_mgNL/1000)*1440

### Meta-analysis Discharge vs GPP, Hall et al 2016 Data #######################
a <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = hall, aes(x = q_m3s, y = gpp_gm2d), shape = 21, 
             color = "darkgrey") +
  # Our data
  geom_point(data = meanData, 
             aes(x = Q.mean, y = GPP.mean, 
                 fill = c("S1", "S2", "S3")), size = 3, shape = 21) +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("GPP (g" ~ O[2] ~ m^{-2} ~ d^{-1}*")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  labs(tag = "a") +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

### Discharge v. total uptake, tank et al 2008 ################################
b <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = tank, aes(x = Discharge_Ls/1000, 
                              y = NO3_Vf_mmmin*(NO3_Cb_mgNL/1000)*1440), 
             shape = 21, color = "darkgrey") +
  # Rode et al 2016 and Hensley et al 2014 data
  geom_point(data = rode.hensley, aes(x = Discharge_m3s,
                                      y = U_mgNm2day/1000),
             shape = 21, color = "darkgrey") +
  # Our data
  geom_point(data = meanData, 
             aes(x = Q.mean, y = U.mean, 
                 fill = c("S1", "S2", "S3")), size = 3, shape = 21) +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1), 
                limits = c(NA, 105)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  labs(tag = "b") +
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("U (g-N" ~~ m^{-2} ~ d^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

### Meta-analysis Discharge vs ER, Hall et al 2016 Data #######################
c <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = hall, aes(x = q_m3s, y = er_gm2d), shape = 21, 
             color = "darkgrey") +
  # Our data
  geom_point(data = meanData, 
             aes(x = Q.mean, y = ER.mean, 
                 fill = c("S1", "S2", "S3")), size = 3, shape = 21) +
  # Add correlation coeff
  #ggpubr::stat_cor(color = "black", method = "spearman") +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  labs(tag = "c") +
  # Axis labels
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression("|ER| (g" ~ O[2] ~ m^{-2} ~ d^{-1}*")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

### Discharge v. Uptake velocity (Tank et al. 2008) ###########################
d <- 
  ggplot() +
  # Meta-analysis data
  geom_point(data = tank, aes(x = Discharge_Ls/1000, y = NO3_Vf_mmmin), 
             shape = 21, color = "darkgrey") +
  # Rode et al 2016 and Hensley et al 2014 data
  geom_point(data = rode.hensley, aes(x = Discharge_m3s,
                                      y = Vf_mmmin),
             shape = 21, color = "darkgrey") +
  # Our data
  geom_point(data = meanData, 
             aes(x = Q.mean, y = Vf.mean, 
                 fill = c("S1", "S2", "S3")), size = 3, shape = 21) +
  # Axis scales
  scale_x_log10(labels = scales::number_format(accuracy=1, scale=1), 
                limits = c(NA, 105)) +
  scale_y_log10(labels = scales::number_format(accuracy=1, scale=1)) +
  # Axis labels
  labs(tag = "d") +
  xlab(expression("Discharge ("*m^{3} ~ s^{-1}*")")) + 
  ylab(expression(V[f] ~~ "(mm" ~ min^{-1} * ")")) +
  # Color scales
  scale_fill_manual(values = c("S1" = "#FF0000", "S2" = "#23baaf", 
                                "S3" = "#F2AD00"),
                     limits = c("S1", "S2", "S3")) +
  # Plot theme
  theme_classic() +
  theme(legend.position = "none", legend.title = element_blank(),
        panel.border = element_rect(fill = NA), 
        axis.text = element_text(color = "black"),
        text = element_text(size = 8))

arrange <- grid.arrange(a,b,c,d, nrow = 2, ncol = 2)
ggsave("./Plots/Fig7_Meta_Q.png", arrange, height = 95, width = 115, units = "mm", 
       dpi = 600)
```

```{r AddressingReviewerComments_JGRB1}
## Check if ER an K covary within a site #####################################
cov(metab$ER.S1S2, metab$K, use = "complete.obs") # S2 covariance
cor(metab$ER.S1S2, metab$K, use = "complete.obs") # S2 correlation coefficient

# Load K estimates for Desoto
## S3
d <- readRDS("./Outputs/MetabResults_Desoto.RData")$fit@fit$daily %>%
  filter(date >= "2018-02-01" & date <= "2018-05-01")
cov(d$ER_daily_mean, d$K600_daily_mean, use = "complete.obs") # S3 covariance
cor(d$ER_daily_mean, d$K600_daily_mean, use = "complete.obs") # S3 covariance

## Check standard deviation of ln(GPP) for estimation of autotrophic ##########
#  respiration, needs to be < 1 to use Hall & Beaulieu 2013
sd(log(metab$GPP.S1S2), na.rm = TRUE) # S2
sd(log(metab$GPP.S3), na.rm = TRUE) # S3

cov(metab$GPP.S3, metab$ER.S3, use = "complete.obs") # S3 covariance
cor(metab$GPP.S3, metab$ER.S3, use = "complete.obs") # S3 covariance
plot(metab$GPP.S3, metab$ER.S3)
```
