---
title: 'KAWN: Data loading and cleaning'
author: "Michelle Catherine Kelly"
date: "3 June 2018"
output:
  html_notebook
---

```{r setup, echo = FALSE, warning=FALSE, error=FALSE, message=FALSE}
knitr::opts_chunk$set(cache=TRUE)

library(XML)
library(lubridate)
library(data.table)
library(dataRetrieval) # USGS loading
# NEON loading
# library(devtools)
# install_github("NEONScience/NEON-utilities/neonUtilities", dependencies = TRUE)
library(neonUtilities)
```

```{r dataLoad}
# masterFile
  # concatenates local nitratax, miniDOT files into a single master .csv (if no master exists). If data is located on USGS database, pulls from USGS database and saves local master. If local master is present, script loads from file
  # sitename = character vector with proper capitalization
  # USGS = logical vector, if TRUE data should is pulled from USGS, if FALSE data is loaded from local files

masterFile <- function(sitename, USGS){
  
  if(file.exists(paste("KAWN_SensorData_", sitename, ".csv", sep = ""))){
    # if master file exists, load from master file
    dataframe <- read.csv(paste("KAWN_SensorData_", sitename, ".csv", sep = ""), 
                          header = TRUE)
  }
  
  if(!file.exists(paste("KAWN_SensorData_", sitename, ".csv", sep = ""))){ 
    # if master file doesn't exist, compile master file
    if(USGS == FALSE){ 
      # load in nitratax data
      nitratax_XMLtoCSV <- function(filename){
        xmlData <- XML::xmlParse(file = filename)
        xmlData <- XML::xmlToDataFrame(xmlData, homogeneous = F, stringsAsFactors = F)
        xmlData <- xmlData[-(1:6),] # taking out text at top of dataframe
        for (count in 1:length(xmlData)){
          names(xmlData)[count] <- as.character(xmlData[1,count])
        }
        xmlData <- xmlData[-1,] # taking out character rows
        xmlData <- xmlData[,-1] # taking out first blank column
        xmlData$`  TIME  ` <- lubridate::as_datetime(xmlData$`  TIME  `, 
                                                     tz = "America/Chicago",
                                                     format = "%m/%d/%Y %H:%M:%S")
        xmlData$`  NITRATE CONC.  ` <- as.numeric(xmlData$`  NITRATE CONC.  `)
        xmlData$`  ER  ` <- as.numeric(xmlData$`  ER  `)
        xmlData$`  EM  ` <- as.numeric(xmlData$`  EM  `)
        
        xmlData <- data.frame(xmlData$`  TIME  `, xmlData$`  NITRATE CONC.  `)
        names(xmlData) <- c("dateTime", "nitrateNitrite")
        return(xmlData)
      }
      
      nitratax <- nitratax_XMLtoCSV(paste("NITRATAX_", sitename, ".xml", sep = ""))
      
      if(file.exists(paste("miniDOT_", sitename, ".txt", sep = ""))){
      # load in minidot data
        DO <- read.table(file = paste("miniDOT_", sitename, ".txt", sep = ""), 
                         header = TRUE, sep = ",", skip = 8, stringsAsFactors = FALSE, 
                         colClasses = c("numeric", "POSIXct", "POSIXct", "numeric", 
                                        "numeric", "numeric", "numeric", "numeric"),
                         col.names = c("unixTimestamp", "time_UTC", "time_CST", 
                                       "battery_V", "temp_C", "DO_mgL", "DO_sat", "Q"))
        DO <- DO[c(-1, -2, -4, -8)] #drop unix timestamp, time UTC, battery volts, Q
        DO$time_CST <- round_date(DO$time_CST, unit = "5 mins") # round time to nearest 5 min
        
        # merge minidot with nitratax by datetime
        dataframe <- merge(nitratax, DO, by.x = "dateTime", by.y = "time_CST", all = TRUE)
        # save master file
        write.csv(dataframe, row.names = FALSE,
                  file = paste("KAWN_SensorData_", sitename, ".csv", sep = ""))
        
        } else{
          # save master file with just nitratax
          dataframe <- nitratax
          write.csv(dataframe, row.names = FALSE,
                    file = paste("KAWN_SensorData_", sitename, ".csv", sep = ""))
          }
      } else{ # use USGS package to pull data from web, then save locally
        start <- ymd_hms("2018-01-01 00:00:00")
        end <- ymd_hms("2018-06-15 00:00:00")
        
        if(sitename == "Desoto"){
          siteNo <- "06892350"
          pCodes <- c("99133", "00060", "00065", "00300", "00301","00010", 
                      "00095", "00400", "32295", "32318")
          data <- readNWISuv(siteNumbers = siteNo, parameterCd = pCodes, 
                           startDate = start, endDate = end, tz = "America/Chicago")
        
          # Rename columns from codes to readable names
          data <- renameNWISColumns(data)
          # Fix remaining names that are still parameter codes
          names(data)[names(data)=="00301_Inst"] <- "DO_percentsat" 
          names(data)[names(data)=="00301_Inst_cd"] <- "DO_percentsat_cd"
          names(data)[names(data)=="99133_Inst"] <- "nitrateNitrite"
          names(data)[names(data)=="99133_Inst_cd"] <- "nitrateNitrite_cd"
          
          # Convert from American to SI units
          # cubic foot per second to liters per second
          ft3s_m3s <- function(ft3s){
            m3s <- ft3s*0.0283168
            return(m3s)
          }
          # foot to meters
          ft_m <- function(ft){
            m <- 0.3048*ft
            return(m)
          }
          data$Flow_Inst <- ft3s_m3s(data$Flow_Inst)
          data$GH_Inst <- ft_m(data$GH_Inst)
          
          # drop agency code, siteNo, various quality codes
          dataframe <- data[c(-1,-2,-5,-7,-9,-11,-13,-15,-17,-19,-21,-22)]
        }
        # save the USGS data locally
        write.csv(dataframe, row.names = FALSE,
                  file = paste("KAWN_SensorData_", sitename, ".csv", sep = ""))
      }
  }
  return(dataframe)
  }

bowersock <- masterFile(sitename = "Bowersock", USGS = FALSE)
eric <- masterFile(sitename = "Eric", USGS = FALSE)
steve <- masterFile(sitename = "Steve", USGS = FALSE)
desoto <- masterFile(sitename = "Desoto", USGS = TRUE)
```








Import of Nitratax data into R environment, cleanup
```{r NitrataxLoadingCleanup, include=FALSE}
# Variable descriptions:    
      # loadfromCSV = logical vector, if TRUE data will be loaded from .csv files
                                    # if FALSE data will be converted from .xml to .csv
                                    # (computationally much faster to load from .csv)
      # bowersock_N = Nitratax sensor located at the bowersock dam upstream of waste release
      # eric_N = Nitratax sensor located at the waste release point
      # steve_N = Nitratax sensor located about ~5 miles downstream of bowersock

loadfromCSV <- TRUE

if (loadfromCSV == TRUE){
  bowersock_N <- read.csv(file = "KansasR_Nitratax_Bowersock.csv", 
                          header = TRUE,
                          colClasses = c("POSIXct", "numeric"))
  eric_N <- read.csv(file = "KansasR_Nitratax_Eric.csv", 
                     header = TRUE,
                     colClasses = c("POSIXct", "numeric"))
  steve_N <- read.csv(file = "KansasR_Nitratax_Steve.csv", 
                      header = TRUE,
                      colClasses = c("POSIXct", "numeric"))
  
  names(bowersock_N) <- c("Date and time", "Nitrate plus nitrite as mg-N/L")
  names(eric_N) <- c("Date and time", "Nitrate plus nitrite as mg-N/L")
  names(steve_N) <- c("Date and time", "Nitrate plus nitrite as mg-N/L")
  
  cat("data loaded from .csv file")
}
if (loadfromCSV == FALSE) {
  bowersock_N <- Nitratax_XMLtoCSV(filename = "NITRATAX_Bowersock_Pulled05-07-2018.xml", 
                                   sensor = "Bowersock", 
                                   deployDate = "2018-01-13")
  eric_N <- Nitratax_XMLtoCSV(filename = "NITRATAX_Eric_Pulled05-07-2018.xml", 
                              sensor = "Eric", 
                              deployDate = "2018-02-19")
  steve_N <- Nitratax_XMLtoCSV(filename = "NITRATAX_Steve_Pulled05-07-2018.xml", 
                               sensor = "Steve", 
                               deployDate = "2018-01-31")
  
  cat("data loaded from .xml file")
}
# bowersock N cleanup
bowersock_N$`Nitrate plus nitrite as mg-N/L`[bowersock_N$`Date and time` 
                                             %between% 
                                               c(ymd_hms("2018-02-05 21:30:00", tz = "America/Chicago"),
                                                 ymd_hms("2018-02-07 15:30:00", tz = "America/Chicago"))] <- NA

bowersock_N$`Nitrate plus nitrite as mg-N/L`[bowersock_N$`Date and time` 
                                             %between% 
                                               c(ymd_hms("2018-02-16 11:00:00", tz = "America/Chicago"),
                                                 ymd_hms("2018-02-16 11:30:00", tz = "America/Chicago"))] <- NA
# for purposes of sfs talk.....
bowersock_N$`Nitrate plus nitrite as mg-N/L`[bowersock_N$`Date and time` 
                                             %between% 
                                               c(ymd_hms("2018-05-01 00:00:00", tz = "America/Chicago"),
                                                 ymd_hms("2018-05-07 00:00:00", tz = "America/Chicago"))] <- NA

# eric N cleanup
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-02-27 00:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-15 19:30:00", tz = "America/Chicago"))] <- NA
# large precip events
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-18 10:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-18 13:15:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-19 04:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-19 06:00:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-19 08:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-19 10:15:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-19 11:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-19 18:45:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-26 07:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-26 10:30:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-26 11:45:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-26 19:45:00", tz = "America/Chicago"))] <- NA
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-04-26 11:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-04-26 13:00:00", tz = "America/Chicago"))] <- NA
# for purposes of sfs talk.....
eric_N$`Nitrate plus nitrite as mg-N/L`[eric_N$`Date and time` 
                                        %between% 
                                          c(ymd_hms("2018-05-01 00:00:00", tz = "America/Chicago"),
                                            ymd_hms("2018-05-07 00:00:00", tz = "America/Chicago"))] <- NA

# steve N cleanup
steve_N$`Date and time` <- ymd_hms(steve_N$`Date and time`, tz = "America/Chicago")
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-02-13 13:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-02-13 18:45:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-02-14 11:45:00", tz = "America/Chicago"),
                                             ymd_hms("2018-02-14 14:45:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-02-22 12:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-02-27 20:45:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-01 14:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-01 14:30:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-03-09 00:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-03-27 11:30:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-04-12 09:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-04-12 09:30:00", tz = "America/Chicago"))] <- NA
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-04-20 15:15:00", tz = "America/Chicago"),
                                             ymd_hms("2018-04-20 15:45:00", tz = "America/Chicago"))] <- NA
# for purposes of sfs talk.....
steve_N$`Nitrate plus nitrite as mg-N/L`[steve_N$`Date and time` 
                                         %between% 
                                           c(ymd_hms("2018-05-01 00:00:00", tz = "America/Chicago"),
                                             ymd_hms("2018-05-07 00:00:00", tz = "America/Chicago"))] <- NA
```

***  

## miniDOT Data  

Loading miniDOT sensor files: dissolved oxygen and temperature data  
```{r DOloadingCleanup, include=FALSE}
steve_DO <- read.table(file = "miniDOT_Steve_Pulled04-20-2018.txt", header = TRUE,
                       sep = ",", skip = 8, stringsAsFactors = FALSE,
                       colClasses = c("numeric", "POSIXct", "POSIXct", "numeric",
                                      "numeric", "numeric", "numeric", "numeric"),
                       col.names = c("unixTimestamp", "time_UTC", "time_CST", "battery_V",
                                     "temp_C", "DO_mgL", "DO_sat", "Q"))

eric_DO <- read.table(file = "miniDOT_Eric_Pulled05-07-2018.txt", header = TRUE,
                       sep = ",", skip = 8, stringsAsFactors = FALSE,
                       colClasses = c("numeric", "POSIXct", "POSIXct", "numeric",
                                      "numeric", "numeric", "numeric", "numeric"),
                       col.names = c("unixTimestamp", "time_UTC", "time_CST", "battery_V",
                                     "temp_C", "DO_mgL", "DO_sat", "Q"))

# Eric DO cleanup
# 19 - 25 Feb
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-02-19 10:38:00", tz = "America/Chicago"),
                   ymd_hms("2018-02-25 01:28:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-02-19 10:38:00", tz = "America/Chicago"),
                   ymd_hms("2018-02-25 01:28:00", tz = "America/Chicago"))] <- NA
# 5 - 15 Mar
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-05 09:58:00", tz = "America/Chicago"),
                   ymd_hms("2018-03-15 11:08:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-05 09:58:00", tz = "America/Chicago"),
                   ymd_hms("2018-03-15 11:08:00", tz = "America/Chicago"))] <- NA
# 28 Mar
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-28 04:25:00", tz = "America/Chicago"),
                   ymd_hms("2018-03-28 21:25:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-28 04:25:00", tz = "America/Chicago"),
                   ymd_hms("2018-03-28 21:25:00", tz = "America/Chicago"))] <- NA
# 30 Mar - 5 Apr
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-30 23:35:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-05 12:00:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-03-30 23:35:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-05 12:00:00", tz = "America/Chicago"))] <- NA
# 14-18 Apr
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-04-14 12:23:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-18 00:00:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-04-14 12:23:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-18 00:00:00", tz = "America/Chicago"))] <- NA
# 25-30 Apr
eric_DO$DO_mgL[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-04-25 19:33:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-30 15:53:00", tz = "America/Chicago"))] <- NA
eric_DO$temp_C[eric_DO$time_CST 
               %between% 
                 c(ymd_hms("2018-04-25 19:33:00", tz = "America/Chicago"),
                   ymd_hms("2018-04-30 15:53:00", tz = "America/Chicago"))] <- NA

# Steve
# 30 Jan
steve_DO$DO_mgL[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-01-30 15:24:00", tz = "America/Chicago"),
                  ymd_hms("2018-01-30 16:54:00", tz = "America/Chicago"))] <- NA
steve_DO$temp_C[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-01-30 15:24:00", tz = "America/Chicago"),
                  ymd_hms("2018-01-30 16:54:00", tz = "America/Chicago"))] <- NA
# 9-12 Mar
steve_DO$DO_mgL[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-03-09 17:17:00", tz = "America/Chicago"),
                  ymd_hms("2018-03-12 10:47:00", tz = "America/Chicago"))] <- NA
steve_DO$temp_C[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-03-09 17:17:00", tz = "America/Chicago"),
                  ymd_hms("2018-03-12 10:47:00", tz = "America/Chicago"))] <- NA
# 13 Mar
steve_DO$DO_mgL[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-03-13 05:09:00", tz = "America/Chicago"),
                  ymd_hms("2018-03-13 08:49:00", tz = "America/Chicago"))] <- NA
steve_DO$temp_C[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-03-13 05:09:00", tz = "America/Chicago"),
                  ymd_hms("2018-03-13 08:49:00", tz = "America/Chicago"))] <- NA
# 19-20 Mar
steve_DO$DO_mgL[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-04-19 23:37:00", tz = "America/Chicago"),
                  ymd_hms("2018-04-20 08:17:00", tz = "America/Chicago"))] <- NA
steve_DO$temp_C[steve_DO$time_CST 
                %between% 
                c(ymd_hms("2018-04-19 23:37:00", tz = "America/Chicago"),
                  ymd_hms("2018-04-20 08:17:00", tz = "America/Chicago"))] <- NA
```

***



## NEON Data   

```{r NEONpullCleanup, include=FALSE, eval=FALSE}
downloadNEONfiles <- FALSE

if (downloadNEONfiles == TRUE){
  dir.create(paste0(getwd(), "/NEONfiles"))
  
  ######## PAR ############
  getPackage(dpID = "DP1.00024.001", site_code = "UKFS",
           year_month = "2018-02", package = "basic",
           savepath = paste(getwd(), "NEONfiles", sep = "/")) # Feb at KU field station
  getPackage(dpID = "DP1.00024.001", site_code = "UKFS",
           year_month = "2018-03", package = "basic",
           savepath = paste(getwd(), "NEONfiles", sep = "/")) # March at KU field station
  #getPackage(dpID = "DP1.00024.001", site_code = "UKFS",
           #year_month = "2018-04", package = "basic",
           #savepath = getwd()) # April at KU field station 
  stackByTable(dpID = "DP1.00024.001", 
               filepath = paste0(getwd(), "/NEONfiles"), 
               savepath = paste0(getwd(), "/NEONfiles"), 
               folder = TRUE)
  
  ######## Barometric pressure ############
  getPackage(dpID = "DP1.00004.001", site_code = "UKFS",
           year_month = "2018-02", package = "basic",
           savepath = paste(getwd(), "NEONfiles", sep = "/")) # Feb at KU field station
  getPackage(dpID = "DP1.00004.001", site_code = "UKFS",
           year_month = "2018-03", package = "basic",
           savepath = paste(getwd(), "NEONfiles", sep = "/")) # March
  #getPackage(dpID = "DP1.00004.001", site_code = "UKFS",
           #year_month = "2018-04", package = "basic",
           #savepath = paste(getwd(), "NEONfiles", sep = "/")) # April
  stackByTable(dpID = "DP1.00004.001", 
               filepath = paste0(getwd(), "/NEONfiles"), 
               savepath = paste0(getwd(), "/NEONfiles"), 
               folder = TRUE)
}

PAR <- read.csv(file = paste0(getwd(), "/NEONfiles", "/stackedFiles", 
                              "/PARPAR_1min.csv"), header = TRUE)
PAR <- subset(PAR, subset = PAR$verticalPosition == 10) # take measurements that are closest to ground
PAR$startDateTime <- ymd_hms(PAR$startDateTime, tz = "America/Chicago")
PAR <- data.frame(
    dateTime = PAR$startDateTime,
    mean = PAR$PARMean,
    min = PAR$PARMinimum,
    max = PAR$PARMaximum,
    var = PAR$PARVariance
)

# PAR units are micromoles per m^2 per second

#### Barometric pressure, units are kPa
BarPress <- read.csv(file = paste0(getwd(), "/NEONfiles", "/stackedFiles", 
                              "/BP_30min.csv"), header = TRUE)
BarPress$startDateTime <- ymd_hms(BarPress$startDateTime, tz = "America/Chicago")
BarPress <- data.frame(
  dateTime = BarPress$startDateTime,
  mean = BarPress$staPresMean,
  min = BarPress$staPresMinimum,
  max = BarPress$staPresMaximum,
  var = BarPress$staPresVariance
)
# convert to mmHg
kpa_mmhg <- function(kpa){
  mmhg <- kpa*7.5006156130264
  return(mmhg)
}
BarPress$mean <- kpa_mmhg(BarPress$mean)
BarPress$min <- kpa_mmhg(BarPress$min)
BarPress$max <- kpa_mmhg(BarPress$max)
BarPress$var <- kpa_mmhg(BarPress$var)
```
